// Code generated by protoc-gen-go. DO NOT EDIT.
// source: provider.proto

/*
Package provider_pb is a generated protocol buffer package.

It is generated from these files:
	provider.proto

It has these top-level messages:
	PingReq
	PingResp
	StoreReq
	StoreResp
	RetrieveReq
	RetrieveResp
	GetFragmentReq
	GetFragmentResp
*/
package provider_pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PingReq struct {
	NodeId string `protobuf:"bytes,1,opt,name=nodeId" json:"nodeId,omitempty"`
}

func (m *PingReq) Reset()                    { *m = PingReq{} }
func (m *PingReq) String() string            { return proto.CompactTextString(m) }
func (*PingReq) ProtoMessage()               {}
func (*PingReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PingReq) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

type PingResp struct {
	NodeId string `protobuf:"bytes,1,opt,name=nodeId" json:"nodeId,omitempty"`
}

func (m *PingResp) Reset()                    { *m = PingResp{} }
func (m *PingResp) String() string            { return proto.CompactTextString(m) }
func (*PingResp) ProtoMessage()               {}
func (*PingResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PingResp) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

type StoreReq struct {
	Data   []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Auth   string `protobuf:"bytes,2,opt,name=auth" json:"auth,omitempty"`
	Ticket string `protobuf:"bytes,3,opt,name=ticket" json:"ticket,omitempty"`
	Key    string `protobuf:"bytes,4,opt,name=key" json:"key,omitempty"`
}

func (m *StoreReq) Reset()                    { *m = StoreReq{} }
func (m *StoreReq) String() string            { return proto.CompactTextString(m) }
func (*StoreReq) ProtoMessage()               {}
func (*StoreReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *StoreReq) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *StoreReq) GetAuth() string {
	if m != nil {
		return m.Auth
	}
	return ""
}

func (m *StoreReq) GetTicket() string {
	if m != nil {
		return m.Ticket
	}
	return ""
}

func (m *StoreReq) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type StoreResp struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (m *StoreResp) Reset()                    { *m = StoreResp{} }
func (m *StoreResp) String() string            { return proto.CompactTextString(m) }
func (*StoreResp) ProtoMessage()               {}
func (*StoreResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *StoreResp) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type RetrieveReq struct {
	Auth   string `protobuf:"bytes,1,opt,name=auth" json:"auth,omitempty"`
	Ticket string `protobuf:"bytes,2,opt,name=ticket" json:"ticket,omitempty"`
	Key    string `protobuf:"bytes,3,opt,name=key" json:"key,omitempty"`
}

func (m *RetrieveReq) Reset()                    { *m = RetrieveReq{} }
func (m *RetrieveReq) String() string            { return proto.CompactTextString(m) }
func (*RetrieveReq) ProtoMessage()               {}
func (*RetrieveReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *RetrieveReq) GetAuth() string {
	if m != nil {
		return m.Auth
	}
	return ""
}

func (m *RetrieveReq) GetTicket() string {
	if m != nil {
		return m.Ticket
	}
	return ""
}

func (m *RetrieveReq) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type RetrieveResp struct {
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *RetrieveResp) Reset()                    { *m = RetrieveResp{} }
func (m *RetrieveResp) String() string            { return proto.CompactTextString(m) }
func (*RetrieveResp) ProtoMessage()               {}
func (*RetrieveResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *RetrieveResp) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetFragmentReq struct {
	Auth      string `protobuf:"bytes,1,opt,name=auth" json:"auth,omitempty"`
	Key       string `protobuf:"bytes,2,opt,name=key" json:"key,omitempty"`
	Size      int32  `protobuf:"varint,3,opt,name=size" json:"size,omitempty"`
	Positions []byte `protobuf:"bytes,4,opt,name=positions,proto3" json:"positions,omitempty"`
}

func (m *GetFragmentReq) Reset()                    { *m = GetFragmentReq{} }
func (m *GetFragmentReq) String() string            { return proto.CompactTextString(m) }
func (*GetFragmentReq) ProtoMessage()               {}
func (*GetFragmentReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *GetFragmentReq) GetAuth() string {
	if m != nil {
		return m.Auth
	}
	return ""
}

func (m *GetFragmentReq) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *GetFragmentReq) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *GetFragmentReq) GetPositions() []byte {
	if m != nil {
		return m.Positions
	}
	return nil
}

type GetFragmentResp struct {
	Data [][]byte `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (m *GetFragmentResp) Reset()                    { *m = GetFragmentResp{} }
func (m *GetFragmentResp) String() string            { return proto.CompactTextString(m) }
func (*GetFragmentResp) ProtoMessage()               {}
func (*GetFragmentResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *GetFragmentResp) GetData() [][]byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*PingReq)(nil), "provider.pb.PingReq")
	proto.RegisterType((*PingResp)(nil), "provider.pb.PingResp")
	proto.RegisterType((*StoreReq)(nil), "provider.pb.StoreReq")
	proto.RegisterType((*StoreResp)(nil), "provider.pb.StoreResp")
	proto.RegisterType((*RetrieveReq)(nil), "provider.pb.RetrieveReq")
	proto.RegisterType((*RetrieveResp)(nil), "provider.pb.RetrieveResp")
	proto.RegisterType((*GetFragmentReq)(nil), "provider.pb.GetFragmentReq")
	proto.RegisterType((*GetFragmentResp)(nil), "provider.pb.GetFragmentResp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ProviderService service

type ProviderServiceClient interface {
	Ping(ctx context.Context, in *PingReq, opts ...grpc.CallOption) (*PingResp, error)
	Store(ctx context.Context, opts ...grpc.CallOption) (ProviderService_StoreClient, error)
	Retrieve(ctx context.Context, in *RetrieveReq, opts ...grpc.CallOption) (ProviderService_RetrieveClient, error)
	GetFragment(ctx context.Context, in *GetFragmentReq, opts ...grpc.CallOption) (*GetFragmentResp, error)
}

type providerServiceClient struct {
	cc *grpc.ClientConn
}

func NewProviderServiceClient(cc *grpc.ClientConn) ProviderServiceClient {
	return &providerServiceClient{cc}
}

func (c *providerServiceClient) Ping(ctx context.Context, in *PingReq, opts ...grpc.CallOption) (*PingResp, error) {
	out := new(PingResp)
	err := grpc.Invoke(ctx, "/provider.pb.ProviderService/Ping", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) Store(ctx context.Context, opts ...grpc.CallOption) (ProviderService_StoreClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_ProviderService_serviceDesc.Streams[0], c.cc, "/provider.pb.ProviderService/Store", opts...)
	if err != nil {
		return nil, err
	}
	x := &providerServiceStoreClient{stream}
	return x, nil
}

type ProviderService_StoreClient interface {
	Send(*StoreReq) error
	CloseAndRecv() (*StoreResp, error)
	grpc.ClientStream
}

type providerServiceStoreClient struct {
	grpc.ClientStream
}

func (x *providerServiceStoreClient) Send(m *StoreReq) error {
	return x.ClientStream.SendMsg(m)
}

func (x *providerServiceStoreClient) CloseAndRecv() (*StoreResp, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(StoreResp)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *providerServiceClient) Retrieve(ctx context.Context, in *RetrieveReq, opts ...grpc.CallOption) (ProviderService_RetrieveClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_ProviderService_serviceDesc.Streams[1], c.cc, "/provider.pb.ProviderService/Retrieve", opts...)
	if err != nil {
		return nil, err
	}
	x := &providerServiceRetrieveClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ProviderService_RetrieveClient interface {
	Recv() (*RetrieveResp, error)
	grpc.ClientStream
}

type providerServiceRetrieveClient struct {
	grpc.ClientStream
}

func (x *providerServiceRetrieveClient) Recv() (*RetrieveResp, error) {
	m := new(RetrieveResp)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *providerServiceClient) GetFragment(ctx context.Context, in *GetFragmentReq, opts ...grpc.CallOption) (*GetFragmentResp, error) {
	out := new(GetFragmentResp)
	err := grpc.Invoke(ctx, "/provider.pb.ProviderService/GetFragment", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ProviderService service

type ProviderServiceServer interface {
	Ping(context.Context, *PingReq) (*PingResp, error)
	Store(ProviderService_StoreServer) error
	Retrieve(*RetrieveReq, ProviderService_RetrieveServer) error
	GetFragment(context.Context, *GetFragmentReq) (*GetFragmentResp, error)
}

func RegisterProviderServiceServer(s *grpc.Server, srv ProviderServiceServer) {
	s.RegisterService(&_ProviderService_serviceDesc, srv)
}

func _ProviderService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/provider.pb.ProviderService/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).Ping(ctx, req.(*PingReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_Store_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ProviderServiceServer).Store(&providerServiceStoreServer{stream})
}

type ProviderService_StoreServer interface {
	SendAndClose(*StoreResp) error
	Recv() (*StoreReq, error)
	grpc.ServerStream
}

type providerServiceStoreServer struct {
	grpc.ServerStream
}

func (x *providerServiceStoreServer) SendAndClose(m *StoreResp) error {
	return x.ServerStream.SendMsg(m)
}

func (x *providerServiceStoreServer) Recv() (*StoreReq, error) {
	m := new(StoreReq)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _ProviderService_Retrieve_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RetrieveReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProviderServiceServer).Retrieve(m, &providerServiceRetrieveServer{stream})
}

type ProviderService_RetrieveServer interface {
	Send(*RetrieveResp) error
	grpc.ServerStream
}

type providerServiceRetrieveServer struct {
	grpc.ServerStream
}

func (x *providerServiceRetrieveServer) Send(m *RetrieveResp) error {
	return x.ServerStream.SendMsg(m)
}

func _ProviderService_GetFragment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFragmentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).GetFragment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/provider.pb.ProviderService/GetFragment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).GetFragment(ctx, req.(*GetFragmentReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProviderService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "provider.pb.ProviderService",
	HandlerType: (*ProviderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _ProviderService_Ping_Handler,
		},
		{
			MethodName: "GetFragment",
			Handler:    _ProviderService_GetFragment_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Store",
			Handler:       _ProviderService_Store_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Retrieve",
			Handler:       _ProviderService_Retrieve_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "provider.proto",
}

func init() { proto.RegisterFile("provider.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 355 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0x4d, 0x6b, 0xe3, 0x30,
	0x10, 0x5d, 0xdb, 0xf9, 0x70, 0x26, 0x21, 0x59, 0x86, 0xdd, 0xe0, 0xf5, 0xe6, 0xd0, 0x0a, 0x02,
	0x39, 0x85, 0xd2, 0xd2, 0x4b, 0xaf, 0x85, 0x96, 0xb6, 0x97, 0xe0, 0x5c, 0x7b, 0x71, 0xec, 0x21,
	0x11, 0xa1, 0xb6, 0x2a, 0x29, 0x81, 0xf6, 0x7f, 0xf4, 0xff, 0x16, 0x29, 0x76, 0x1d, 0x83, 0x7d,
	0x9b, 0x79, 0x7e, 0x7a, 0x6f, 0x66, 0x9e, 0x61, 0x2c, 0x64, 0x7e, 0xe4, 0x29, 0xc9, 0xa5, 0x90,
	0xb9, 0xce, 0x71, 0x58, 0xf5, 0x1b, 0x76, 0x09, 0xfd, 0x15, 0xcf, 0xb6, 0x11, 0xbd, 0xe3, 0x14,
	0x7a, 0x59, 0x9e, 0xd2, 0x53, 0x1a, 0x38, 0x17, 0xce, 0x62, 0x10, 0x15, 0x1d, 0x63, 0xe0, 0x9f,
	0x28, 0x4a, 0xb4, 0x72, 0x5e, 0xc1, 0x5f, 0xeb, 0x5c, 0x92, 0xd1, 0x41, 0xe8, 0xa4, 0xb1, 0x8e,
	0x2d, 0x63, 0x14, 0xd9, 0xda, 0x60, 0xf1, 0x41, 0xef, 0x02, 0xd7, 0xbe, 0xb2, 0xb5, 0xd1, 0xd2,
	0x3c, 0xd9, 0x93, 0x0e, 0xbc, 0x93, 0xd6, 0xa9, 0xc3, 0xdf, 0xe0, 0xed, 0xe9, 0x23, 0xe8, 0x58,
	0xd0, 0x94, 0x6c, 0x0e, 0x83, 0x42, 0x5d, 0x09, 0x0c, 0xa0, 0xaf, 0x0e, 0x49, 0x42, 0x4a, 0x59,
	0x07, 0x3f, 0x2a, 0x5b, 0xf6, 0x02, 0xc3, 0x88, 0xb4, 0xe4, 0x74, 0x2c, 0xe7, 0xb0, 0x9e, 0x4e,
	0xa3, 0xa7, 0xdb, 0xe4, 0xe9, 0x55, 0x9e, 0x0c, 0x46, 0x95, 0x98, 0x12, 0x4d, 0x5b, 0xb1, 0x1d,
	0x8c, 0x1f, 0x49, 0x3f, 0xc8, 0x78, 0xfb, 0x46, 0x99, 0x6e, 0xf3, 0x2c, 0xb4, 0xdd, 0x1f, 0x6d,
	0xc3, 0x52, 0xfc, 0x93, 0xac, 0x5d, 0x37, 0xb2, 0x35, 0xce, 0x60, 0x20, 0x72, 0xc5, 0x35, 0xcf,
	0x33, 0x65, 0x77, 0x1f, 0x45, 0x15, 0xc0, 0xe6, 0x30, 0xa9, 0x39, 0xd5, 0x06, 0xf2, 0xca, 0x81,
	0xae, 0xbf, 0x5c, 0x98, 0xac, 0x8a, 0x74, 0xd7, 0x24, 0x8f, 0x3c, 0x21, 0xbc, 0x85, 0x8e, 0x89,
	0x0f, 0xff, 0x2c, 0xcf, 0x72, 0x5f, 0x16, 0xa1, 0x87, 0x7f, 0x1b, 0x50, 0x25, 0xd8, 0x2f, 0xbc,
	0x83, 0xae, 0xbd, 0x39, 0xd6, 0x19, 0x65, 0xca, 0xe1, 0xb4, 0x09, 0x36, 0x2f, 0x17, 0x0e, 0xde,
	0x83, 0x5f, 0xde, 0x0e, 0x83, 0x1a, 0xef, 0x2c, 0x9f, 0xf0, 0x5f, 0xcb, 0x17, 0x23, 0x72, 0xe5,
	0xe0, 0x33, 0x0c, 0xcf, 0x56, 0xc6, 0xff, 0x35, 0x76, 0xfd, 0xec, 0xe1, 0xac, 0xfd, 0xa3, 0x51,
	0xdb, 0xf4, 0xec, 0x9f, 0x7f, 0xf3, 0x1d, 0x00, 0x00, 0xff, 0xff, 0xdb, 0xc9, 0xec, 0x6a, 0x0b,
	0x03, 0x00, 0x00,
}
