// Code generated by protoc-gen-go. DO NOT EDIT.
// source: client_register.proto

/*
Package register_client_pb is a generated protocol buffer package.

It is generated from these files:
	client_register.proto

It has these top-level messages:
	GetPublicKeyReq
	PublicKeyResp
	RegisterReq
	RegisterResp
	VerifyContactEmailReq
	VerifyContactEmailResp
	GetTrackerServerReq
	GetTrackerServerResp
	TrackerServer
*/
package register_client_pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetPublicKeyReq struct {
	Version uint32 `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
}

func (m *GetPublicKeyReq) Reset()                    { *m = GetPublicKeyReq{} }
func (m *GetPublicKeyReq) String() string            { return proto.CompactTextString(m) }
func (*GetPublicKeyReq) ProtoMessage()               {}
func (*GetPublicKeyReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GetPublicKeyReq) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

type PublicKeyResp struct {
	PublicKey []byte `protobuf:"bytes,1,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
}

func (m *PublicKeyResp) Reset()                    { *m = PublicKeyResp{} }
func (m *PublicKeyResp) String() string            { return proto.CompactTextString(m) }
func (*PublicKeyResp) ProtoMessage()               {}
func (*PublicKeyResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PublicKeyResp) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

type RegisterReq struct {
	Version         uint32 `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	NodeId          []byte `protobuf:"bytes,2,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	PublicKeyEnc    []byte `protobuf:"bytes,3,opt,name=publicKeyEnc,proto3" json:"publicKeyEnc,omitempty"`
	ContactEmailEnc []byte `protobuf:"bytes,4,opt,name=contactEmailEnc,proto3" json:"contactEmailEnc,omitempty"`
}

func (m *RegisterReq) Reset()                    { *m = RegisterReq{} }
func (m *RegisterReq) String() string            { return proto.CompactTextString(m) }
func (*RegisterReq) ProtoMessage()               {}
func (*RegisterReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *RegisterReq) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *RegisterReq) GetNodeId() []byte {
	if m != nil {
		return m.NodeId
	}
	return nil
}

func (m *RegisterReq) GetPublicKeyEnc() []byte {
	if m != nil {
		return m.PublicKeyEnc
	}
	return nil
}

func (m *RegisterReq) GetContactEmailEnc() []byte {
	if m != nil {
		return m.ContactEmailEnc
	}
	return nil
}

type RegisterResp struct {
	Code   uint32 `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	ErrMsg string `protobuf:"bytes,2,opt,name=errMsg" json:"errMsg,omitempty"`
}

func (m *RegisterResp) Reset()                    { *m = RegisterResp{} }
func (m *RegisterResp) String() string            { return proto.CompactTextString(m) }
func (*RegisterResp) ProtoMessage()               {}
func (*RegisterResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *RegisterResp) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *RegisterResp) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

type VerifyContactEmailReq struct {
	Version    uint32 `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	NodeId     []byte `protobuf:"bytes,2,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	VerifyCode string `protobuf:"bytes,3,opt,name=verifyCode" json:"verifyCode,omitempty"`
	Sign       []byte `protobuf:"bytes,4,opt,name=sign,proto3" json:"sign,omitempty"`
}

func (m *VerifyContactEmailReq) Reset()                    { *m = VerifyContactEmailReq{} }
func (m *VerifyContactEmailReq) String() string            { return proto.CompactTextString(m) }
func (*VerifyContactEmailReq) ProtoMessage()               {}
func (*VerifyContactEmailReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *VerifyContactEmailReq) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *VerifyContactEmailReq) GetNodeId() []byte {
	if m != nil {
		return m.NodeId
	}
	return nil
}

func (m *VerifyContactEmailReq) GetVerifyCode() string {
	if m != nil {
		return m.VerifyCode
	}
	return ""
}

func (m *VerifyContactEmailReq) GetSign() []byte {
	if m != nil {
		return m.Sign
	}
	return nil
}

type VerifyContactEmailResp struct {
	Code   uint32 `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	ErrMsg string `protobuf:"bytes,2,opt,name=errMsg" json:"errMsg,omitempty"`
}

func (m *VerifyContactEmailResp) Reset()                    { *m = VerifyContactEmailResp{} }
func (m *VerifyContactEmailResp) String() string            { return proto.CompactTextString(m) }
func (*VerifyContactEmailResp) ProtoMessage()               {}
func (*VerifyContactEmailResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *VerifyContactEmailResp) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *VerifyContactEmailResp) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

type GetTrackerServerReq struct {
	Version   uint32 `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	NodeId    []byte `protobuf:"bytes,2,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	Timestamp uint64 `protobuf:"varint,3,opt,name=timestamp" json:"timestamp,omitempty"`
	Sign      []byte `protobuf:"bytes,4,opt,name=sign,proto3" json:"sign,omitempty"`
}

func (m *GetTrackerServerReq) Reset()                    { *m = GetTrackerServerReq{} }
func (m *GetTrackerServerReq) String() string            { return proto.CompactTextString(m) }
func (*GetTrackerServerReq) ProtoMessage()               {}
func (*GetTrackerServerReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *GetTrackerServerReq) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *GetTrackerServerReq) GetNodeId() []byte {
	if m != nil {
		return m.NodeId
	}
	return nil
}

func (m *GetTrackerServerReq) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *GetTrackerServerReq) GetSign() []byte {
	if m != nil {
		return m.Sign
	}
	return nil
}

type GetTrackerServerResp struct {
	Server []*TrackerServer `protobuf:"bytes,1,rep,name=server" json:"server,omitempty"`
}

func (m *GetTrackerServerResp) Reset()                    { *m = GetTrackerServerResp{} }
func (m *GetTrackerServerResp) String() string            { return proto.CompactTextString(m) }
func (*GetTrackerServerResp) ProtoMessage()               {}
func (*GetTrackerServerResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *GetTrackerServerResp) GetServer() []*TrackerServer {
	if m != nil {
		return m.Server
	}
	return nil
}

type TrackerServer struct {
	Server string `protobuf:"bytes,1,opt,name=server" json:"server,omitempty"`
	Port   uint32 `protobuf:"varint,2,opt,name=port" json:"port,omitempty"`
}

func (m *TrackerServer) Reset()                    { *m = TrackerServer{} }
func (m *TrackerServer) String() string            { return proto.CompactTextString(m) }
func (*TrackerServer) ProtoMessage()               {}
func (*TrackerServer) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *TrackerServer) GetServer() string {
	if m != nil {
		return m.Server
	}
	return ""
}

func (m *TrackerServer) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func init() {
	proto.RegisterType((*GetPublicKeyReq)(nil), "register.client.pb.GetPublicKeyReq")
	proto.RegisterType((*PublicKeyResp)(nil), "register.client.pb.PublicKeyResp")
	proto.RegisterType((*RegisterReq)(nil), "register.client.pb.RegisterReq")
	proto.RegisterType((*RegisterResp)(nil), "register.client.pb.RegisterResp")
	proto.RegisterType((*VerifyContactEmailReq)(nil), "register.client.pb.VerifyContactEmailReq")
	proto.RegisterType((*VerifyContactEmailResp)(nil), "register.client.pb.VerifyContactEmailResp")
	proto.RegisterType((*GetTrackerServerReq)(nil), "register.client.pb.GetTrackerServerReq")
	proto.RegisterType((*GetTrackerServerResp)(nil), "register.client.pb.GetTrackerServerResp")
	proto.RegisterType((*TrackerServer)(nil), "register.client.pb.TrackerServer")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ClientRegisterService service

type ClientRegisterServiceClient interface {
	GetPublicKey(ctx context.Context, in *GetPublicKeyReq, opts ...grpc.CallOption) (*PublicKeyResp, error)
	Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error)
	VerifyContactEmail(ctx context.Context, in *VerifyContactEmailReq, opts ...grpc.CallOption) (*VerifyContactEmailResp, error)
	GetTrackerServer(ctx context.Context, in *GetTrackerServerReq, opts ...grpc.CallOption) (*GetTrackerServerResp, error)
}

type clientRegisterServiceClient struct {
	cc *grpc.ClientConn
}

func NewClientRegisterServiceClient(cc *grpc.ClientConn) ClientRegisterServiceClient {
	return &clientRegisterServiceClient{cc}
}

func (c *clientRegisterServiceClient) GetPublicKey(ctx context.Context, in *GetPublicKeyReq, opts ...grpc.CallOption) (*PublicKeyResp, error) {
	out := new(PublicKeyResp)
	err := grpc.Invoke(ctx, "/register.client.pb.ClientRegisterService/GetPublicKey", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientRegisterServiceClient) Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error) {
	out := new(RegisterResp)
	err := grpc.Invoke(ctx, "/register.client.pb.ClientRegisterService/Register", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientRegisterServiceClient) VerifyContactEmail(ctx context.Context, in *VerifyContactEmailReq, opts ...grpc.CallOption) (*VerifyContactEmailResp, error) {
	out := new(VerifyContactEmailResp)
	err := grpc.Invoke(ctx, "/register.client.pb.ClientRegisterService/VerifyContactEmail", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientRegisterServiceClient) GetTrackerServer(ctx context.Context, in *GetTrackerServerReq, opts ...grpc.CallOption) (*GetTrackerServerResp, error) {
	out := new(GetTrackerServerResp)
	err := grpc.Invoke(ctx, "/register.client.pb.ClientRegisterService/GetTrackerServer", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ClientRegisterService service

type ClientRegisterServiceServer interface {
	GetPublicKey(context.Context, *GetPublicKeyReq) (*PublicKeyResp, error)
	Register(context.Context, *RegisterReq) (*RegisterResp, error)
	VerifyContactEmail(context.Context, *VerifyContactEmailReq) (*VerifyContactEmailResp, error)
	GetTrackerServer(context.Context, *GetTrackerServerReq) (*GetTrackerServerResp, error)
}

func RegisterClientRegisterServiceServer(s *grpc.Server, srv ClientRegisterServiceServer) {
	s.RegisterService(&_ClientRegisterService_serviceDesc, srv)
}

func _ClientRegisterService_GetPublicKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPublicKeyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientRegisterServiceServer).GetPublicKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/register.client.pb.ClientRegisterService/GetPublicKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientRegisterServiceServer).GetPublicKey(ctx, req.(*GetPublicKeyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientRegisterService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientRegisterServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/register.client.pb.ClientRegisterService/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientRegisterServiceServer).Register(ctx, req.(*RegisterReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientRegisterService_VerifyContactEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyContactEmailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientRegisterServiceServer).VerifyContactEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/register.client.pb.ClientRegisterService/VerifyContactEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientRegisterServiceServer).VerifyContactEmail(ctx, req.(*VerifyContactEmailReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientRegisterService_GetTrackerServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTrackerServerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientRegisterServiceServer).GetTrackerServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/register.client.pb.ClientRegisterService/GetTrackerServer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientRegisterServiceServer).GetTrackerServer(ctx, req.(*GetTrackerServerReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _ClientRegisterService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "register.client.pb.ClientRegisterService",
	HandlerType: (*ClientRegisterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPublicKey",
			Handler:    _ClientRegisterService_GetPublicKey_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _ClientRegisterService_Register_Handler,
		},
		{
			MethodName: "VerifyContactEmail",
			Handler:    _ClientRegisterService_VerifyContactEmail_Handler,
		},
		{
			MethodName: "GetTrackerServer",
			Handler:    _ClientRegisterService_GetTrackerServer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "client_register.proto",
}

func init() { proto.RegisterFile("client_register.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 440 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0x26, 0x24, 0x0a, 0x64, 0x9a, 0xa8, 0x68, 0x20, 0x95, 0x15, 0x55, 0x10, 0x96, 0x03, 0x01,
	0x44, 0x0e, 0xe5, 0x04, 0x1c, 0x4b, 0x55, 0x21, 0x84, 0x80, 0x05, 0x21, 0x6e, 0xc8, 0x59, 0x0f,
	0xd6, 0x8a, 0xd8, 0x5e, 0x76, 0x97, 0x48, 0x39, 0xf0, 0x08, 0xbc, 0x00, 0x4f, 0x8b, 0x3c, 0xb5,
	0x13, 0xdb, 0x31, 0x55, 0xc9, 0x6d, 0x67, 0x76, 0xe6, 0xfb, 0xf1, 0xce, 0x18, 0xc6, 0x6a, 0xa9,
	0x29, 0xf5, 0x5f, 0x2d, 0xc5, 0xda, 0x79, 0xb2, 0x73, 0x63, 0x33, 0x9f, 0x21, 0x6e, 0xe2, 0x8b,
	0xfb, 0xb9, 0x59, 0x88, 0x27, 0x70, 0x78, 0x4e, 0xfe, 0xfd, 0xcf, 0xc5, 0x52, 0xab, 0x37, 0xb4,
	0x96, 0xf4, 0x03, 0x03, 0xb8, 0xb1, 0x22, 0xeb, 0x74, 0x96, 0x06, 0x9d, 0x69, 0x67, 0x36, 0x92,
	0x65, 0x28, 0x9e, 0xc2, 0xa8, 0x52, 0xe9, 0x0c, 0x1e, 0xc3, 0xc0, 0x94, 0x09, 0x2e, 0x1e, 0xca,
	0x6d, 0x42, 0xfc, 0xee, 0xc0, 0x81, 0x2c, 0x28, 0x2f, 0x05, 0xc6, 0x23, 0xe8, 0xa7, 0x59, 0x44,
	0xaf, 0xa3, 0xe0, 0x3a, 0x83, 0x14, 0x11, 0x0a, 0x18, 0x6e, 0xe0, 0xce, 0x52, 0x15, 0x74, 0xf9,
	0xb6, 0x96, 0xc3, 0x19, 0x1c, 0xaa, 0x2c, 0xf5, 0xa1, 0xf2, 0x67, 0x49, 0xa8, 0x97, 0x79, 0x59,
	0x8f, 0xcb, 0x9a, 0x69, 0xf1, 0x02, 0x86, 0x5b, 0x39, 0xce, 0x20, 0x42, 0x4f, 0x65, 0x11, 0x15,
	0x62, 0xf8, 0x9c, 0x2b, 0x21, 0x6b, 0xdf, 0xba, 0x98, 0x95, 0x0c, 0x64, 0x11, 0x89, 0x5f, 0x30,
	0xfe, 0x4c, 0x56, 0x7f, 0x5b, 0x9f, 0x56, 0x40, 0xf7, 0x33, 0x75, 0x17, 0x60, 0x55, 0x40, 0x45,
	0xc4, 0x96, 0x06, 0xb2, 0x92, 0xc9, 0x65, 0x39, 0x1d, 0xa7, 0x85, 0x0b, 0x3e, 0x8b, 0x57, 0x70,
	0xd4, 0x46, 0xff, 0x9f, 0x26, 0xd6, 0x70, 0xfb, 0x9c, 0xfc, 0x27, 0x1b, 0xaa, 0xef, 0x64, 0x3f,
	0x92, 0x5d, 0xed, 0xfb, 0x2e, 0xc7, 0x30, 0xf0, 0x3a, 0x21, 0xe7, 0xc3, 0xc4, 0xb0, 0x83, 0x9e,
	0xdc, 0x26, 0x5a, 0x0d, 0x7c, 0x80, 0x3b, 0xbb, 0xd4, 0xce, 0xe0, 0x73, 0xe8, 0x3b, 0x8e, 0x82,
	0xce, 0xb4, 0x3b, 0x3b, 0x38, 0xb9, 0x3f, 0xdf, 0x1d, 0xd2, 0x79, 0xbd, 0xad, 0x68, 0x10, 0x2f,
	0x61, 0x54, 0xbb, 0xc8, 0xd5, 0x6e, 0xb0, 0xd8, 0xf6, 0x45, 0x94, 0xeb, 0x31, 0x99, 0xf5, 0xec,
	0x61, 0x24, 0xf9, 0x7c, 0xf2, 0xa7, 0x0b, 0xe3, 0x53, 0x26, 0x28, 0x47, 0x22, 0x07, 0xd1, 0x8a,
	0xf0, 0x0b, 0x0c, 0xab, 0x1b, 0x81, 0x0f, 0xda, 0x14, 0x35, 0x76, 0x66, 0xd2, 0x2a, 0xbb, 0xb6,
	0x2b, 0xe2, 0x1a, 0xbe, 0x83, 0x9b, 0x25, 0x19, 0xde, 0x6b, 0x6b, 0xa8, 0x2c, 0xcb, 0x64, 0x7a,
	0x79, 0x01, 0x03, 0x26, 0x80, 0xbb, 0x53, 0x81, 0x8f, 0xda, 0x3a, 0x5b, 0x87, 0x77, 0xf2, 0xf8,
	0xaa, 0xa5, 0x4c, 0x17, 0xc3, 0xad, 0xe6, 0x1b, 0xe2, 0xc3, 0x7f, 0x7c, 0x9d, 0xe6, 0x90, 0x4d,
	0x66, 0x57, 0x2b, 0xcc, 0x89, 0x16, 0x7d, 0xfe, 0x5f, 0x3d, 0xfb, 0x1b, 0x00, 0x00, 0xff, 0xff,
	0x8b, 0xe0, 0x73, 0xfd, 0xc8, 0x04, 0x00, 0x00,
}
