// Code generated by protoc-gen-go. DO NOT EDIT.
// source: provider_register.proto

/*
Package register_provider_pb is a generated protocol buffer package.

It is generated from these files:
	provider_register.proto

It has these top-level messages:
	GetPublicKeyReq
	GetPublicKeyResp
	RegisterReq
	RegisterResp
	VerifyBillEmailReq
	VerifyBillEmailResp
	ResendVerifyCodeReq
	ResendVerifyCodeResp
	AddExtraStorageReq
	AddExtraStorageResp
	GetTrackerServerReq
	GetTrackerServerResp
	TrackerServer
	GetCollectorServerReq
	GetCollectorServerResp
	CollectorServer
	RefreshIpReq
	RefreshIpResp
	SwitchPrivateReq
	SwitchPrivateResp
	SwitchPublicReq
	SwitchPublicResp
*/
package register_provider_pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetPublicKeyReq struct {
	Version uint32 `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
}

func (m *GetPublicKeyReq) Reset()                    { *m = GetPublicKeyReq{} }
func (m *GetPublicKeyReq) String() string            { return proto.CompactTextString(m) }
func (*GetPublicKeyReq) ProtoMessage()               {}
func (*GetPublicKeyReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GetPublicKeyReq) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

type GetPublicKeyResp struct {
	PublicKey     []byte `protobuf:"bytes,1,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	PublicKeyHash []byte `protobuf:"bytes,2,opt,name=publicKeyHash,proto3" json:"publicKeyHash,omitempty"`
	Ip            string `protobuf:"bytes,3,opt,name=ip" json:"ip,omitempty"`
}

func (m *GetPublicKeyResp) Reset()                    { *m = GetPublicKeyResp{} }
func (m *GetPublicKeyResp) String() string            { return proto.CompactTextString(m) }
func (*GetPublicKeyResp) ProtoMessage()               {}
func (*GetPublicKeyResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetPublicKeyResp) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *GetPublicKeyResp) GetPublicKeyHash() []byte {
	if m != nil {
		return m.PublicKeyHash
	}
	return nil
}

func (m *GetPublicKeyResp) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

type RegisterReq struct {
	Version            uint32   `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	Timestamp          uint64   `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
	NodeIdEnc          []byte   `protobuf:"bytes,3,opt,name=nodeIdEnc,proto3" json:"nodeIdEnc,omitempty"`
	PublicKeyEnc       []byte   `protobuf:"bytes,4,opt,name=publicKeyEnc,proto3" json:"publicKeyEnc,omitempty"`
	EncryptKeyEnc      []byte   `protobuf:"bytes,5,opt,name=encryptKeyEnc,proto3" json:"encryptKeyEnc,omitempty"`
	WalletAddressEnc   []byte   `protobuf:"bytes,6,opt,name=walletAddressEnc,proto3" json:"walletAddressEnc,omitempty"`
	BillEmailEnc       []byte   `protobuf:"bytes,7,opt,name=billEmailEnc,proto3" json:"billEmailEnc,omitempty"`
	MainStorageVolume  uint64   `protobuf:"varint,8,opt,name=mainStorageVolume" json:"mainStorageVolume,omitempty"`
	UpBandwidth        uint64   `protobuf:"varint,9,opt,name=upBandwidth" json:"upBandwidth,omitempty"`
	DownBandwidth      uint64   `protobuf:"varint,10,opt,name=downBandwidth" json:"downBandwidth,omitempty"`
	TestUpBandwidth    uint64   `protobuf:"varint,11,opt,name=testUpBandwidth" json:"testUpBandwidth,omitempty"`
	TestDownBandwidth  uint64   `protobuf:"varint,12,opt,name=testDownBandwidth" json:"testDownBandwidth,omitempty"`
	Availability       float64  `protobuf:"fixed64,13,opt,name=availability" json:"availability,omitempty"`
	Port               uint32   `protobuf:"varint,14,opt,name=port" json:"port,omitempty"`
	HostEnc            []byte   `protobuf:"bytes,15,opt,name=hostEnc,proto3" json:"hostEnc,omitempty"`
	DynamicDomainEnc   []byte   `protobuf:"bytes,16,opt,name=dynamicDomainEnc,proto3" json:"dynamicDomainEnc,omitempty"`
	ExtraStorageVolume []uint64 `protobuf:"varint,17,rep,packed,name=extraStorageVolume" json:"extraStorageVolume,omitempty"`
	PublicKeyHash      []byte   `protobuf:"bytes,18,opt,name=publicKeyHash,proto3" json:"publicKeyHash,omitempty"`
	Sign               []byte   `protobuf:"bytes,19,opt,name=sign,proto3" json:"sign,omitempty"`
	ConfirmInner       bool     `protobuf:"varint,20,opt,name=confirmInner" json:"confirmInner,omitempty"`
}

func (m *RegisterReq) Reset()                    { *m = RegisterReq{} }
func (m *RegisterReq) String() string            { return proto.CompactTextString(m) }
func (*RegisterReq) ProtoMessage()               {}
func (*RegisterReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *RegisterReq) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *RegisterReq) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *RegisterReq) GetNodeIdEnc() []byte {
	if m != nil {
		return m.NodeIdEnc
	}
	return nil
}

func (m *RegisterReq) GetPublicKeyEnc() []byte {
	if m != nil {
		return m.PublicKeyEnc
	}
	return nil
}

func (m *RegisterReq) GetEncryptKeyEnc() []byte {
	if m != nil {
		return m.EncryptKeyEnc
	}
	return nil
}

func (m *RegisterReq) GetWalletAddressEnc() []byte {
	if m != nil {
		return m.WalletAddressEnc
	}
	return nil
}

func (m *RegisterReq) GetBillEmailEnc() []byte {
	if m != nil {
		return m.BillEmailEnc
	}
	return nil
}

func (m *RegisterReq) GetMainStorageVolume() uint64 {
	if m != nil {
		return m.MainStorageVolume
	}
	return 0
}

func (m *RegisterReq) GetUpBandwidth() uint64 {
	if m != nil {
		return m.UpBandwidth
	}
	return 0
}

func (m *RegisterReq) GetDownBandwidth() uint64 {
	if m != nil {
		return m.DownBandwidth
	}
	return 0
}

func (m *RegisterReq) GetTestUpBandwidth() uint64 {
	if m != nil {
		return m.TestUpBandwidth
	}
	return 0
}

func (m *RegisterReq) GetTestDownBandwidth() uint64 {
	if m != nil {
		return m.TestDownBandwidth
	}
	return 0
}

func (m *RegisterReq) GetAvailability() float64 {
	if m != nil {
		return m.Availability
	}
	return 0
}

func (m *RegisterReq) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *RegisterReq) GetHostEnc() []byte {
	if m != nil {
		return m.HostEnc
	}
	return nil
}

func (m *RegisterReq) GetDynamicDomainEnc() []byte {
	if m != nil {
		return m.DynamicDomainEnc
	}
	return nil
}

func (m *RegisterReq) GetExtraStorageVolume() []uint64 {
	if m != nil {
		return m.ExtraStorageVolume
	}
	return nil
}

func (m *RegisterReq) GetPublicKeyHash() []byte {
	if m != nil {
		return m.PublicKeyHash
	}
	return nil
}

func (m *RegisterReq) GetSign() []byte {
	if m != nil {
		return m.Sign
	}
	return nil
}

func (m *RegisterReq) GetConfirmInner() bool {
	if m != nil {
		return m.ConfirmInner
	}
	return false
}

type RegisterResp struct {
	Code   uint32 `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	ErrMsg string `protobuf:"bytes,2,opt,name=errMsg" json:"errMsg,omitempty"`
}

func (m *RegisterResp) Reset()                    { *m = RegisterResp{} }
func (m *RegisterResp) String() string            { return proto.CompactTextString(m) }
func (*RegisterResp) ProtoMessage()               {}
func (*RegisterResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *RegisterResp) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *RegisterResp) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

type VerifyBillEmailReq struct {
	Version    uint32 `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	NodeId     []byte `protobuf:"bytes,2,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	Timestamp  uint64 `protobuf:"varint,3,opt,name=timestamp" json:"timestamp,omitempty"`
	VerifyCode string `protobuf:"bytes,4,opt,name=verifyCode" json:"verifyCode,omitempty"`
	Sign       []byte `protobuf:"bytes,5,opt,name=sign,proto3" json:"sign,omitempty"`
}

func (m *VerifyBillEmailReq) Reset()                    { *m = VerifyBillEmailReq{} }
func (m *VerifyBillEmailReq) String() string            { return proto.CompactTextString(m) }
func (*VerifyBillEmailReq) ProtoMessage()               {}
func (*VerifyBillEmailReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *VerifyBillEmailReq) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *VerifyBillEmailReq) GetNodeId() []byte {
	if m != nil {
		return m.NodeId
	}
	return nil
}

func (m *VerifyBillEmailReq) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *VerifyBillEmailReq) GetVerifyCode() string {
	if m != nil {
		return m.VerifyCode
	}
	return ""
}

func (m *VerifyBillEmailReq) GetSign() []byte {
	if m != nil {
		return m.Sign
	}
	return nil
}

type VerifyBillEmailResp struct {
	Code   uint32 `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	ErrMsg string `protobuf:"bytes,2,opt,name=errMsg" json:"errMsg,omitempty"`
}

func (m *VerifyBillEmailResp) Reset()                    { *m = VerifyBillEmailResp{} }
func (m *VerifyBillEmailResp) String() string            { return proto.CompactTextString(m) }
func (*VerifyBillEmailResp) ProtoMessage()               {}
func (*VerifyBillEmailResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *VerifyBillEmailResp) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *VerifyBillEmailResp) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

type ResendVerifyCodeReq struct {
	Version   uint32 `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	NodeId    []byte `protobuf:"bytes,2,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	Timestamp uint64 `protobuf:"varint,3,opt,name=timestamp" json:"timestamp,omitempty"`
	Sign      []byte `protobuf:"bytes,4,opt,name=sign,proto3" json:"sign,omitempty"`
}

func (m *ResendVerifyCodeReq) Reset()                    { *m = ResendVerifyCodeReq{} }
func (m *ResendVerifyCodeReq) String() string            { return proto.CompactTextString(m) }
func (*ResendVerifyCodeReq) ProtoMessage()               {}
func (*ResendVerifyCodeReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ResendVerifyCodeReq) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *ResendVerifyCodeReq) GetNodeId() []byte {
	if m != nil {
		return m.NodeId
	}
	return nil
}

func (m *ResendVerifyCodeReq) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *ResendVerifyCodeReq) GetSign() []byte {
	if m != nil {
		return m.Sign
	}
	return nil
}

type ResendVerifyCodeResp struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (m *ResendVerifyCodeResp) Reset()                    { *m = ResendVerifyCodeResp{} }
func (m *ResendVerifyCodeResp) String() string            { return proto.CompactTextString(m) }
func (*ResendVerifyCodeResp) ProtoMessage()               {}
func (*ResendVerifyCodeResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *ResendVerifyCodeResp) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type AddExtraStorageReq struct {
	Version   uint32 `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	NodeId    []byte `protobuf:"bytes,2,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	Timestamp uint64 `protobuf:"varint,3,opt,name=timestamp" json:"timestamp,omitempty"`
	Volume    uint64 `protobuf:"varint,4,opt,name=volume" json:"volume,omitempty"`
	Sign      []byte `protobuf:"bytes,5,opt,name=sign,proto3" json:"sign,omitempty"`
}

func (m *AddExtraStorageReq) Reset()                    { *m = AddExtraStorageReq{} }
func (m *AddExtraStorageReq) String() string            { return proto.CompactTextString(m) }
func (*AddExtraStorageReq) ProtoMessage()               {}
func (*AddExtraStorageReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *AddExtraStorageReq) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *AddExtraStorageReq) GetNodeId() []byte {
	if m != nil {
		return m.NodeId
	}
	return nil
}

func (m *AddExtraStorageReq) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *AddExtraStorageReq) GetVolume() uint64 {
	if m != nil {
		return m.Volume
	}
	return 0
}

func (m *AddExtraStorageReq) GetSign() []byte {
	if m != nil {
		return m.Sign
	}
	return nil
}

type AddExtraStorageResp struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (m *AddExtraStorageResp) Reset()                    { *m = AddExtraStorageResp{} }
func (m *AddExtraStorageResp) String() string            { return proto.CompactTextString(m) }
func (*AddExtraStorageResp) ProtoMessage()               {}
func (*AddExtraStorageResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *AddExtraStorageResp) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type GetTrackerServerReq struct {
	Version   uint32 `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	NodeId    []byte `protobuf:"bytes,2,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	Timestamp uint64 `protobuf:"varint,3,opt,name=timestamp" json:"timestamp,omitempty"`
	Sign      []byte `protobuf:"bytes,4,opt,name=sign,proto3" json:"sign,omitempty"`
}

func (m *GetTrackerServerReq) Reset()                    { *m = GetTrackerServerReq{} }
func (m *GetTrackerServerReq) String() string            { return proto.CompactTextString(m) }
func (*GetTrackerServerReq) ProtoMessage()               {}
func (*GetTrackerServerReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *GetTrackerServerReq) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *GetTrackerServerReq) GetNodeId() []byte {
	if m != nil {
		return m.NodeId
	}
	return nil
}

func (m *GetTrackerServerReq) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *GetTrackerServerReq) GetSign() []byte {
	if m != nil {
		return m.Sign
	}
	return nil
}

type GetTrackerServerResp struct {
	Server []*TrackerServer `protobuf:"bytes,1,rep,name=server" json:"server,omitempty"`
}

func (m *GetTrackerServerResp) Reset()                    { *m = GetTrackerServerResp{} }
func (m *GetTrackerServerResp) String() string            { return proto.CompactTextString(m) }
func (*GetTrackerServerResp) ProtoMessage()               {}
func (*GetTrackerServerResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *GetTrackerServerResp) GetServer() []*TrackerServer {
	if m != nil {
		return m.Server
	}
	return nil
}

type TrackerServer struct {
	Server string `protobuf:"bytes,1,opt,name=server" json:"server,omitempty"`
	Port   uint32 `protobuf:"varint,2,opt,name=port" json:"port,omitempty"`
}

func (m *TrackerServer) Reset()                    { *m = TrackerServer{} }
func (m *TrackerServer) String() string            { return proto.CompactTextString(m) }
func (*TrackerServer) ProtoMessage()               {}
func (*TrackerServer) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *TrackerServer) GetServer() string {
	if m != nil {
		return m.Server
	}
	return ""
}

func (m *TrackerServer) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type GetCollectorServerReq struct {
	Version   uint32 `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	NodeId    []byte `protobuf:"bytes,2,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	Timestamp uint64 `protobuf:"varint,3,opt,name=timestamp" json:"timestamp,omitempty"`
	Sign      []byte `protobuf:"bytes,4,opt,name=sign,proto3" json:"sign,omitempty"`
}

func (m *GetCollectorServerReq) Reset()                    { *m = GetCollectorServerReq{} }
func (m *GetCollectorServerReq) String() string            { return proto.CompactTextString(m) }
func (*GetCollectorServerReq) ProtoMessage()               {}
func (*GetCollectorServerReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *GetCollectorServerReq) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *GetCollectorServerReq) GetNodeId() []byte {
	if m != nil {
		return m.NodeId
	}
	return nil
}

func (m *GetCollectorServerReq) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *GetCollectorServerReq) GetSign() []byte {
	if m != nil {
		return m.Sign
	}
	return nil
}

type GetCollectorServerResp struct {
	Server []*CollectorServer `protobuf:"bytes,1,rep,name=server" json:"server,omitempty"`
}

func (m *GetCollectorServerResp) Reset()                    { *m = GetCollectorServerResp{} }
func (m *GetCollectorServerResp) String() string            { return proto.CompactTextString(m) }
func (*GetCollectorServerResp) ProtoMessage()               {}
func (*GetCollectorServerResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *GetCollectorServerResp) GetServer() []*CollectorServer {
	if m != nil {
		return m.Server
	}
	return nil
}

type CollectorServer struct {
	Server string `protobuf:"bytes,1,opt,name=server" json:"server,omitempty"`
	Port   uint32 `protobuf:"varint,2,opt,name=port" json:"port,omitempty"`
}

func (m *CollectorServer) Reset()                    { *m = CollectorServer{} }
func (m *CollectorServer) String() string            { return proto.CompactTextString(m) }
func (*CollectorServer) ProtoMessage()               {}
func (*CollectorServer) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *CollectorServer) GetServer() string {
	if m != nil {
		return m.Server
	}
	return ""
}

func (m *CollectorServer) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type RefreshIpReq struct {
	Version   uint32 `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	NodeId    []byte `protobuf:"bytes,2,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	Timestamp uint64 `protobuf:"varint,3,opt,name=timestamp" json:"timestamp,omitempty"`
	Port      uint32 `protobuf:"varint,4,opt,name=port" json:"port,omitempty"`
	Sign      []byte `protobuf:"bytes,5,opt,name=sign,proto3" json:"sign,omitempty"`
}

func (m *RefreshIpReq) Reset()                    { *m = RefreshIpReq{} }
func (m *RefreshIpReq) String() string            { return proto.CompactTextString(m) }
func (*RefreshIpReq) ProtoMessage()               {}
func (*RefreshIpReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *RefreshIpReq) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *RefreshIpReq) GetNodeId() []byte {
	if m != nil {
		return m.NodeId
	}
	return nil
}

func (m *RefreshIpReq) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *RefreshIpReq) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *RefreshIpReq) GetSign() []byte {
	if m != nil {
		return m.Sign
	}
	return nil
}

type RefreshIpResp struct {
	Ip string `protobuf:"bytes,1,opt,name=ip" json:"ip,omitempty"`
}

func (m *RefreshIpResp) Reset()                    { *m = RefreshIpResp{} }
func (m *RefreshIpResp) String() string            { return proto.CompactTextString(m) }
func (*RefreshIpResp) ProtoMessage()               {}
func (*RefreshIpResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *RefreshIpResp) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

type SwitchPrivateReq struct {
	Version   uint32 `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	NodeId    []byte `protobuf:"bytes,2,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	Timestamp uint64 `protobuf:"varint,3,opt,name=timestamp" json:"timestamp,omitempty"`
	Sign      []byte `protobuf:"bytes,4,opt,name=sign,proto3" json:"sign,omitempty"`
}

func (m *SwitchPrivateReq) Reset()                    { *m = SwitchPrivateReq{} }
func (m *SwitchPrivateReq) String() string            { return proto.CompactTextString(m) }
func (*SwitchPrivateReq) ProtoMessage()               {}
func (*SwitchPrivateReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *SwitchPrivateReq) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *SwitchPrivateReq) GetNodeId() []byte {
	if m != nil {
		return m.NodeId
	}
	return nil
}

func (m *SwitchPrivateReq) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *SwitchPrivateReq) GetSign() []byte {
	if m != nil {
		return m.Sign
	}
	return nil
}

type SwitchPrivateResp struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (m *SwitchPrivateResp) Reset()                    { *m = SwitchPrivateResp{} }
func (m *SwitchPrivateResp) String() string            { return proto.CompactTextString(m) }
func (*SwitchPrivateResp) ProtoMessage()               {}
func (*SwitchPrivateResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *SwitchPrivateResp) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type SwitchPublicReq struct {
	Version          uint32 `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	NodeId           []byte `protobuf:"bytes,2,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	Timestamp        uint64 `protobuf:"varint,3,opt,name=timestamp" json:"timestamp,omitempty"`
	Sign             []byte `protobuf:"bytes,4,opt,name=sign,proto3" json:"sign,omitempty"`
	PublicKeyHash    []byte `protobuf:"bytes,5,opt,name=publicKeyHash,proto3" json:"publicKeyHash,omitempty"`
	Port             uint32 `protobuf:"varint,6,opt,name=port" json:"port,omitempty"`
	HostEnc          []byte `protobuf:"bytes,7,opt,name=hostEnc,proto3" json:"hostEnc,omitempty"`
	DynamicDomainEnc []byte `protobuf:"bytes,8,opt,name=dynamicDomainEnc,proto3" json:"dynamicDomainEnc,omitempty"`
}

func (m *SwitchPublicReq) Reset()                    { *m = SwitchPublicReq{} }
func (m *SwitchPublicReq) String() string            { return proto.CompactTextString(m) }
func (*SwitchPublicReq) ProtoMessage()               {}
func (*SwitchPublicReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *SwitchPublicReq) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *SwitchPublicReq) GetNodeId() []byte {
	if m != nil {
		return m.NodeId
	}
	return nil
}

func (m *SwitchPublicReq) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *SwitchPublicReq) GetSign() []byte {
	if m != nil {
		return m.Sign
	}
	return nil
}

func (m *SwitchPublicReq) GetPublicKeyHash() []byte {
	if m != nil {
		return m.PublicKeyHash
	}
	return nil
}

func (m *SwitchPublicReq) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *SwitchPublicReq) GetHostEnc() []byte {
	if m != nil {
		return m.HostEnc
	}
	return nil
}

func (m *SwitchPublicReq) GetDynamicDomainEnc() []byte {
	if m != nil {
		return m.DynamicDomainEnc
	}
	return nil
}

type SwitchPublicResp struct {
	Code   uint32 `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	ErrMsg string `protobuf:"bytes,2,opt,name=errMsg" json:"errMsg,omitempty"`
}

func (m *SwitchPublicResp) Reset()                    { *m = SwitchPublicResp{} }
func (m *SwitchPublicResp) String() string            { return proto.CompactTextString(m) }
func (*SwitchPublicResp) ProtoMessage()               {}
func (*SwitchPublicResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *SwitchPublicResp) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *SwitchPublicResp) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func init() {
	proto.RegisterType((*GetPublicKeyReq)(nil), "register_provider_pb.GetPublicKeyReq")
	proto.RegisterType((*GetPublicKeyResp)(nil), "register_provider_pb.GetPublicKeyResp")
	proto.RegisterType((*RegisterReq)(nil), "register_provider_pb.RegisterReq")
	proto.RegisterType((*RegisterResp)(nil), "register_provider_pb.RegisterResp")
	proto.RegisterType((*VerifyBillEmailReq)(nil), "register_provider_pb.VerifyBillEmailReq")
	proto.RegisterType((*VerifyBillEmailResp)(nil), "register_provider_pb.VerifyBillEmailResp")
	proto.RegisterType((*ResendVerifyCodeReq)(nil), "register_provider_pb.ResendVerifyCodeReq")
	proto.RegisterType((*ResendVerifyCodeResp)(nil), "register_provider_pb.ResendVerifyCodeResp")
	proto.RegisterType((*AddExtraStorageReq)(nil), "register_provider_pb.AddExtraStorageReq")
	proto.RegisterType((*AddExtraStorageResp)(nil), "register_provider_pb.AddExtraStorageResp")
	proto.RegisterType((*GetTrackerServerReq)(nil), "register_provider_pb.GetTrackerServerReq")
	proto.RegisterType((*GetTrackerServerResp)(nil), "register_provider_pb.GetTrackerServerResp")
	proto.RegisterType((*TrackerServer)(nil), "register_provider_pb.TrackerServer")
	proto.RegisterType((*GetCollectorServerReq)(nil), "register_provider_pb.GetCollectorServerReq")
	proto.RegisterType((*GetCollectorServerResp)(nil), "register_provider_pb.GetCollectorServerResp")
	proto.RegisterType((*CollectorServer)(nil), "register_provider_pb.CollectorServer")
	proto.RegisterType((*RefreshIpReq)(nil), "register_provider_pb.RefreshIpReq")
	proto.RegisterType((*RefreshIpResp)(nil), "register_provider_pb.RefreshIpResp")
	proto.RegisterType((*SwitchPrivateReq)(nil), "register_provider_pb.SwitchPrivateReq")
	proto.RegisterType((*SwitchPrivateResp)(nil), "register_provider_pb.SwitchPrivateResp")
	proto.RegisterType((*SwitchPublicReq)(nil), "register_provider_pb.SwitchPublicReq")
	proto.RegisterType((*SwitchPublicResp)(nil), "register_provider_pb.SwitchPublicResp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ProviderRegisterService service

type ProviderRegisterServiceClient interface {
	GetPublicKey(ctx context.Context, in *GetPublicKeyReq, opts ...grpc.CallOption) (*GetPublicKeyResp, error)
	Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error)
	VerifyBillEmail(ctx context.Context, in *VerifyBillEmailReq, opts ...grpc.CallOption) (*VerifyBillEmailResp, error)
	ResendVerifyCode(ctx context.Context, in *ResendVerifyCodeReq, opts ...grpc.CallOption) (*ResendVerifyCodeResp, error)
	AddExtraStorage(ctx context.Context, in *AddExtraStorageReq, opts ...grpc.CallOption) (*AddExtraStorageResp, error)
	GetTrackerServer(ctx context.Context, in *GetTrackerServerReq, opts ...grpc.CallOption) (*GetTrackerServerResp, error)
	GetCollectorServer(ctx context.Context, in *GetCollectorServerReq, opts ...grpc.CallOption) (*GetCollectorServerResp, error)
	RefreshIp(ctx context.Context, in *RefreshIpReq, opts ...grpc.CallOption) (*RefreshIpResp, error)
	SwitchPrivate(ctx context.Context, in *SwitchPrivateReq, opts ...grpc.CallOption) (*SwitchPrivateResp, error)
	SwitchPublic(ctx context.Context, in *SwitchPublicReq, opts ...grpc.CallOption) (*SwitchPublicResp, error)
}

type providerRegisterServiceClient struct {
	cc *grpc.ClientConn
}

func NewProviderRegisterServiceClient(cc *grpc.ClientConn) ProviderRegisterServiceClient {
	return &providerRegisterServiceClient{cc}
}

func (c *providerRegisterServiceClient) GetPublicKey(ctx context.Context, in *GetPublicKeyReq, opts ...grpc.CallOption) (*GetPublicKeyResp, error) {
	out := new(GetPublicKeyResp)
	err := grpc.Invoke(ctx, "/register_provider_pb.ProviderRegisterService/GetPublicKey", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerRegisterServiceClient) Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error) {
	out := new(RegisterResp)
	err := grpc.Invoke(ctx, "/register_provider_pb.ProviderRegisterService/Register", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerRegisterServiceClient) VerifyBillEmail(ctx context.Context, in *VerifyBillEmailReq, opts ...grpc.CallOption) (*VerifyBillEmailResp, error) {
	out := new(VerifyBillEmailResp)
	err := grpc.Invoke(ctx, "/register_provider_pb.ProviderRegisterService/VerifyBillEmail", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerRegisterServiceClient) ResendVerifyCode(ctx context.Context, in *ResendVerifyCodeReq, opts ...grpc.CallOption) (*ResendVerifyCodeResp, error) {
	out := new(ResendVerifyCodeResp)
	err := grpc.Invoke(ctx, "/register_provider_pb.ProviderRegisterService/ResendVerifyCode", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerRegisterServiceClient) AddExtraStorage(ctx context.Context, in *AddExtraStorageReq, opts ...grpc.CallOption) (*AddExtraStorageResp, error) {
	out := new(AddExtraStorageResp)
	err := grpc.Invoke(ctx, "/register_provider_pb.ProviderRegisterService/AddExtraStorage", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerRegisterServiceClient) GetTrackerServer(ctx context.Context, in *GetTrackerServerReq, opts ...grpc.CallOption) (*GetTrackerServerResp, error) {
	out := new(GetTrackerServerResp)
	err := grpc.Invoke(ctx, "/register_provider_pb.ProviderRegisterService/GetTrackerServer", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerRegisterServiceClient) GetCollectorServer(ctx context.Context, in *GetCollectorServerReq, opts ...grpc.CallOption) (*GetCollectorServerResp, error) {
	out := new(GetCollectorServerResp)
	err := grpc.Invoke(ctx, "/register_provider_pb.ProviderRegisterService/GetCollectorServer", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerRegisterServiceClient) RefreshIp(ctx context.Context, in *RefreshIpReq, opts ...grpc.CallOption) (*RefreshIpResp, error) {
	out := new(RefreshIpResp)
	err := grpc.Invoke(ctx, "/register_provider_pb.ProviderRegisterService/RefreshIp", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerRegisterServiceClient) SwitchPrivate(ctx context.Context, in *SwitchPrivateReq, opts ...grpc.CallOption) (*SwitchPrivateResp, error) {
	out := new(SwitchPrivateResp)
	err := grpc.Invoke(ctx, "/register_provider_pb.ProviderRegisterService/SwitchPrivate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerRegisterServiceClient) SwitchPublic(ctx context.Context, in *SwitchPublicReq, opts ...grpc.CallOption) (*SwitchPublicResp, error) {
	out := new(SwitchPublicResp)
	err := grpc.Invoke(ctx, "/register_provider_pb.ProviderRegisterService/SwitchPublic", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ProviderRegisterService service

type ProviderRegisterServiceServer interface {
	GetPublicKey(context.Context, *GetPublicKeyReq) (*GetPublicKeyResp, error)
	Register(context.Context, *RegisterReq) (*RegisterResp, error)
	VerifyBillEmail(context.Context, *VerifyBillEmailReq) (*VerifyBillEmailResp, error)
	ResendVerifyCode(context.Context, *ResendVerifyCodeReq) (*ResendVerifyCodeResp, error)
	AddExtraStorage(context.Context, *AddExtraStorageReq) (*AddExtraStorageResp, error)
	GetTrackerServer(context.Context, *GetTrackerServerReq) (*GetTrackerServerResp, error)
	GetCollectorServer(context.Context, *GetCollectorServerReq) (*GetCollectorServerResp, error)
	RefreshIp(context.Context, *RefreshIpReq) (*RefreshIpResp, error)
	SwitchPrivate(context.Context, *SwitchPrivateReq) (*SwitchPrivateResp, error)
	SwitchPublic(context.Context, *SwitchPublicReq) (*SwitchPublicResp, error)
}

func RegisterProviderRegisterServiceServer(s *grpc.Server, srv ProviderRegisterServiceServer) {
	s.RegisterService(&_ProviderRegisterService_serviceDesc, srv)
}

func _ProviderRegisterService_GetPublicKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPublicKeyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderRegisterServiceServer).GetPublicKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/register_provider_pb.ProviderRegisterService/GetPublicKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderRegisterServiceServer).GetPublicKey(ctx, req.(*GetPublicKeyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderRegisterService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderRegisterServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/register_provider_pb.ProviderRegisterService/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderRegisterServiceServer).Register(ctx, req.(*RegisterReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderRegisterService_VerifyBillEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyBillEmailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderRegisterServiceServer).VerifyBillEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/register_provider_pb.ProviderRegisterService/VerifyBillEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderRegisterServiceServer).VerifyBillEmail(ctx, req.(*VerifyBillEmailReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderRegisterService_ResendVerifyCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResendVerifyCodeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderRegisterServiceServer).ResendVerifyCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/register_provider_pb.ProviderRegisterService/ResendVerifyCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderRegisterServiceServer).ResendVerifyCode(ctx, req.(*ResendVerifyCodeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderRegisterService_AddExtraStorage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddExtraStorageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderRegisterServiceServer).AddExtraStorage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/register_provider_pb.ProviderRegisterService/AddExtraStorage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderRegisterServiceServer).AddExtraStorage(ctx, req.(*AddExtraStorageReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderRegisterService_GetTrackerServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTrackerServerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderRegisterServiceServer).GetTrackerServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/register_provider_pb.ProviderRegisterService/GetTrackerServer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderRegisterServiceServer).GetTrackerServer(ctx, req.(*GetTrackerServerReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderRegisterService_GetCollectorServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCollectorServerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderRegisterServiceServer).GetCollectorServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/register_provider_pb.ProviderRegisterService/GetCollectorServer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderRegisterServiceServer).GetCollectorServer(ctx, req.(*GetCollectorServerReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderRegisterService_RefreshIp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshIpReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderRegisterServiceServer).RefreshIp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/register_provider_pb.ProviderRegisterService/RefreshIp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderRegisterServiceServer).RefreshIp(ctx, req.(*RefreshIpReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderRegisterService_SwitchPrivate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SwitchPrivateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderRegisterServiceServer).SwitchPrivate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/register_provider_pb.ProviderRegisterService/SwitchPrivate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderRegisterServiceServer).SwitchPrivate(ctx, req.(*SwitchPrivateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderRegisterService_SwitchPublic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SwitchPublicReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderRegisterServiceServer).SwitchPublic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/register_provider_pb.ProviderRegisterService/SwitchPublic",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderRegisterServiceServer).SwitchPublic(ctx, req.(*SwitchPublicReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProviderRegisterService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "register_provider_pb.ProviderRegisterService",
	HandlerType: (*ProviderRegisterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPublicKey",
			Handler:    _ProviderRegisterService_GetPublicKey_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _ProviderRegisterService_Register_Handler,
		},
		{
			MethodName: "VerifyBillEmail",
			Handler:    _ProviderRegisterService_VerifyBillEmail_Handler,
		},
		{
			MethodName: "ResendVerifyCode",
			Handler:    _ProviderRegisterService_ResendVerifyCode_Handler,
		},
		{
			MethodName: "AddExtraStorage",
			Handler:    _ProviderRegisterService_AddExtraStorage_Handler,
		},
		{
			MethodName: "GetTrackerServer",
			Handler:    _ProviderRegisterService_GetTrackerServer_Handler,
		},
		{
			MethodName: "GetCollectorServer",
			Handler:    _ProviderRegisterService_GetCollectorServer_Handler,
		},
		{
			MethodName: "RefreshIp",
			Handler:    _ProviderRegisterService_RefreshIp_Handler,
		},
		{
			MethodName: "SwitchPrivate",
			Handler:    _ProviderRegisterService_SwitchPrivate_Handler,
		},
		{
			MethodName: "SwitchPublic",
			Handler:    _ProviderRegisterService_SwitchPublic_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "provider_register.proto",
}

func init() { proto.RegisterFile("provider_register.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1001 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x57, 0x4b, 0x6f, 0x23, 0x45,
	0x10, 0xde, 0x49, 0x26, 0x8e, 0x5d, 0xb1, 0xd7, 0x4e, 0x3b, 0x64, 0x47, 0x16, 0x02, 0x33, 0x0b,
	0x8b, 0xf7, 0x41, 0x40, 0xcb, 0x8d, 0xd5, 0x22, 0x65, 0x77, 0xa3, 0x10, 0x21, 0xa4, 0x68, 0x0c,
	0xe1, 0x18, 0x8d, 0x67, 0x3a, 0x71, 0x6b, 0xc7, 0x33, 0xbd, 0xdd, 0x9d, 0x09, 0x16, 0x77, 0x6e,
	0x48, 0x1c, 0xf9, 0x67, 0xfc, 0x12, 0xee, 0xa8, 0x7b, 0xde, 0xaf, 0xd8, 0x91, 0x48, 0x6e, 0xae,
	0xea, 0x6f, 0xba, 0xbe, 0xaa, 0xae, 0xae, 0xaf, 0x0d, 0x8f, 0x28, 0x0b, 0x42, 0xe2, 0x62, 0x76,
	0xce, 0xf0, 0x25, 0xe1, 0x02, 0xb3, 0x03, 0xca, 0x02, 0x11, 0xa0, 0xbd, 0xc4, 0x3e, 0x4f, 0x11,
	0x74, 0x66, 0x3e, 0x87, 0xfe, 0x31, 0x16, 0xa7, 0x57, 0x33, 0x8f, 0x38, 0x3f, 0xe2, 0xa5, 0x85,
	0x3f, 0x20, 0x03, 0xb6, 0x43, 0xcc, 0x38, 0x09, 0x7c, 0x43, 0x1b, 0x6b, 0x93, 0x9e, 0x95, 0x98,
	0xe6, 0x05, 0x0c, 0x8a, 0x60, 0x4e, 0xd1, 0xc7, 0xd0, 0xa1, 0x89, 0x43, 0xe1, 0xbb, 0x56, 0xe6,
	0x40, 0x9f, 0x43, 0x2f, 0x35, 0x7e, 0xb0, 0xf9, 0xdc, 0xd8, 0x50, 0x88, 0xa2, 0x13, 0x3d, 0x84,
	0x0d, 0x42, 0x8d, 0xcd, 0xb1, 0x36, 0xe9, 0x58, 0x1b, 0x84, 0x9a, 0xff, 0x6c, 0xc1, 0x8e, 0x15,
	0xb3, 0xbd, 0x91, 0x91, 0x8c, 0x2e, 0xc8, 0x02, 0x73, 0x61, 0x2f, 0xa8, 0xda, 0x5b, 0xb7, 0x32,
	0x87, 0x5c, 0xf5, 0x03, 0x17, 0x9f, 0xb8, 0x47, 0xbe, 0xa3, 0xb6, 0xef, 0x5a, 0x99, 0x03, 0x99,
	0xd0, 0x4d, 0x69, 0x48, 0x80, 0xae, 0x00, 0x05, 0x9f, 0xe4, 0x8f, 0x7d, 0x87, 0x2d, 0xa9, 0x88,
	0x41, 0x5b, 0x11, 0xff, 0x82, 0x13, 0x3d, 0x83, 0xc1, 0xb5, 0xed, 0x79, 0x58, 0x1c, 0xba, 0x2e,
	0xc3, 0x9c, 0x4b, 0x60, 0x4b, 0x01, 0x2b, 0x7e, 0x19, 0x75, 0x46, 0x3c, 0xef, 0x68, 0x61, 0x13,
	0x4f, 0xe2, 0xb6, 0xa3, 0xa8, 0x79, 0x1f, 0x7a, 0x01, 0xbb, 0x0b, 0x9b, 0xf8, 0x53, 0x11, 0x30,
	0xfb, 0x12, 0x9f, 0x05, 0xde, 0xd5, 0x02, 0x1b, 0x6d, 0x95, 0x5d, 0x75, 0x01, 0x8d, 0x61, 0xe7,
	0x8a, 0xbe, 0xb1, 0x7d, 0xf7, 0x9a, 0xb8, 0x62, 0x6e, 0x74, 0x14, 0x2e, 0xef, 0x92, 0x59, 0xb8,
	0xc1, 0xb5, 0x9f, 0x61, 0x40, 0x61, 0x8a, 0x4e, 0x34, 0x81, 0xbe, 0xc0, 0x5c, 0xfc, 0x92, 0xdb,
	0x6b, 0x47, 0xe1, 0xca, 0x6e, 0xc9, 0x4f, 0xba, 0xde, 0x15, 0xf6, 0xec, 0x46, 0xfc, 0x2a, 0x0b,
	0x32, 0x63, 0x3b, 0xb4, 0x89, 0x67, 0xcf, 0x88, 0x47, 0xc4, 0xd2, 0xe8, 0x8d, 0xb5, 0x89, 0x66,
	0x15, 0x7c, 0x08, 0x81, 0x4e, 0x03, 0x26, 0x8c, 0x87, 0xea, 0x78, 0xd5, 0x6f, 0x79, 0xea, 0xf3,
	0x80, 0x0b, 0x59, 0xa4, 0xbe, 0x2a, 0x52, 0x62, 0xca, 0x7a, 0xbb, 0x4b, 0xdf, 0x5e, 0x10, 0xe7,
	0x5d, 0x20, 0xeb, 0x21, 0x21, 0x83, 0xa8, 0xde, 0x65, 0x3f, 0x3a, 0x00, 0x84, 0x7f, 0x13, 0xcc,
	0x2e, 0x16, 0x73, 0x77, 0xbc, 0x39, 0xd1, 0xad, 0x9a, 0x95, 0x6a, 0xc7, 0xa2, 0xba, 0x8e, 0x45,
	0xa0, 0x73, 0x72, 0xe9, 0x1b, 0x43, 0xb5, 0xa8, 0x7e, 0xcb, 0x3c, 0x9d, 0xc0, 0xbf, 0x20, 0x6c,
	0x71, 0xe2, 0xfb, 0x98, 0x19, 0x7b, 0x63, 0x6d, 0xd2, 0xb6, 0x0a, 0x3e, 0xf3, 0x3b, 0xe8, 0x66,
	0x8d, 0xcd, 0xa9, 0xdc, 0xc7, 0x09, 0x5c, 0x1c, 0xb7, 0xb5, 0xfa, 0x8d, 0xf6, 0xa1, 0x85, 0x19,
	0xfb, 0x89, 0x5f, 0xaa, 0x86, 0xee, 0x58, 0xb1, 0x65, 0xfe, 0xad, 0x01, 0x3a, 0xc3, 0x8c, 0x5c,
	0x2c, 0xdf, 0x24, 0xcd, 0x72, 0xf3, 0xe5, 0xd8, 0x87, 0x56, 0xd4, 0xed, 0xf1, 0xad, 0x8b, 0xad,
	0xe2, 0xa5, 0xd9, 0x2c, 0x5f, 0x9a, 0x4f, 0x00, 0x42, 0x15, 0xe5, 0xad, 0x24, 0xa6, 0x2b, 0x0a,
	0x39, 0x4f, 0x9a, 0xfa, 0x56, 0x96, 0xba, 0x79, 0x08, 0xc3, 0x0a, 0xb3, 0x5b, 0x66, 0xb7, 0x84,
	0xa1, 0x85, 0x39, 0xf6, 0xdd, 0xb3, 0x34, 0xd4, 0x5d, 0x64, 0x97, 0xb0, 0xd7, 0x73, 0xec, 0xbf,
	0x81, 0xbd, 0x6a, 0x68, 0x4e, 0x65, 0x6c, 0x7e, 0xe5, 0x38, 0x98, 0x73, 0x15, 0xbb, 0x6d, 0x25,
	0xa6, 0xf9, 0x97, 0x06, 0xe8, 0xd0, 0x75, 0x8f, 0x72, 0xed, 0x73, 0x17, 0x64, 0xf7, 0xa1, 0x15,
	0x46, 0xfd, 0xaa, 0xab, 0xa5, 0xd8, 0xaa, 0x3d, 0x82, 0xaf, 0x61, 0x58, 0x61, 0x74, 0x63, 0x0e,
	0x4b, 0x18, 0x1e, 0x63, 0xf1, 0x33, 0xb3, 0x9d, 0xf7, 0x98, 0x4d, 0x31, 0x0b, 0x57, 0xcd, 0xda,
	0xff, 0xaf, 0xe0, 0x53, 0xd8, 0xab, 0x86, 0xe6, 0x14, 0xbd, 0x82, 0x16, 0x57, 0x96, 0xa1, 0x8d,
	0x37, 0x27, 0x3b, 0x2f, 0x1f, 0x1f, 0xd4, 0x69, 0xd6, 0x41, 0xf1, 0xc3, 0xf8, 0x13, 0xf3, 0x15,
	0xf4, 0x0a, 0x0b, 0x92, 0x6f, 0xba, 0x9b, 0xea, 0xb4, 0xc8, 0x4a, 0x67, 0xcd, 0x46, 0x36, 0x6b,
	0xcc, 0xdf, 0xe1, 0xa3, 0x63, 0x2c, 0xde, 0x06, 0x9e, 0x87, 0x1d, 0x11, 0xdc, 0x73, 0x39, 0x7e,
	0x85, 0xfd, 0xba, 0xe0, 0x9c, 0xa2, 0xd7, 0xa5, 0x82, 0x7c, 0x51, 0x5f, 0x90, 0xf2, 0xa7, 0x49,
	0x49, 0x5e, 0x43, 0xbf, 0xb4, 0x74, 0xab, 0xa2, 0xfc, 0xa1, 0xc9, 0x69, 0x75, 0xc1, 0x30, 0x9f,
	0x9f, 0xd0, 0x3b, 0x2a, 0x86, 0x0a, 0xaa, 0xe7, 0xa6, 0x7e, 0x5d, 0x6f, 0x7f, 0x0a, 0xbd, 0x1c,
	0x0f, 0x4e, 0xe3, 0x07, 0x83, 0x96, 0x3e, 0x18, 0x42, 0x18, 0x4c, 0xaf, 0x89, 0x70, 0xe6, 0xa7,
	0x8c, 0x84, 0xb6, 0xb8, 0xb7, 0xc9, 0xf1, 0x15, 0xec, 0x96, 0xe2, 0xde, 0x78, 0xe5, 0xfe, 0xd5,
	0xa0, 0x1f, 0xe3, 0x95, 0x9a, 0xdc, 0x13, 0xcd, 0xaa, 0xa6, 0x6d, 0x35, 0x68, 0x9a, 0x3a, 0x8d,
	0x56, 0xbd, 0x06, 0x6f, 0xaf, 0xd6, 0xe0, 0x76, 0xbd, 0x06, 0x9b, 0xdf, 0xa7, 0xc7, 0x13, 0xa7,
	0x7d, 0x3b, 0x6d, 0x78, 0xf9, 0x67, 0x1b, 0x1e, 0x9d, 0xc6, 0xfd, 0x9e, 0xc8, 0xa7, 0xec, 0x67,
	0xe2, 0x60, 0x74, 0x0e, 0xdd, 0xfc, 0x9b, 0x14, 0x35, 0x5c, 0x91, 0xd2, 0x23, 0x77, 0xf4, 0x64,
	0x1d, 0x18, 0xa7, 0xe6, 0x03, 0x34, 0x85, 0x76, 0x12, 0x13, 0x7d, 0x56, 0xff, 0x55, 0xee, 0xad,
	0x3a, 0x32, 0x57, 0x41, 0xd4, 0xa6, 0x73, 0xe8, 0x97, 0x04, 0x13, 0x4d, 0xea, 0x3f, 0xac, 0x2a,
	0xfe, 0xe8, 0xe9, 0x9a, 0x48, 0x15, 0xe9, 0x3d, 0x0c, 0xca, 0xe2, 0x86, 0x9e, 0x36, 0x71, 0xac,
	0xe8, 0xef, 0xe8, 0xd9, 0xba, 0xd0, 0x24, 0xad, 0x92, 0x08, 0x35, 0xa5, 0x55, 0x55, 0xcf, 0xa6,
	0xb4, 0x6a, 0x54, 0x2d, 0x4a, 0xab, 0x2c, 0x21, 0x4d, 0x69, 0xd5, 0xa8, 0x5c, 0x53, 0x5a, 0x75,
	0xaa, 0x64, 0x3e, 0x40, 0x1f, 0x00, 0x55, 0x07, 0x34, 0x7a, 0xde, 0xb8, 0x47, 0x55, 0x47, 0x46,
	0x2f, 0xd6, 0x07, 0xab, 0x90, 0x67, 0xd0, 0x49, 0x47, 0x1e, 0x6a, 0xec, 0xa9, 0x6c, 0x36, 0x8f,
	0x1e, 0xaf, 0xc4, 0xa8, 0x7d, 0x67, 0xd0, 0x2b, 0x4c, 0x2c, 0xd4, 0x70, 0x11, 0xca, 0xe3, 0x74,
	0xf4, 0xe5, 0x5a, 0x38, 0x15, 0xe3, 0x1c, 0xba, 0xf9, 0xeb, 0xde, 0x74, 0x25, 0x4b, 0x93, 0x70,
	0xf4, 0x64, 0x1d, 0x98, 0x0c, 0x30, 0x6b, 0xa9, 0x7f, 0xb4, 0xdf, 0xfe, 0x17, 0x00, 0x00, 0xff,
	0xff, 0xc4, 0xa6, 0xec, 0xf8, 0xec, 0x0e, 0x00, 0x00,
}
