// Code generated by protoc-gen-go. DO NOT EDIT.
// source: provider_register.proto

/*
Package provider_client_pb is a generated protocol buffer package.

It is generated from these files:
	provider_register.proto

It has these top-level messages:
	GetPublicKeyReq
	PublicKeyResp
	RegisterReq
	RegisterResp
*/
package provider_client_pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetPublicKeyReq struct {
	Version uint32 `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
}

func (m *GetPublicKeyReq) Reset()                    { *m = GetPublicKeyReq{} }
func (m *GetPublicKeyReq) String() string            { return proto.CompactTextString(m) }
func (*GetPublicKeyReq) ProtoMessage()               {}
func (*GetPublicKeyReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GetPublicKeyReq) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

type PublicKeyResp struct {
	PublicKey []byte `protobuf:"bytes,1,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
}

func (m *PublicKeyResp) Reset()                    { *m = PublicKeyResp{} }
func (m *PublicKeyResp) String() string            { return proto.CompactTextString(m) }
func (*PublicKeyResp) ProtoMessage()               {}
func (*PublicKeyResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PublicKeyResp) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

type RegisterReq struct {
	Version            uint32   `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	Auth               []byte   `protobuf:"bytes,2,opt,name=auth,proto3" json:"auth,omitempty"`
	NodeIdEnc          []byte   `protobuf:"bytes,3,opt,name=nodeIdEnc,proto3" json:"nodeIdEnc,omitempty"`
	PublicKeyEnc       []byte   `protobuf:"bytes,4,opt,name=publicKeyEnc,proto3" json:"publicKeyEnc,omitempty"`
	EncryptKeyEnc      []byte   `protobuf:"bytes,5,opt,name=encryptKeyEnc,proto3" json:"encryptKeyEnc,omitempty"`
	WalletAddressEnc   []byte   `protobuf:"bytes,6,opt,name=walletAddressEnc,proto3" json:"walletAddressEnc,omitempty"`
	BillEmailEnc       []byte   `protobuf:"bytes,7,opt,name=billEmailEnc,proto3" json:"billEmailEnc,omitempty"`
	MainStorageVolume  uint64   `protobuf:"varint,8,opt,name=mainStorageVolume" json:"mainStorageVolume,omitempty"`
	UpBandwidth        uint64   `protobuf:"varint,9,opt,name=upBandwidth" json:"upBandwidth,omitempty"`
	DownBandwidth      uint64   `protobuf:"varint,10,opt,name=downBandwidth" json:"downBandwidth,omitempty"`
	TestUpBandwidth    uint64   `protobuf:"varint,11,opt,name=testUpBandwidth" json:"testUpBandwidth,omitempty"`
	TestDownBandwidth  uint64   `protobuf:"varint,12,opt,name=testDownBandwidth" json:"testDownBandwidth,omitempty"`
	Availability       float32  `protobuf:"fixed32,13,opt,name=availability" json:"availability,omitempty"`
	ExtraStorageVolume []uint64 `protobuf:"varint,14,rep,packed,name=extraStorageVolume" json:"extraStorageVolume,omitempty"`
}

func (m *RegisterReq) Reset()                    { *m = RegisterReq{} }
func (m *RegisterReq) String() string            { return proto.CompactTextString(m) }
func (*RegisterReq) ProtoMessage()               {}
func (*RegisterReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *RegisterReq) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *RegisterReq) GetAuth() []byte {
	if m != nil {
		return m.Auth
	}
	return nil
}

func (m *RegisterReq) GetNodeIdEnc() []byte {
	if m != nil {
		return m.NodeIdEnc
	}
	return nil
}

func (m *RegisterReq) GetPublicKeyEnc() []byte {
	if m != nil {
		return m.PublicKeyEnc
	}
	return nil
}

func (m *RegisterReq) GetEncryptKeyEnc() []byte {
	if m != nil {
		return m.EncryptKeyEnc
	}
	return nil
}

func (m *RegisterReq) GetWalletAddressEnc() []byte {
	if m != nil {
		return m.WalletAddressEnc
	}
	return nil
}

func (m *RegisterReq) GetBillEmailEnc() []byte {
	if m != nil {
		return m.BillEmailEnc
	}
	return nil
}

func (m *RegisterReq) GetMainStorageVolume() uint64 {
	if m != nil {
		return m.MainStorageVolume
	}
	return 0
}

func (m *RegisterReq) GetUpBandwidth() uint64 {
	if m != nil {
		return m.UpBandwidth
	}
	return 0
}

func (m *RegisterReq) GetDownBandwidth() uint64 {
	if m != nil {
		return m.DownBandwidth
	}
	return 0
}

func (m *RegisterReq) GetTestUpBandwidth() uint64 {
	if m != nil {
		return m.TestUpBandwidth
	}
	return 0
}

func (m *RegisterReq) GetTestDownBandwidth() uint64 {
	if m != nil {
		return m.TestDownBandwidth
	}
	return 0
}

func (m *RegisterReq) GetAvailability() float32 {
	if m != nil {
		return m.Availability
	}
	return 0
}

func (m *RegisterReq) GetExtraStorageVolume() []uint64 {
	if m != nil {
		return m.ExtraStorageVolume
	}
	return nil
}

type RegisterResp struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (m *RegisterResp) Reset()                    { *m = RegisterResp{} }
func (m *RegisterResp) String() string            { return proto.CompactTextString(m) }
func (*RegisterResp) ProtoMessage()               {}
func (*RegisterResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *RegisterResp) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*GetPublicKeyReq)(nil), "provider.client.pb.GetPublicKeyReq")
	proto.RegisterType((*PublicKeyResp)(nil), "provider.client.pb.PublicKeyResp")
	proto.RegisterType((*RegisterReq)(nil), "provider.client.pb.RegisterReq")
	proto.RegisterType((*RegisterResp)(nil), "provider.client.pb.RegisterResp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ProviderRegisterService service

type ProviderRegisterServiceClient interface {
	GetPublicKey(ctx context.Context, in *GetPublicKeyReq, opts ...grpc.CallOption) (*PublicKeyResp, error)
	Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error)
}

type providerRegisterServiceClient struct {
	cc *grpc.ClientConn
}

func NewProviderRegisterServiceClient(cc *grpc.ClientConn) ProviderRegisterServiceClient {
	return &providerRegisterServiceClient{cc}
}

func (c *providerRegisterServiceClient) GetPublicKey(ctx context.Context, in *GetPublicKeyReq, opts ...grpc.CallOption) (*PublicKeyResp, error) {
	out := new(PublicKeyResp)
	err := grpc.Invoke(ctx, "/provider.client.pb.ProviderRegisterService/GetPublicKey", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerRegisterServiceClient) Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error) {
	out := new(RegisterResp)
	err := grpc.Invoke(ctx, "/provider.client.pb.ProviderRegisterService/Register", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ProviderRegisterService service

type ProviderRegisterServiceServer interface {
	GetPublicKey(context.Context, *GetPublicKeyReq) (*PublicKeyResp, error)
	Register(context.Context, *RegisterReq) (*RegisterResp, error)
}

func RegisterProviderRegisterServiceServer(s *grpc.Server, srv ProviderRegisterServiceServer) {
	s.RegisterService(&_ProviderRegisterService_serviceDesc, srv)
}

func _ProviderRegisterService_GetPublicKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPublicKeyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderRegisterServiceServer).GetPublicKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/provider.client.pb.ProviderRegisterService/GetPublicKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderRegisterServiceServer).GetPublicKey(ctx, req.(*GetPublicKeyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderRegisterService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderRegisterServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/provider.client.pb.ProviderRegisterService/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderRegisterServiceServer).Register(ctx, req.(*RegisterReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProviderRegisterService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "provider.client.pb.ProviderRegisterService",
	HandlerType: (*ProviderRegisterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPublicKey",
			Handler:    _ProviderRegisterService_GetPublicKey_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _ProviderRegisterService_Register_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "provider_register.proto",
}

func init() { proto.RegisterFile("provider_register.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 428 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x93, 0xdf, 0x6e, 0xd3, 0x30,
	0x14, 0xc6, 0xc9, 0x16, 0xb6, 0xee, 0x34, 0x65, 0x70, 0x6e, 0x16, 0x4d, 0x48, 0x84, 0xc0, 0x45,
	0xc4, 0x9f, 0x5c, 0xc0, 0x13, 0x80, 0x98, 0x10, 0xe2, 0x82, 0x29, 0x13, 0x88, 0x3b, 0xe4, 0x24,
	0x47, 0x9b, 0x25, 0xd7, 0x36, 0xb6, 0xd3, 0xd2, 0x07, 0xe1, 0x8d, 0x78, 0x30, 0x64, 0xb7, 0x59,
	0x93, 0xb5, 0xda, 0x5d, 0xf3, 0x3b, 0x3f, 0x7f, 0xc7, 0x96, 0xbe, 0xc2, 0x99, 0x36, 0x6a, 0xc1,
	0x5b, 0x32, 0xbf, 0x0c, 0x5d, 0x73, 0xeb, 0xc8, 0x94, 0xda, 0x28, 0xa7, 0x10, 0xfb, 0x41, 0xd9,
	0x08, 0x4e, 0xd2, 0x95, 0xba, 0xce, 0x5f, 0xc3, 0xe9, 0x67, 0x72, 0x97, 0x5d, 0x2d, 0x78, 0xf3,
	0x95, 0x56, 0x15, 0xfd, 0xc6, 0x14, 0x8e, 0x17, 0x64, 0x2c, 0x57, 0x32, 0x8d, 0xb2, 0xa8, 0x98,
	0x55, 0xfd, 0x67, 0xfe, 0x16, 0x66, 0x03, 0xd3, 0x6a, 0x7c, 0x0a, 0x27, 0xba, 0x07, 0x41, 0x4e,
	0xaa, 0x2d, 0xc8, 0xff, 0xc6, 0x30, 0xad, 0x36, 0x57, 0xb8, 0x37, 0x18, 0x11, 0x62, 0xd6, 0xb9,
	0x9b, 0xf4, 0x20, 0x44, 0x84, 0xdf, 0x3e, 0x5b, 0xaa, 0x96, 0xbe, 0xb4, 0x17, 0xb2, 0x49, 0x0f,
	0xd7, 0xd9, 0xb7, 0x00, 0x73, 0x48, 0x6e, 0x17, 0x79, 0x21, 0x0e, 0xc2, 0x88, 0xe1, 0x4b, 0x98,
	0x91, 0x6c, 0xcc, 0x4a, 0xbb, 0x8d, 0xf4, 0x30, 0x48, 0x63, 0x88, 0xaf, 0xe0, 0xf1, 0x92, 0x09,
	0x41, 0xee, 0x43, 0xdb, 0x1a, 0xb2, 0xd6, 0x8b, 0x47, 0x41, 0xdc, 0xe1, 0x7e, 0x6b, 0xcd, 0x85,
	0xb8, 0x98, 0x33, 0x2e, 0xbc, 0x77, 0xbc, 0xde, 0x3a, 0x64, 0xf8, 0x06, 0x9e, 0xcc, 0x19, 0x97,
	0x57, 0x4e, 0x19, 0x76, 0x4d, 0x3f, 0x94, 0xe8, 0xe6, 0x94, 0x4e, 0xb2, 0xa8, 0x88, 0xab, 0xdd,
	0x01, 0x66, 0x30, 0xed, 0xf4, 0x47, 0x26, 0xdb, 0x25, 0x6f, 0xdd, 0x4d, 0x7a, 0x12, 0xbc, 0x21,
	0xf2, 0xaf, 0x68, 0xd5, 0x52, 0x6e, 0x1d, 0x08, 0xce, 0x18, 0x62, 0x01, 0xa7, 0x8e, 0xac, 0xfb,
	0x3e, 0xc8, 0x9a, 0x06, 0xef, 0x2e, 0xf6, 0xf7, 0xf3, 0xe8, 0xd3, 0x28, 0x33, 0x59, 0xdf, 0x6f,
	0x67, 0xe0, 0x5f, 0xcc, 0x16, 0x8c, 0x0b, 0x56, 0x73, 0xc1, 0xdd, 0x2a, 0x9d, 0x65, 0x51, 0x71,
	0x50, 0x8d, 0x18, 0x96, 0x80, 0xf4, 0xc7, 0x19, 0x36, 0x7e, 0xf2, 0xa3, 0xec, 0xb0, 0x88, 0xab,
	0x3d, 0x93, 0xbc, 0x80, 0x64, 0x5b, 0x0b, 0xab, 0x7d, 0x2f, 0x6c, 0xd7, 0x34, 0x64, 0x6d, 0xe8,
	0xc5, 0xa4, 0xea, 0x3f, 0xdf, 0xfd, 0x8b, 0xe0, 0xec, 0x72, 0x53, 0xda, 0xfe, 0xc8, 0x15, 0x99,
	0x05, 0x6f, 0x08, 0x7f, 0x42, 0x32, 0x6c, 0x2e, 0xbe, 0x28, 0x77, 0xeb, 0x5d, 0xde, 0xe9, 0xf6,
	0xf9, 0xf3, 0x7d, 0xd2, 0xa8, 0xd3, 0xf9, 0x03, 0xfc, 0x06, 0x93, 0x7e, 0x19, 0x3e, 0xdb, 0x77,
	0x60, 0x50, 0xea, 0xf3, 0xec, 0x7e, 0xc1, 0x07, 0xd6, 0x47, 0xe1, 0xff, 0xf7, 0xfe, 0x7f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x3c, 0xa3, 0x11, 0x1d, 0x9a, 0x03, 0x00, 0x00,
}
