// Code generated by protoc-gen-go. DO NOT EDIT.
// source: client_collector.proto

/*
Package collector_client_pb is a generated protocol buffer package.

It is generated from these files:
	client_collector.proto

It has these top-level messages:
	CollectReq
	Batch
	CollectResp
	ActionLog
*/
package collector_client_pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CollectReq struct {
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *CollectReq) Reset()                    { *m = CollectReq{} }
func (m *CollectReq) String() string            { return proto.CompactTextString(m) }
func (*CollectReq) ProtoMessage()               {}
func (*CollectReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CollectReq) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Batch struct {
	Version   uint32       `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	NodeId    []byte       `protobuf:"bytes,2,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	Timestamp uint64       `protobuf:"varint,3,opt,name=timestamp" json:"timestamp,omitempty"`
	ActionLog []*ActionLog `protobuf:"bytes,4,rep,name=actionLog" json:"actionLog,omitempty"`
	Sign      []byte       `protobuf:"bytes,5,opt,name=sign,proto3" json:"sign,omitempty"`
}

func (m *Batch) Reset()                    { *m = Batch{} }
func (m *Batch) String() string            { return proto.CompactTextString(m) }
func (*Batch) ProtoMessage()               {}
func (*Batch) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Batch) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Batch) GetNodeId() []byte {
	if m != nil {
		return m.NodeId
	}
	return nil
}

func (m *Batch) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Batch) GetActionLog() []*ActionLog {
	if m != nil {
		return m.ActionLog
	}
	return nil
}

func (m *Batch) GetSign() []byte {
	if m != nil {
		return m.Sign
	}
	return nil
}

type CollectResp struct {
}

func (m *CollectResp) Reset()                    { *m = CollectResp{} }
func (m *CollectResp) String() string            { return proto.CompactTextString(m) }
func (*CollectResp) ProtoMessage()               {}
func (*CollectResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type ActionLog struct {
	Type           uint32 `protobuf:"varint,1,opt,name=type" json:"type,omitempty"`
	OppositeNodeId []byte `protobuf:"bytes,2,opt,name=oppositeNodeId,proto3" json:"oppositeNodeId,omitempty"`
	Ticket         string `protobuf:"bytes,3,opt,name=ticket" json:"ticket,omitempty"`
	Success        bool   `protobuf:"varint,4,opt,name=success" json:"success,omitempty"`
	FileHash       []byte `protobuf:"bytes,5,opt,name=fileHash,proto3" json:"fileHash,omitempty"`
	FileSize       uint64 `protobuf:"varint,6,opt,name=fileSize" json:"fileSize,omitempty"`
	PartitionSeq   uint32 `protobuf:"varint,7,opt,name=partitionSeq" json:"partitionSeq,omitempty"`
	Checksum       bool   `protobuf:"varint,8,opt,name=checksum" json:"checksum,omitempty"`
	BlockSeq       uint32 `protobuf:"varint,9,opt,name=blockSeq" json:"blockSeq,omitempty"`
	BlockHash      []byte `protobuf:"bytes,10,opt,name=blockHash,proto3" json:"blockHash,omitempty"`
	BlockSize      uint64 `protobuf:"varint,11,opt,name=blockSize" json:"blockSize,omitempty"`
	BeginTime      uint64 `protobuf:"varint,12,opt,name=beginTime" json:"beginTime,omitempty"`
	EndTime        uint64 `protobuf:"varint,13,opt,name=endTime" json:"endTime,omitempty"`
	TransportSize  uint64 `protobuf:"varint,14,opt,name=transportSize" json:"transportSize,omitempty"`
	Info           string `protobuf:"bytes,15,opt,name=info" json:"info,omitempty"`
}

func (m *ActionLog) Reset()                    { *m = ActionLog{} }
func (m *ActionLog) String() string            { return proto.CompactTextString(m) }
func (*ActionLog) ProtoMessage()               {}
func (*ActionLog) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ActionLog) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *ActionLog) GetOppositeNodeId() []byte {
	if m != nil {
		return m.OppositeNodeId
	}
	return nil
}

func (m *ActionLog) GetTicket() string {
	if m != nil {
		return m.Ticket
	}
	return ""
}

func (m *ActionLog) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ActionLog) GetFileHash() []byte {
	if m != nil {
		return m.FileHash
	}
	return nil
}

func (m *ActionLog) GetFileSize() uint64 {
	if m != nil {
		return m.FileSize
	}
	return 0
}

func (m *ActionLog) GetPartitionSeq() uint32 {
	if m != nil {
		return m.PartitionSeq
	}
	return 0
}

func (m *ActionLog) GetChecksum() bool {
	if m != nil {
		return m.Checksum
	}
	return false
}

func (m *ActionLog) GetBlockSeq() uint32 {
	if m != nil {
		return m.BlockSeq
	}
	return 0
}

func (m *ActionLog) GetBlockHash() []byte {
	if m != nil {
		return m.BlockHash
	}
	return nil
}

func (m *ActionLog) GetBlockSize() uint64 {
	if m != nil {
		return m.BlockSize
	}
	return 0
}

func (m *ActionLog) GetBeginTime() uint64 {
	if m != nil {
		return m.BeginTime
	}
	return 0
}

func (m *ActionLog) GetEndTime() uint64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

func (m *ActionLog) GetTransportSize() uint64 {
	if m != nil {
		return m.TransportSize
	}
	return 0
}

func (m *ActionLog) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

func init() {
	proto.RegisterType((*CollectReq)(nil), "collector.client.pb.CollectReq")
	proto.RegisterType((*Batch)(nil), "collector.client.pb.Batch")
	proto.RegisterType((*CollectResp)(nil), "collector.client.pb.CollectResp")
	proto.RegisterType((*ActionLog)(nil), "collector.client.pb.ActionLog")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ClientCollectorService service

type ClientCollectorServiceClient interface {
	Collect(ctx context.Context, opts ...grpc.CallOption) (ClientCollectorService_CollectClient, error)
}

type clientCollectorServiceClient struct {
	cc *grpc.ClientConn
}

func NewClientCollectorServiceClient(cc *grpc.ClientConn) ClientCollectorServiceClient {
	return &clientCollectorServiceClient{cc}
}

func (c *clientCollectorServiceClient) Collect(ctx context.Context, opts ...grpc.CallOption) (ClientCollectorService_CollectClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_ClientCollectorService_serviceDesc.Streams[0], c.cc, "/collector.client.pb.ClientCollectorService/Collect", opts...)
	if err != nil {
		return nil, err
	}
	x := &clientCollectorServiceCollectClient{stream}
	return x, nil
}

type ClientCollectorService_CollectClient interface {
	Send(*CollectReq) error
	CloseAndRecv() (*CollectResp, error)
	grpc.ClientStream
}

type clientCollectorServiceCollectClient struct {
	grpc.ClientStream
}

func (x *clientCollectorServiceCollectClient) Send(m *CollectReq) error {
	return x.ClientStream.SendMsg(m)
}

func (x *clientCollectorServiceCollectClient) CloseAndRecv() (*CollectResp, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(CollectResp)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for ClientCollectorService service

type ClientCollectorServiceServer interface {
	Collect(ClientCollectorService_CollectServer) error
}

func RegisterClientCollectorServiceServer(s *grpc.Server, srv ClientCollectorServiceServer) {
	s.RegisterService(&_ClientCollectorService_serviceDesc, srv)
}

func _ClientCollectorService_Collect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ClientCollectorServiceServer).Collect(&clientCollectorServiceCollectServer{stream})
}

type ClientCollectorService_CollectServer interface {
	SendAndClose(*CollectResp) error
	Recv() (*CollectReq, error)
	grpc.ServerStream
}

type clientCollectorServiceCollectServer struct {
	grpc.ServerStream
}

func (x *clientCollectorServiceCollectServer) SendAndClose(m *CollectResp) error {
	return x.ServerStream.SendMsg(m)
}

func (x *clientCollectorServiceCollectServer) Recv() (*CollectReq, error) {
	m := new(CollectReq)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _ClientCollectorService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "collector.client.pb.ClientCollectorService",
	HandlerType: (*ClientCollectorServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Collect",
			Handler:       _ClientCollectorService_Collect_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "client_collector.proto",
}

func init() { proto.RegisterFile("client_collector.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 429 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x53, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xc5, 0x24, 0x4d, 0xe2, 0x49, 0x52, 0xa4, 0x45, 0x8a, 0x56, 0x15, 0x02, 0xcb, 0x42, 0xc8,
	0x27, 0x1f, 0xca, 0x95, 0x4b, 0xc9, 0x05, 0x24, 0x84, 0x90, 0xc3, 0x1d, 0x6d, 0xd6, 0xd3, 0x64,
	0x89, 0xbd, 0xbb, 0xf5, 0x6e, 0x2b, 0xc1, 0x3f, 0xe2, 0x37, 0xf0, 0xe7, 0xd0, 0x8e, 0xbf, 0x5a,
	0x54, 0xf5, 0x36, 0xef, 0xbd, 0x79, 0xc9, 0x9b, 0xd9, 0x31, 0x6c, 0x64, 0xa5, 0x50, 0xfb, 0x1f,
	0xd2, 0x54, 0x15, 0x4a, 0x6f, 0x9a, 0xdc, 0x36, 0xc6, 0x1b, 0xf6, 0x72, 0x24, 0xda, 0x8e, 0xdc,
	0xee, 0xd3, 0x04, 0x60, 0xdb, 0xd2, 0x05, 0xde, 0x30, 0x06, 0xd3, 0x52, 0x78, 0xc1, 0xa3, 0x24,
	0xca, 0x56, 0x05, 0xd5, 0xe9, 0x9f, 0x08, 0xce, 0x3e, 0x0a, 0x2f, 0x8f, 0x8c, 0xc3, 0xfc, 0x0e,
	0x1b, 0xa7, 0x8c, 0xa6, 0x86, 0x75, 0xd1, 0x43, 0xb6, 0x81, 0x99, 0x36, 0x25, 0x7e, 0x2e, 0xf9,
	0x73, 0x72, 0x76, 0x88, 0xbd, 0x82, 0xd8, 0xab, 0x1a, 0x9d, 0x17, 0xb5, 0xe5, 0x93, 0x24, 0xca,
	0xa6, 0xc5, 0x48, 0xb0, 0x0f, 0x10, 0x0b, 0xe9, 0x95, 0xd1, 0x5f, 0xcc, 0x81, 0x4f, 0x93, 0x49,
	0xb6, 0xbc, 0x7c, 0x9d, 0x3f, 0x12, 0x32, 0xbf, 0xea, 0xbb, 0x8a, 0xd1, 0x10, 0xb2, 0x3a, 0x75,
	0xd0, 0xfc, 0xac, 0xcd, 0x1a, 0xea, 0x74, 0x0d, 0xcb, 0x61, 0x1a, 0x67, 0xd3, 0xbf, 0x13, 0x88,
	0xaf, 0xee, 0x1b, 0xfc, 0x2f, 0x8b, 0x5d, 0x76, 0xaa, 0xd9, 0x3b, 0x38, 0x37, 0xd6, 0x1a, 0xa7,
	0x3c, 0x7e, 0xbd, 0x3f, 0xc0, 0x7f, 0x6c, 0x18, 0xd0, 0x2b, 0x79, 0x42, 0x4f, 0x53, 0xc4, 0x45,
	0x87, 0xc2, 0x4a, 0xdc, 0xad, 0x94, 0xe8, 0x1c, 0x9f, 0x26, 0x51, 0xb6, 0x28, 0x7a, 0xc8, 0x2e,
	0x60, 0x71, 0xad, 0x2a, 0xfc, 0x24, 0xdc, 0xb1, 0x8b, 0x38, 0xe0, 0x5e, 0xdb, 0xa9, 0xdf, 0xc8,
	0x67, 0xb4, 0x95, 0x01, 0xb3, 0x14, 0x56, 0x56, 0x34, 0x5e, 0x85, 0xd4, 0x3b, 0xbc, 0xe1, 0x73,
	0x4a, 0xfb, 0x80, 0x0b, 0x7e, 0x79, 0x44, 0x79, 0x72, 0xb7, 0x35, 0x5f, 0xd0, 0xdf, 0x0e, 0x38,
	0x68, 0xfb, 0xca, 0xc8, 0x53, 0xf0, 0xc6, 0xe4, 0x1d, 0x70, 0x78, 0x0e, 0xaa, 0x29, 0x14, 0x50,
	0xa8, 0x91, 0x18, 0x54, 0x8a, 0xb5, 0x6c, 0x1f, 0x6b, 0x20, 0x48, 0xc5, 0x83, 0xd2, 0xdf, 0x55,
	0x8d, 0x7c, 0xd5, 0xa9, 0x3d, 0x11, 0xf6, 0x80, 0xba, 0x24, 0x6d, 0x4d, 0x5a, 0x0f, 0xd9, 0x5b,
	0x58, 0xfb, 0x46, 0x68, 0x67, 0x4d, 0xe3, 0xe9, 0x97, 0xcf, 0x49, 0x7f, 0x48, 0x86, 0xb7, 0x51,
	0xfa, 0xda, 0xf0, 0x17, 0xb4, 0x5d, 0xaa, 0x2f, 0x7f, 0xc2, 0x66, 0x4b, 0x27, 0xb0, 0xed, 0x4f,
	0x62, 0x87, 0xcd, 0x9d, 0x92, 0xc8, 0xbe, 0xc1, 0xbc, 0xe3, 0xd8, 0x9b, 0x47, 0x0f, 0x66, 0x3c,
	0xe9, 0x8b, 0xe4, 0xe9, 0x06, 0x67, 0xd3, 0x67, 0x59, 0xb4, 0x9f, 0xd1, 0x27, 0xf2, 0xfe, 0x5f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x85, 0x31, 0x61, 0x9a, 0x3c, 0x03, 0x00, 0x00,
}
