// Code generated by protoc-gen-go. DO NOT EDIT.
// source: metadata.proto

/*
Package metadata_pb is a generated protocol buffer package.

It is generated from these files:
	metadata.proto

It has these top-level messages:
	MkFolderReq
	MkFolderResp
	CheckFileExistReq
	CheckFileExistResp
	ReplicaProvider
	UploadFilePrepareReq
	PieceHashAndSize
	UploadFilePrepareResp
	ErasureCodeProvider
	PieceHashAuth
	UploadFileDoneReq
	Partition
	Block
	UploadFileDoneResp
	ListFilesReq
	ListFilesResp
	FileOrFolder
	RetrieveFileReq
	RetrieveFileResp
	RetrievePartition
	RetrieveBlock
	RetrieveNode
	RemoveReq
	RemoveResp
*/
package metadata_pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FileStoreType int32

const (
	FileStoreType_ErasureCode  FileStoreType = 0
	FileStoreType_MultiReplica FileStoreType = 1
)

var FileStoreType_name = map[int32]string{
	0: "ErasureCode",
	1: "MultiReplica",
}
var FileStoreType_value = map[string]int32{
	"ErasureCode":  0,
	"MultiReplica": 1,
}

func (x FileStoreType) String() string {
	return proto.EnumName(FileStoreType_name, int32(x))
}
func (FileStoreType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type SortType int32

const (
	SortType_Name    SortType = 0
	SortType_ModTime SortType = 1
	SortType_Size    SortType = 2
)

var SortType_name = map[int32]string{
	0: "Name",
	1: "ModTime",
	2: "Size",
}
var SortType_value = map[string]int32{
	"Name":    0,
	"ModTime": 1,
	"Size":    2,
}

func (x SortType) String() string {
	return proto.EnumName(SortType_name, int32(x))
}
func (SortType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type MkFolderReq struct {
	Version   uint32   `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	NodeId    []byte   `protobuf:"bytes,2,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	Timestamp uint64   `protobuf:"varint,3,opt,name=timestamp" json:"timestamp,omitempty"`
	Path      string   `protobuf:"bytes,4,opt,name=path" json:"path,omitempty"`
	Folder    []string `protobuf:"bytes,5,rep,name=folder" json:"folder,omitempty"`
	Sign      []byte   `protobuf:"bytes,6,opt,name=sign,proto3" json:"sign,omitempty"`
}

func (m *MkFolderReq) Reset()                    { *m = MkFolderReq{} }
func (m *MkFolderReq) String() string            { return proto.CompactTextString(m) }
func (*MkFolderReq) ProtoMessage()               {}
func (*MkFolderReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *MkFolderReq) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *MkFolderReq) GetNodeId() []byte {
	if m != nil {
		return m.NodeId
	}
	return nil
}

func (m *MkFolderReq) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *MkFolderReq) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *MkFolderReq) GetFolder() []string {
	if m != nil {
		return m.Folder
	}
	return nil
}

func (m *MkFolderReq) GetSign() []byte {
	if m != nil {
		return m.Sign
	}
	return nil
}

type MkFolderResp struct {
	Code   uint32 `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	ErrMsg string `protobuf:"bytes,2,opt,name=errMsg" json:"errMsg,omitempty"`
}

func (m *MkFolderResp) Reset()                    { *m = MkFolderResp{} }
func (m *MkFolderResp) String() string            { return proto.CompactTextString(m) }
func (*MkFolderResp) ProtoMessage()               {}
func (*MkFolderResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *MkFolderResp) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *MkFolderResp) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

type CheckFileExistReq struct {
	Version     uint32 `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	NodeId      []byte `protobuf:"bytes,2,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	Timestamp   uint64 `protobuf:"varint,3,opt,name=timestamp" json:"timestamp,omitempty"`
	FilePath    string `protobuf:"bytes,4,opt,name=filePath" json:"filePath,omitempty"`
	FileHash    []byte `protobuf:"bytes,5,opt,name=fileHash,proto3" json:"fileHash,omitempty"`
	FileSize    uint64 `protobuf:"varint,6,opt,name=fileSize" json:"fileSize,omitempty"`
	FileName    string `protobuf:"bytes,7,opt,name=fileName" json:"fileName,omitempty"`
	FileModTime uint64 `protobuf:"varint,8,opt,name=fileModTime" json:"fileModTime,omitempty"`
	FileData    []byte `protobuf:"bytes,9,opt,name=fileData,proto3" json:"fileData,omitempty"`
	Interactive bool   `protobuf:"varint,10,opt,name=interactive" json:"interactive,omitempty"`
	NewVersion  bool   `protobuf:"varint,11,opt,name=newVersion" json:"newVersion,omitempty"`
	Sign        []byte `protobuf:"bytes,12,opt,name=sign,proto3" json:"sign,omitempty"`
}

func (m *CheckFileExistReq) Reset()                    { *m = CheckFileExistReq{} }
func (m *CheckFileExistReq) String() string            { return proto.CompactTextString(m) }
func (*CheckFileExistReq) ProtoMessage()               {}
func (*CheckFileExistReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CheckFileExistReq) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *CheckFileExistReq) GetNodeId() []byte {
	if m != nil {
		return m.NodeId
	}
	return nil
}

func (m *CheckFileExistReq) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *CheckFileExistReq) GetFilePath() string {
	if m != nil {
		return m.FilePath
	}
	return ""
}

func (m *CheckFileExistReq) GetFileHash() []byte {
	if m != nil {
		return m.FileHash
	}
	return nil
}

func (m *CheckFileExistReq) GetFileSize() uint64 {
	if m != nil {
		return m.FileSize
	}
	return 0
}

func (m *CheckFileExistReq) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *CheckFileExistReq) GetFileModTime() uint64 {
	if m != nil {
		return m.FileModTime
	}
	return 0
}

func (m *CheckFileExistReq) GetFileData() []byte {
	if m != nil {
		return m.FileData
	}
	return nil
}

func (m *CheckFileExistReq) GetInteractive() bool {
	if m != nil {
		return m.Interactive
	}
	return false
}

func (m *CheckFileExistReq) GetNewVersion() bool {
	if m != nil {
		return m.NewVersion
	}
	return false
}

func (m *CheckFileExistReq) GetSign() []byte {
	if m != nil {
		return m.Sign
	}
	return nil
}

type CheckFileExistResp struct {
	Code             uint32             `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	ErrMsg           string             `protobuf:"bytes,2,opt,name=errMsg" json:"errMsg,omitempty"`
	StoreType        FileStoreType      `protobuf:"varint,3,opt,name=storeType,enum=metadata.pb.FileStoreType" json:"storeType,omitempty"`
	DataPieceCount   uint32             `protobuf:"varint,4,opt,name=dataPieceCount" json:"dataPieceCount,omitempty"`
	VerifyPieceCount uint32             `protobuf:"varint,5,opt,name=verifyPieceCount" json:"verifyPieceCount,omitempty"`
	ReplicaCount     uint32             `protobuf:"varint,6,opt,name=replicaCount" json:"replicaCount,omitempty"`
	Provider         []*ReplicaProvider `protobuf:"bytes,7,rep,name=provider" json:"provider,omitempty"`
}

func (m *CheckFileExistResp) Reset()                    { *m = CheckFileExistResp{} }
func (m *CheckFileExistResp) String() string            { return proto.CompactTextString(m) }
func (*CheckFileExistResp) ProtoMessage()               {}
func (*CheckFileExistResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *CheckFileExistResp) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *CheckFileExistResp) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *CheckFileExistResp) GetStoreType() FileStoreType {
	if m != nil {
		return m.StoreType
	}
	return FileStoreType_ErasureCode
}

func (m *CheckFileExistResp) GetDataPieceCount() uint32 {
	if m != nil {
		return m.DataPieceCount
	}
	return 0
}

func (m *CheckFileExistResp) GetVerifyPieceCount() uint32 {
	if m != nil {
		return m.VerifyPieceCount
	}
	return 0
}

func (m *CheckFileExistResp) GetReplicaCount() uint32 {
	if m != nil {
		return m.ReplicaCount
	}
	return 0
}

func (m *CheckFileExistResp) GetProvider() []*ReplicaProvider {
	if m != nil {
		return m.Provider
	}
	return nil
}

type ReplicaProvider struct {
	NodeId    []byte `protobuf:"bytes,1,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	Server    string `protobuf:"bytes,2,opt,name=server" json:"server,omitempty"`
	Port      uint32 `protobuf:"varint,3,opt,name=port" json:"port,omitempty"`
	Timestamp uint64 `protobuf:"varint,4,opt,name=timestamp" json:"timestamp,omitempty"`
	Ticket    string `protobuf:"bytes,5,opt,name=ticket" json:"ticket,omitempty"`
	Auth      []byte `protobuf:"bytes,6,opt,name=auth,proto3" json:"auth,omitempty"`
}

func (m *ReplicaProvider) Reset()                    { *m = ReplicaProvider{} }
func (m *ReplicaProvider) String() string            { return proto.CompactTextString(m) }
func (*ReplicaProvider) ProtoMessage()               {}
func (*ReplicaProvider) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ReplicaProvider) GetNodeId() []byte {
	if m != nil {
		return m.NodeId
	}
	return nil
}

func (m *ReplicaProvider) GetServer() string {
	if m != nil {
		return m.Server
	}
	return ""
}

func (m *ReplicaProvider) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *ReplicaProvider) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *ReplicaProvider) GetTicket() string {
	if m != nil {
		return m.Ticket
	}
	return ""
}

func (m *ReplicaProvider) GetAuth() []byte {
	if m != nil {
		return m.Auth
	}
	return nil
}

type UploadFilePrepareReq struct {
	Version   uint32              `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	NodeId    []byte              `protobuf:"bytes,2,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	Timestamp uint64              `protobuf:"varint,3,opt,name=timestamp" json:"timestamp,omitempty"`
	FileHash  []byte              `protobuf:"bytes,4,opt,name=fileHash,proto3" json:"fileHash,omitempty"`
	FileSize  uint64              `protobuf:"varint,5,opt,name=fileSize" json:"fileSize,omitempty"`
	Piece     []*PieceHashAndSize `protobuf:"bytes,6,rep,name=piece" json:"piece,omitempty"`
	Sign      []byte              `protobuf:"bytes,7,opt,name=sign,proto3" json:"sign,omitempty"`
}

func (m *UploadFilePrepareReq) Reset()                    { *m = UploadFilePrepareReq{} }
func (m *UploadFilePrepareReq) String() string            { return proto.CompactTextString(m) }
func (*UploadFilePrepareReq) ProtoMessage()               {}
func (*UploadFilePrepareReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *UploadFilePrepareReq) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *UploadFilePrepareReq) GetNodeId() []byte {
	if m != nil {
		return m.NodeId
	}
	return nil
}

func (m *UploadFilePrepareReq) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *UploadFilePrepareReq) GetFileHash() []byte {
	if m != nil {
		return m.FileHash
	}
	return nil
}

func (m *UploadFilePrepareReq) GetFileSize() uint64 {
	if m != nil {
		return m.FileSize
	}
	return 0
}

func (m *UploadFilePrepareReq) GetPiece() []*PieceHashAndSize {
	if m != nil {
		return m.Piece
	}
	return nil
}

func (m *UploadFilePrepareReq) GetSign() []byte {
	if m != nil {
		return m.Sign
	}
	return nil
}

type PieceHashAndSize struct {
	Hash []byte `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Size uint32 `protobuf:"varint,2,opt,name=size" json:"size,omitempty"`
}

func (m *PieceHashAndSize) Reset()                    { *m = PieceHashAndSize{} }
func (m *PieceHashAndSize) String() string            { return proto.CompactTextString(m) }
func (*PieceHashAndSize) ProtoMessage()               {}
func (*PieceHashAndSize) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *PieceHashAndSize) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *PieceHashAndSize) GetSize() uint32 {
	if m != nil {
		return m.Size
	}
	return 0
}

type UploadFilePrepareResp struct {
	Provider []*ErasureCodeProvider `protobuf:"bytes,1,rep,name=provider" json:"provider,omitempty"`
}

func (m *UploadFilePrepareResp) Reset()                    { *m = UploadFilePrepareResp{} }
func (m *UploadFilePrepareResp) String() string            { return proto.CompactTextString(m) }
func (*UploadFilePrepareResp) ProtoMessage()               {}
func (*UploadFilePrepareResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *UploadFilePrepareResp) GetProvider() []*ErasureCodeProvider {
	if m != nil {
		return m.Provider
	}
	return nil
}

type ErasureCodeProvider struct {
	NodeId    []byte           `protobuf:"bytes,1,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	Server    string           `protobuf:"bytes,2,opt,name=server" json:"server,omitempty"`
	Port      uint32           `protobuf:"varint,3,opt,name=port" json:"port,omitempty"`
	Timestamp uint64           `protobuf:"varint,4,opt,name=timestamp" json:"timestamp,omitempty"`
	HashAuth  []*PieceHashAuth `protobuf:"bytes,5,rep,name=hashAuth" json:"hashAuth,omitempty"`
}

func (m *ErasureCodeProvider) Reset()                    { *m = ErasureCodeProvider{} }
func (m *ErasureCodeProvider) String() string            { return proto.CompactTextString(m) }
func (*ErasureCodeProvider) ProtoMessage()               {}
func (*ErasureCodeProvider) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *ErasureCodeProvider) GetNodeId() []byte {
	if m != nil {
		return m.NodeId
	}
	return nil
}

func (m *ErasureCodeProvider) GetServer() string {
	if m != nil {
		return m.Server
	}
	return ""
}

func (m *ErasureCodeProvider) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *ErasureCodeProvider) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *ErasureCodeProvider) GetHashAuth() []*PieceHashAuth {
	if m != nil {
		return m.HashAuth
	}
	return nil
}

type PieceHashAuth struct {
	Hash   []byte `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Ticket string `protobuf:"bytes,2,opt,name=ticket" json:"ticket,omitempty"`
	Auth   []byte `protobuf:"bytes,3,opt,name=auth,proto3" json:"auth,omitempty"`
}

func (m *PieceHashAuth) Reset()                    { *m = PieceHashAuth{} }
func (m *PieceHashAuth) String() string            { return proto.CompactTextString(m) }
func (*PieceHashAuth) ProtoMessage()               {}
func (*PieceHashAuth) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *PieceHashAuth) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *PieceHashAuth) GetTicket() string {
	if m != nil {
		return m.Ticket
	}
	return ""
}

func (m *PieceHashAuth) GetAuth() []byte {
	if m != nil {
		return m.Auth
	}
	return nil
}

type UploadFileDoneReq struct {
	Version     uint32       `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	NodeId      []byte       `protobuf:"bytes,2,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	Timestamp   uint64       `protobuf:"varint,3,opt,name=timestamp" json:"timestamp,omitempty"`
	FilePath    string       `protobuf:"bytes,4,opt,name=filePath" json:"filePath,omitempty"`
	FileHash    []byte       `protobuf:"bytes,5,opt,name=fileHash,proto3" json:"fileHash,omitempty"`
	FileSize    uint64       `protobuf:"varint,6,opt,name=fileSize" json:"fileSize,omitempty"`
	FileName    string       `protobuf:"bytes,7,opt,name=fileName" json:"fileName,omitempty"`
	FileModTime uint64       `protobuf:"varint,8,opt,name=fileModTime" json:"fileModTime,omitempty"`
	Partition   []*Partition `protobuf:"bytes,9,rep,name=partition" json:"partition,omitempty"`
	Interactive bool         `protobuf:"varint,10,opt,name=interactive" json:"interactive,omitempty"`
	NewVersion  bool         `protobuf:"varint,11,opt,name=newVersion" json:"newVersion,omitempty"`
	Sign        []byte       `protobuf:"bytes,12,opt,name=sign,proto3" json:"sign,omitempty"`
}

func (m *UploadFileDoneReq) Reset()                    { *m = UploadFileDoneReq{} }
func (m *UploadFileDoneReq) String() string            { return proto.CompactTextString(m) }
func (*UploadFileDoneReq) ProtoMessage()               {}
func (*UploadFileDoneReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *UploadFileDoneReq) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *UploadFileDoneReq) GetNodeId() []byte {
	if m != nil {
		return m.NodeId
	}
	return nil
}

func (m *UploadFileDoneReq) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *UploadFileDoneReq) GetFilePath() string {
	if m != nil {
		return m.FilePath
	}
	return ""
}

func (m *UploadFileDoneReq) GetFileHash() []byte {
	if m != nil {
		return m.FileHash
	}
	return nil
}

func (m *UploadFileDoneReq) GetFileSize() uint64 {
	if m != nil {
		return m.FileSize
	}
	return 0
}

func (m *UploadFileDoneReq) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *UploadFileDoneReq) GetFileModTime() uint64 {
	if m != nil {
		return m.FileModTime
	}
	return 0
}

func (m *UploadFileDoneReq) GetPartition() []*Partition {
	if m != nil {
		return m.Partition
	}
	return nil
}

func (m *UploadFileDoneReq) GetInteractive() bool {
	if m != nil {
		return m.Interactive
	}
	return false
}

func (m *UploadFileDoneReq) GetNewVersion() bool {
	if m != nil {
		return m.NewVersion
	}
	return false
}

func (m *UploadFileDoneReq) GetSign() []byte {
	if m != nil {
		return m.Sign
	}
	return nil
}

type Partition struct {
	Block []*Block `protobuf:"bytes,1,rep,name=block" json:"block,omitempty"`
}

func (m *Partition) Reset()                    { *m = Partition{} }
func (m *Partition) String() string            { return proto.CompactTextString(m) }
func (*Partition) ProtoMessage()               {}
func (*Partition) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *Partition) GetBlock() []*Block {
	if m != nil {
		return m.Block
	}
	return nil
}

type Block struct {
	Hash        []byte   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Size        uint32   `protobuf:"varint,2,opt,name=size" json:"size,omitempty"`
	BlockSeq    uint32   `protobuf:"varint,3,opt,name=blockSeq" json:"blockSeq,omitempty"`
	Checksum    bool     `protobuf:"varint,4,opt,name=checksum" json:"checksum,omitempty"`
	StoreNodeId [][]byte `protobuf:"bytes,5,rep,name=storeNodeId,proto3" json:"storeNodeId,omitempty"`
}

func (m *Block) Reset()                    { *m = Block{} }
func (m *Block) String() string            { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()               {}
func (*Block) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *Block) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *Block) GetSize() uint32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Block) GetBlockSeq() uint32 {
	if m != nil {
		return m.BlockSeq
	}
	return 0
}

func (m *Block) GetChecksum() bool {
	if m != nil {
		return m.Checksum
	}
	return false
}

func (m *Block) GetStoreNodeId() [][]byte {
	if m != nil {
		return m.StoreNodeId
	}
	return nil
}

type UploadFileDoneResp struct {
	Code   uint32 `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	ErrMsg string `protobuf:"bytes,2,opt,name=errMsg" json:"errMsg,omitempty"`
}

func (m *UploadFileDoneResp) Reset()                    { *m = UploadFileDoneResp{} }
func (m *UploadFileDoneResp) String() string            { return proto.CompactTextString(m) }
func (*UploadFileDoneResp) ProtoMessage()               {}
func (*UploadFileDoneResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *UploadFileDoneResp) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *UploadFileDoneResp) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

type ListFilesReq struct {
	Version   uint32   `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	NodeId    []byte   `protobuf:"bytes,2,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	Timestamp uint64   `protobuf:"varint,3,opt,name=timestamp" json:"timestamp,omitempty"`
	Path      string   `protobuf:"bytes,4,opt,name=path" json:"path,omitempty"`
	PageSize  uint32   `protobuf:"varint,5,opt,name=pageSize" json:"pageSize,omitempty"`
	PageNum   uint32   `protobuf:"varint,6,opt,name=pageNum" json:"pageNum,omitempty"`
	SortType  SortType `protobuf:"varint,7,opt,name=sortType,enum=metadata.pb.SortType" json:"sortType,omitempty"`
	AscOrder  bool     `protobuf:"varint,8,opt,name=ascOrder" json:"ascOrder,omitempty"`
	Sign      []byte   `protobuf:"bytes,9,opt,name=sign,proto3" json:"sign,omitempty"`
}

func (m *ListFilesReq) Reset()                    { *m = ListFilesReq{} }
func (m *ListFilesReq) String() string            { return proto.CompactTextString(m) }
func (*ListFilesReq) ProtoMessage()               {}
func (*ListFilesReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *ListFilesReq) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *ListFilesReq) GetNodeId() []byte {
	if m != nil {
		return m.NodeId
	}
	return nil
}

func (m *ListFilesReq) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *ListFilesReq) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *ListFilesReq) GetPageSize() uint32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListFilesReq) GetPageNum() uint32 {
	if m != nil {
		return m.PageNum
	}
	return 0
}

func (m *ListFilesReq) GetSortType() SortType {
	if m != nil {
		return m.SortType
	}
	return SortType_Name
}

func (m *ListFilesReq) GetAscOrder() bool {
	if m != nil {
		return m.AscOrder
	}
	return false
}

func (m *ListFilesReq) GetSign() []byte {
	if m != nil {
		return m.Sign
	}
	return nil
}

type ListFilesResp struct {
	Code        uint32          `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	ErrMsg      string          `protobuf:"bytes,2,opt,name=errMsg" json:"errMsg,omitempty"`
	TotalRecord uint32          `protobuf:"varint,3,opt,name=totalRecord" json:"totalRecord,omitempty"`
	Fof         []*FileOrFolder `protobuf:"bytes,4,rep,name=fof" json:"fof,omitempty"`
}

func (m *ListFilesResp) Reset()                    { *m = ListFilesResp{} }
func (m *ListFilesResp) String() string            { return proto.CompactTextString(m) }
func (*ListFilesResp) ProtoMessage()               {}
func (*ListFilesResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *ListFilesResp) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ListFilesResp) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *ListFilesResp) GetTotalRecord() uint32 {
	if m != nil {
		return m.TotalRecord
	}
	return 0
}

func (m *ListFilesResp) GetFof() []*FileOrFolder {
	if m != nil {
		return m.Fof
	}
	return nil
}

type FileOrFolder struct {
	Folder   bool   `protobuf:"varint,1,opt,name=folder" json:"folder,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	ModTime  uint64 `protobuf:"varint,3,opt,name=modTime" json:"modTime,omitempty"`
	FileHash []byte `protobuf:"bytes,4,opt,name=fileHash,proto3" json:"fileHash,omitempty"`
	FileSize uint64 `protobuf:"varint,5,opt,name=fileSize" json:"fileSize,omitempty"`
}

func (m *FileOrFolder) Reset()                    { *m = FileOrFolder{} }
func (m *FileOrFolder) String() string            { return proto.CompactTextString(m) }
func (*FileOrFolder) ProtoMessage()               {}
func (*FileOrFolder) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *FileOrFolder) GetFolder() bool {
	if m != nil {
		return m.Folder
	}
	return false
}

func (m *FileOrFolder) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FileOrFolder) GetModTime() uint64 {
	if m != nil {
		return m.ModTime
	}
	return 0
}

func (m *FileOrFolder) GetFileHash() []byte {
	if m != nil {
		return m.FileHash
	}
	return nil
}

func (m *FileOrFolder) GetFileSize() uint64 {
	if m != nil {
		return m.FileSize
	}
	return 0
}

type RetrieveFileReq struct {
	Version   uint32 `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	NodeId    []byte `protobuf:"bytes,2,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	Timestamp uint64 `protobuf:"varint,3,opt,name=timestamp" json:"timestamp,omitempty"`
	FileHash  []byte `protobuf:"bytes,4,opt,name=fileHash,proto3" json:"fileHash,omitempty"`
	FileSize  uint64 `protobuf:"varint,5,opt,name=fileSize" json:"fileSize,omitempty"`
	Sign      []byte `protobuf:"bytes,6,opt,name=sign,proto3" json:"sign,omitempty"`
}

func (m *RetrieveFileReq) Reset()                    { *m = RetrieveFileReq{} }
func (m *RetrieveFileReq) String() string            { return proto.CompactTextString(m) }
func (*RetrieveFileReq) ProtoMessage()               {}
func (*RetrieveFileReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *RetrieveFileReq) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *RetrieveFileReq) GetNodeId() []byte {
	if m != nil {
		return m.NodeId
	}
	return nil
}

func (m *RetrieveFileReq) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *RetrieveFileReq) GetFileHash() []byte {
	if m != nil {
		return m.FileHash
	}
	return nil
}

func (m *RetrieveFileReq) GetFileSize() uint64 {
	if m != nil {
		return m.FileSize
	}
	return 0
}

func (m *RetrieveFileReq) GetSign() []byte {
	if m != nil {
		return m.Sign
	}
	return nil
}

type RetrieveFileResp struct {
	Code      uint32               `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	ErrMsg    string               `protobuf:"bytes,2,opt,name=errMsg" json:"errMsg,omitempty"`
	FileData  []byte               `protobuf:"bytes,3,opt,name=fileData,proto3" json:"fileData,omitempty"`
	Partition []*RetrievePartition `protobuf:"bytes,4,rep,name=partition" json:"partition,omitempty"`
	Timestamp uint64               `protobuf:"varint,5,opt,name=timestamp" json:"timestamp,omitempty"`
}

func (m *RetrieveFileResp) Reset()                    { *m = RetrieveFileResp{} }
func (m *RetrieveFileResp) String() string            { return proto.CompactTextString(m) }
func (*RetrieveFileResp) ProtoMessage()               {}
func (*RetrieveFileResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *RetrieveFileResp) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *RetrieveFileResp) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *RetrieveFileResp) GetFileData() []byte {
	if m != nil {
		return m.FileData
	}
	return nil
}

func (m *RetrieveFileResp) GetPartition() []*RetrievePartition {
	if m != nil {
		return m.Partition
	}
	return nil
}

func (m *RetrieveFileResp) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type RetrievePartition struct {
	Block []*RetrieveBlock `protobuf:"bytes,1,rep,name=block" json:"block,omitempty"`
}

func (m *RetrievePartition) Reset()                    { *m = RetrievePartition{} }
func (m *RetrievePartition) String() string            { return proto.CompactTextString(m) }
func (*RetrievePartition) ProtoMessage()               {}
func (*RetrievePartition) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *RetrievePartition) GetBlock() []*RetrieveBlock {
	if m != nil {
		return m.Block
	}
	return nil
}

type RetrieveBlock struct {
	Hash      []byte          `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Size      uint32          `protobuf:"varint,2,opt,name=size" json:"size,omitempty"`
	BlockSeq  uint32          `protobuf:"varint,3,opt,name=blockSeq" json:"blockSeq,omitempty"`
	Checksum  bool            `protobuf:"varint,4,opt,name=checksum" json:"checksum,omitempty"`
	StoreNode []*RetrieveNode `protobuf:"bytes,5,rep,name=storeNode" json:"storeNode,omitempty"`
}

func (m *RetrieveBlock) Reset()                    { *m = RetrieveBlock{} }
func (m *RetrieveBlock) String() string            { return proto.CompactTextString(m) }
func (*RetrieveBlock) ProtoMessage()               {}
func (*RetrieveBlock) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *RetrieveBlock) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *RetrieveBlock) GetSize() uint32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *RetrieveBlock) GetBlockSeq() uint32 {
	if m != nil {
		return m.BlockSeq
	}
	return 0
}

func (m *RetrieveBlock) GetChecksum() bool {
	if m != nil {
		return m.Checksum
	}
	return false
}

func (m *RetrieveBlock) GetStoreNode() []*RetrieveNode {
	if m != nil {
		return m.StoreNode
	}
	return nil
}

type RetrieveNode struct {
	NodeId []byte `protobuf:"bytes,1,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	Server string `protobuf:"bytes,2,opt,name=server" json:"server,omitempty"`
	Port   uint32 `protobuf:"varint,3,opt,name=port" json:"port,omitempty"`
	Ticket string `protobuf:"bytes,4,opt,name=ticket" json:"ticket,omitempty"`
	Auth   []byte `protobuf:"bytes,5,opt,name=auth,proto3" json:"auth,omitempty"`
}

func (m *RetrieveNode) Reset()                    { *m = RetrieveNode{} }
func (m *RetrieveNode) String() string            { return proto.CompactTextString(m) }
func (*RetrieveNode) ProtoMessage()               {}
func (*RetrieveNode) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *RetrieveNode) GetNodeId() []byte {
	if m != nil {
		return m.NodeId
	}
	return nil
}

func (m *RetrieveNode) GetServer() string {
	if m != nil {
		return m.Server
	}
	return ""
}

func (m *RetrieveNode) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *RetrieveNode) GetTicket() string {
	if m != nil {
		return m.Ticket
	}
	return ""
}

func (m *RetrieveNode) GetAuth() []byte {
	if m != nil {
		return m.Auth
	}
	return nil
}

type RemoveReq struct {
	Version   uint32 `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	NodeId    []byte `protobuf:"bytes,2,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	Timestamp uint64 `protobuf:"varint,3,opt,name=timestamp" json:"timestamp,omitempty"`
	Path      string `protobuf:"bytes,4,opt,name=path" json:"path,omitempty"`
	Recursive bool   `protobuf:"varint,5,opt,name=recursive" json:"recursive,omitempty"`
	Sign      []byte `protobuf:"bytes,6,opt,name=sign,proto3" json:"sign,omitempty"`
}

func (m *RemoveReq) Reset()                    { *m = RemoveReq{} }
func (m *RemoveReq) String() string            { return proto.CompactTextString(m) }
func (*RemoveReq) ProtoMessage()               {}
func (*RemoveReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *RemoveReq) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *RemoveReq) GetNodeId() []byte {
	if m != nil {
		return m.NodeId
	}
	return nil
}

func (m *RemoveReq) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *RemoveReq) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *RemoveReq) GetRecursive() bool {
	if m != nil {
		return m.Recursive
	}
	return false
}

func (m *RemoveReq) GetSign() []byte {
	if m != nil {
		return m.Sign
	}
	return nil
}

type RemoveResp struct {
	Code   uint32 `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	ErrMsg string `protobuf:"bytes,2,opt,name=errMsg" json:"errMsg,omitempty"`
}

func (m *RemoveResp) Reset()                    { *m = RemoveResp{} }
func (m *RemoveResp) String() string            { return proto.CompactTextString(m) }
func (*RemoveResp) ProtoMessage()               {}
func (*RemoveResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *RemoveResp) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *RemoveResp) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func init() {
	proto.RegisterType((*MkFolderReq)(nil), "metadata.pb.MkFolderReq")
	proto.RegisterType((*MkFolderResp)(nil), "metadata.pb.MkFolderResp")
	proto.RegisterType((*CheckFileExistReq)(nil), "metadata.pb.CheckFileExistReq")
	proto.RegisterType((*CheckFileExistResp)(nil), "metadata.pb.CheckFileExistResp")
	proto.RegisterType((*ReplicaProvider)(nil), "metadata.pb.ReplicaProvider")
	proto.RegisterType((*UploadFilePrepareReq)(nil), "metadata.pb.UploadFilePrepareReq")
	proto.RegisterType((*PieceHashAndSize)(nil), "metadata.pb.PieceHashAndSize")
	proto.RegisterType((*UploadFilePrepareResp)(nil), "metadata.pb.UploadFilePrepareResp")
	proto.RegisterType((*ErasureCodeProvider)(nil), "metadata.pb.ErasureCodeProvider")
	proto.RegisterType((*PieceHashAuth)(nil), "metadata.pb.PieceHashAuth")
	proto.RegisterType((*UploadFileDoneReq)(nil), "metadata.pb.UploadFileDoneReq")
	proto.RegisterType((*Partition)(nil), "metadata.pb.Partition")
	proto.RegisterType((*Block)(nil), "metadata.pb.Block")
	proto.RegisterType((*UploadFileDoneResp)(nil), "metadata.pb.UploadFileDoneResp")
	proto.RegisterType((*ListFilesReq)(nil), "metadata.pb.ListFilesReq")
	proto.RegisterType((*ListFilesResp)(nil), "metadata.pb.ListFilesResp")
	proto.RegisterType((*FileOrFolder)(nil), "metadata.pb.FileOrFolder")
	proto.RegisterType((*RetrieveFileReq)(nil), "metadata.pb.RetrieveFileReq")
	proto.RegisterType((*RetrieveFileResp)(nil), "metadata.pb.RetrieveFileResp")
	proto.RegisterType((*RetrievePartition)(nil), "metadata.pb.RetrievePartition")
	proto.RegisterType((*RetrieveBlock)(nil), "metadata.pb.RetrieveBlock")
	proto.RegisterType((*RetrieveNode)(nil), "metadata.pb.RetrieveNode")
	proto.RegisterType((*RemoveReq)(nil), "metadata.pb.RemoveReq")
	proto.RegisterType((*RemoveResp)(nil), "metadata.pb.RemoveResp")
	proto.RegisterEnum("metadata.pb.FileStoreType", FileStoreType_name, FileStoreType_value)
	proto.RegisterEnum("metadata.pb.SortType", SortType_name, SortType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for MatadataService service

type MatadataServiceClient interface {
	MkFolder(ctx context.Context, in *MkFolderReq, opts ...grpc.CallOption) (*MkFolderResp, error)
	CheckFileExist(ctx context.Context, in *CheckFileExistReq, opts ...grpc.CallOption) (*CheckFileExistResp, error)
	UploadFilePrepare(ctx context.Context, in *UploadFilePrepareReq, opts ...grpc.CallOption) (*UploadFilePrepareResp, error)
	UploadFileDone(ctx context.Context, in *UploadFileDoneReq, opts ...grpc.CallOption) (*UploadFileDoneResp, error)
	ListFiles(ctx context.Context, in *ListFilesReq, opts ...grpc.CallOption) (*ListFilesResp, error)
	RetrieveFile(ctx context.Context, in *RetrieveFileReq, opts ...grpc.CallOption) (*RetrieveFileResp, error)
	Remove(ctx context.Context, in *RemoveReq, opts ...grpc.CallOption) (*RemoveResp, error)
}

type matadataServiceClient struct {
	cc *grpc.ClientConn
}

func NewMatadataServiceClient(cc *grpc.ClientConn) MatadataServiceClient {
	return &matadataServiceClient{cc}
}

func (c *matadataServiceClient) MkFolder(ctx context.Context, in *MkFolderReq, opts ...grpc.CallOption) (*MkFolderResp, error) {
	out := new(MkFolderResp)
	err := grpc.Invoke(ctx, "/metadata.pb.MatadataService/MkFolder", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matadataServiceClient) CheckFileExist(ctx context.Context, in *CheckFileExistReq, opts ...grpc.CallOption) (*CheckFileExistResp, error) {
	out := new(CheckFileExistResp)
	err := grpc.Invoke(ctx, "/metadata.pb.MatadataService/CheckFileExist", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matadataServiceClient) UploadFilePrepare(ctx context.Context, in *UploadFilePrepareReq, opts ...grpc.CallOption) (*UploadFilePrepareResp, error) {
	out := new(UploadFilePrepareResp)
	err := grpc.Invoke(ctx, "/metadata.pb.MatadataService/UploadFilePrepare", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matadataServiceClient) UploadFileDone(ctx context.Context, in *UploadFileDoneReq, opts ...grpc.CallOption) (*UploadFileDoneResp, error) {
	out := new(UploadFileDoneResp)
	err := grpc.Invoke(ctx, "/metadata.pb.MatadataService/UploadFileDone", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matadataServiceClient) ListFiles(ctx context.Context, in *ListFilesReq, opts ...grpc.CallOption) (*ListFilesResp, error) {
	out := new(ListFilesResp)
	err := grpc.Invoke(ctx, "/metadata.pb.MatadataService/ListFiles", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matadataServiceClient) RetrieveFile(ctx context.Context, in *RetrieveFileReq, opts ...grpc.CallOption) (*RetrieveFileResp, error) {
	out := new(RetrieveFileResp)
	err := grpc.Invoke(ctx, "/metadata.pb.MatadataService/RetrieveFile", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matadataServiceClient) Remove(ctx context.Context, in *RemoveReq, opts ...grpc.CallOption) (*RemoveResp, error) {
	out := new(RemoveResp)
	err := grpc.Invoke(ctx, "/metadata.pb.MatadataService/Remove", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for MatadataService service

type MatadataServiceServer interface {
	MkFolder(context.Context, *MkFolderReq) (*MkFolderResp, error)
	CheckFileExist(context.Context, *CheckFileExistReq) (*CheckFileExistResp, error)
	UploadFilePrepare(context.Context, *UploadFilePrepareReq) (*UploadFilePrepareResp, error)
	UploadFileDone(context.Context, *UploadFileDoneReq) (*UploadFileDoneResp, error)
	ListFiles(context.Context, *ListFilesReq) (*ListFilesResp, error)
	RetrieveFile(context.Context, *RetrieveFileReq) (*RetrieveFileResp, error)
	Remove(context.Context, *RemoveReq) (*RemoveResp, error)
}

func RegisterMatadataServiceServer(s *grpc.Server, srv MatadataServiceServer) {
	s.RegisterService(&_MatadataService_serviceDesc, srv)
}

func _MatadataService_MkFolder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MkFolderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatadataServiceServer).MkFolder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metadata.pb.MatadataService/MkFolder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatadataServiceServer).MkFolder(ctx, req.(*MkFolderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatadataService_CheckFileExist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckFileExistReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatadataServiceServer).CheckFileExist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metadata.pb.MatadataService/CheckFileExist",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatadataServiceServer).CheckFileExist(ctx, req.(*CheckFileExistReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatadataService_UploadFilePrepare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadFilePrepareReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatadataServiceServer).UploadFilePrepare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metadata.pb.MatadataService/UploadFilePrepare",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatadataServiceServer).UploadFilePrepare(ctx, req.(*UploadFilePrepareReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatadataService_UploadFileDone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadFileDoneReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatadataServiceServer).UploadFileDone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metadata.pb.MatadataService/UploadFileDone",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatadataServiceServer).UploadFileDone(ctx, req.(*UploadFileDoneReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatadataService_ListFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFilesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatadataServiceServer).ListFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metadata.pb.MatadataService/ListFiles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatadataServiceServer).ListFiles(ctx, req.(*ListFilesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatadataService_RetrieveFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveFileReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatadataServiceServer).RetrieveFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metadata.pb.MatadataService/RetrieveFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatadataServiceServer).RetrieveFile(ctx, req.(*RetrieveFileReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatadataService_Remove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatadataServiceServer).Remove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metadata.pb.MatadataService/Remove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatadataServiceServer).Remove(ctx, req.(*RemoveReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _MatadataService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "metadata.pb.MatadataService",
	HandlerType: (*MatadataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MkFolder",
			Handler:    _MatadataService_MkFolder_Handler,
		},
		{
			MethodName: "CheckFileExist",
			Handler:    _MatadataService_CheckFileExist_Handler,
		},
		{
			MethodName: "UploadFilePrepare",
			Handler:    _MatadataService_UploadFilePrepare_Handler,
		},
		{
			MethodName: "UploadFileDone",
			Handler:    _MatadataService_UploadFileDone_Handler,
		},
		{
			MethodName: "ListFiles",
			Handler:    _MatadataService_ListFiles_Handler,
		},
		{
			MethodName: "RetrieveFile",
			Handler:    _MatadataService_RetrieveFile_Handler,
		},
		{
			MethodName: "Remove",
			Handler:    _MatadataService_Remove_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "metadata.proto",
}

func init() { proto.RegisterFile("metadata.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1245 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe4, 0x58, 0xcd, 0x6f, 0xe3, 0x44,
	0x14, 0xaf, 0x93, 0x38, 0xb1, 0x5f, 0x92, 0x36, 0x1d, 0xd8, 0xe2, 0x5a, 0xdd, 0x25, 0xf8, 0x80,
	0xa2, 0xae, 0x54, 0x41, 0x97, 0x8f, 0x0a, 0xf6, 0x40, 0x69, 0xbb, 0x02, 0x89, 0xb4, 0xd5, 0x64,
	0x97, 0x13, 0x17, 0xd7, 0x99, 0x36, 0x56, 0x93, 0xd8, 0x3b, 0x9e, 0x04, 0x76, 0x0f, 0x48, 0x1c,
	0xf9, 0xf8, 0x17, 0x10, 0xe2, 0xc6, 0x81, 0x8f, 0x1b, 0xff, 0xd2, 0xfe, 0x1b, 0x68, 0xc6, 0x5f,
	0x33, 0x8e, 0x5b, 0x08, 0xa2, 0x15, 0xd2, 0xde, 0xe6, 0xbd, 0xf7, 0x9b, 0x99, 0x37, 0xef, 0xdb,
	0x86, 0xd5, 0x09, 0x61, 0xee, 0xd0, 0x65, 0xee, 0x4e, 0x48, 0x03, 0x16, 0xa0, 0x66, 0x4e, 0x9f,
	0x39, 0x3f, 0x6a, 0xd0, 0xec, 0x5f, 0x3e, 0x0a, 0xc6, 0x43, 0x42, 0x31, 0x79, 0x8a, 0x2c, 0x68,
	0xcc, 0x09, 0x8d, 0xfc, 0x60, 0x6a, 0x69, 0x5d, 0xad, 0xd7, 0xc6, 0x29, 0x89, 0x36, 0xa0, 0x3e,
	0x0d, 0x86, 0xe4, 0xd3, 0xa1, 0x55, 0xe9, 0x6a, 0xbd, 0x16, 0x4e, 0x28, 0xb4, 0x05, 0x26, 0xf3,
	0x27, 0x24, 0x62, 0xee, 0x24, 0xb4, 0xaa, 0x5d, 0xad, 0x57, 0xc3, 0x39, 0x03, 0x21, 0xa8, 0x85,
	0x2e, 0x1b, 0x59, 0xb5, 0xae, 0xd6, 0x33, 0xb1, 0x58, 0xf3, 0x93, 0xce, 0xc5, 0x85, 0x96, 0xde,
	0xad, 0xf6, 0x4c, 0x9c, 0x50, 0x1c, 0x1b, 0xf9, 0x17, 0x53, 0xab, 0x2e, 0xce, 0x17, 0x6b, 0xe7,
	0x03, 0x68, 0xe5, 0xea, 0x45, 0xe2, 0x3c, 0x2f, 0x18, 0x92, 0x44, 0x39, 0xb1, 0xe6, 0xe7, 0x11,
	0x4a, 0xfb, 0xd1, 0x85, 0xd0, 0xcc, 0xc4, 0x09, 0xe5, 0xbc, 0xa8, 0xc0, 0xfa, 0xc1, 0x88, 0x78,
	0x97, 0x8f, 0xfc, 0x31, 0x39, 0xfa, 0xca, 0x8f, 0xd8, 0x4d, 0xbc, 0xd0, 0x06, 0xe3, 0xdc, 0x1f,
	0x93, 0xd3, 0xfc, 0x95, 0x19, 0x9d, 0xca, 0x3e, 0x71, 0xa3, 0x91, 0xa5, 0x8b, 0x33, 0x33, 0x3a,
	0x95, 0x0d, 0xfc, 0xe7, 0x44, 0xbc, 0xb8, 0x86, 0x33, 0x3a, 0x95, 0x1d, 0xbb, 0x13, 0x62, 0x35,
	0xf2, 0x33, 0x39, 0x8d, 0xba, 0xd0, 0xe4, 0xeb, 0x7e, 0x30, 0x7c, 0xec, 0x4f, 0x88, 0x65, 0x88,
	0xad, 0x32, 0x2b, 0xdd, 0x7d, 0xe8, 0x32, 0xd7, 0x32, 0xf3, 0x5b, 0x39, 0xcd, 0x77, 0xfb, 0x53,
	0x46, 0xa8, 0xeb, 0x31, 0x7f, 0x4e, 0x2c, 0xe8, 0x6a, 0x3d, 0x03, 0xcb, 0x2c, 0x74, 0x0f, 0x60,
	0x4a, 0xbe, 0xfc, 0x3c, 0x31, 0x51, 0x53, 0x00, 0x24, 0x4e, 0xe6, 0xa5, 0x96, 0xe4, 0xa5, 0x5f,
	0x2b, 0x80, 0x8a, 0x96, 0x5e, 0xce, 0x59, 0x68, 0x0f, 0xcc, 0x88, 0x05, 0x94, 0x3c, 0x7e, 0x16,
	0x12, 0x61, 0xe4, 0xd5, 0x5d, 0x7b, 0x47, 0x8a, 0xd4, 0x1d, 0x7e, 0xf4, 0x20, 0x45, 0xe0, 0x1c,
	0x8c, 0xde, 0x84, 0x55, 0x8e, 0x39, 0xf5, 0x89, 0x47, 0x0e, 0x82, 0xd9, 0x94, 0x09, 0x37, 0xb4,
	0x71, 0x81, 0x8b, 0xb6, 0xa1, 0x33, 0x27, 0xd4, 0x3f, 0x7f, 0x26, 0x21, 0x75, 0x81, 0x5c, 0xe0,
	0x23, 0x07, 0x5a, 0x94, 0x84, 0x63, 0xdf, 0x73, 0x63, 0x5c, 0x5d, 0xe0, 0x14, 0x1e, 0xda, 0x03,
	0x23, 0xa4, 0xc1, 0xdc, 0xe7, 0x81, 0xdc, 0xe8, 0x56, 0x7b, 0xcd, 0xdd, 0x2d, 0x45, 0x61, 0x1c,
	0x83, 0x4f, 0x13, 0x0c, 0xce, 0xd0, 0xce, 0x4f, 0x1a, 0xac, 0x15, 0xa4, 0x52, 0xf0, 0x69, 0x4a,
	0xf0, 0x6d, 0x40, 0x3d, 0x22, 0x74, 0x4e, 0x68, 0x6a, 0xaf, 0x98, 0x12, 0x89, 0x15, 0x50, 0x26,
	0x4c, 0xd5, 0xc6, 0x62, 0xad, 0x06, 0x6a, 0xad, 0x18, 0xa8, 0x1b, 0x50, 0x67, 0xbe, 0x77, 0x49,
	0xe2, 0x57, 0x9b, 0x38, 0xa1, 0xf8, 0x49, 0xee, 0x8c, 0x8d, 0xd2, 0xb4, 0xe3, 0x6b, 0xe7, 0x85,
	0x06, 0xaf, 0x3e, 0x09, 0xc7, 0x81, 0x3b, 0xe4, 0x66, 0x3f, 0xa5, 0x24, 0x74, 0x29, 0xb9, 0xc1,
	0xec, 0x11, 0x19, 0x52, 0xbb, 0x26, 0x43, 0xf4, 0x42, 0x86, 0x3c, 0x00, 0x3d, 0xe4, 0xee, 0xb2,
	0xea, 0xc2, 0xf2, 0x77, 0x15, 0xcb, 0x0b, 0x47, 0xf2, 0x23, 0xf6, 0xa7, 0x43, 0x8e, 0xc6, 0x31,
	0x36, 0x0b, 0xdd, 0x86, 0x52, 0x60, 0x3a, 0x45, 0x38, 0xc7, 0x8d, 0xb8, 0x42, 0xb1, 0x27, 0xc4,
	0x3a, 0xde, 0xfb, 0x9c, 0x88, 0xc7, 0xb5, 0xb1, 0x58, 0x3b, 0x4f, 0xe0, 0x4e, 0x89, 0x91, 0xa2,
	0x10, 0x3d, 0x94, 0x42, 0x43, 0x13, 0x0a, 0x76, 0x15, 0x05, 0x8f, 0xa8, 0x1b, 0xcd, 0x28, 0x39,
	0x08, 0x86, 0xa4, 0x24, 0x3c, 0xfe, 0xd0, 0xe0, 0x95, 0x12, 0xc4, 0x2d, 0x84, 0xc8, 0x7b, 0x60,
	0xf0, 0xc7, 0xee, 0xf3, 0x70, 0xd0, 0x85, 0xde, 0xf6, 0x15, 0x86, 0x9d, 0xb1, 0x11, 0xce, 0xb0,
	0xce, 0x09, 0xb4, 0x15, 0x51, 0xa9, 0x05, 0xf3, 0xf8, 0xab, 0x94, 0xc6, 0x5f, 0x55, 0x8a, 0xbf,
	0x6f, 0xaa, 0xb0, 0x9e, 0x9b, 0xf6, 0x30, 0x98, 0x92, 0x97, 0xa3, 0x74, 0xbf, 0x03, 0x66, 0xe8,
	0x52, 0xe6, 0x33, 0xfe, 0x46, 0x53, 0x78, 0x60, 0x43, 0xf5, 0x40, 0x2a, 0xc5, 0x39, 0xf0, 0x86,
	0x8a, 0xfa, 0xbb, 0x60, 0x66, 0xb7, 0xa1, 0x1e, 0xe8, 0x67, 0xe3, 0xc0, 0xbb, 0x4c, 0xc2, 0x19,
	0x29, 0x4a, 0x7d, 0xcc, 0x25, 0x38, 0x06, 0x38, 0xdf, 0x6a, 0xa0, 0x0b, 0xc6, 0x3f, 0x4d, 0x23,
	0x6e, 0x32, 0xb1, 0x75, 0x40, 0x9e, 0x26, 0xb1, 0x9a, 0xd1, 0x5c, 0xe6, 0xf1, 0xc6, 0x12, 0xcd,
	0x26, 0xc2, 0x45, 0x06, 0xce, 0x68, 0xfe, 0x6c, 0xd1, 0x05, 0x8e, 0x63, 0xcf, 0xf3, 0x80, 0x6d,
	0x61, 0x99, 0xe5, 0x7c, 0x04, 0xa8, 0x18, 0x45, 0x4b, 0xce, 0x10, 0xdf, 0x57, 0xa0, 0xf5, 0x99,
	0x1f, 0x31, 0x7e, 0x40, 0x74, 0x5b, 0x03, 0x92, 0x0d, 0x46, 0xe8, 0x5e, 0xe4, 0x85, 0xaf, 0x8d,
	0x33, 0x9a, 0xdf, 0xcf, 0xd7, 0xc7, 0xb3, 0x49, 0xd2, 0x94, 0x52, 0x12, 0xbd, 0x0d, 0x46, 0x14,
	0x50, 0x26, 0x1a, 0x68, 0x43, 0x34, 0xd0, 0x3b, 0x8a, 0x97, 0x06, 0x89, 0x10, 0x67, 0x30, 0x7e,
	0x91, 0x1b, 0x79, 0x27, 0x94, 0xd7, 0x29, 0x23, 0xb6, 0x6e, 0x4a, 0x67, 0x21, 0x61, 0x4a, 0x21,
	0xf1, 0x9d, 0x06, 0x6d, 0xc9, 0x1a, 0x4b, 0xb6, 0xf8, 0x2e, 0x34, 0x59, 0xc0, 0xdc, 0x31, 0x26,
	0x5e, 0x40, 0x87, 0x89, 0xab, 0x65, 0x16, 0xba, 0x0f, 0xd5, 0xf3, 0xe0, 0xdc, 0xaa, 0x89, 0x18,
	0xdb, 0x5c, 0x68, 0xff, 0x27, 0x34, 0x99, 0x04, 0x39, 0xca, 0xf9, 0x41, 0x83, 0x96, 0xcc, 0x95,
	0xe6, 0x4a, 0x4d, 0xbc, 0x45, 0x9a, 0x2b, 0xa7, 0x3c, 0x1d, 0x63, 0x6d, 0xc4, 0x9a, 0x9b, 0x71,
	0x92, 0xa4, 0x61, 0xec, 0x92, 0x94, 0xfc, 0xb7, 0x1d, 0xc9, 0xf9, 0x4d, 0x34, 0x75, 0x46, 0x7d,
	0x32, 0x27, 0x5c, 0xad, 0xff, 0x53, 0xb7, 0x2c, 0x9b, 0xac, 0xff, 0xd4, 0xa0, 0xa3, 0xea, 0xbb,
	0xa4, 0x3b, 0xe5, 0x31, 0xb3, 0x5a, 0x18, 0x33, 0x1f, 0xca, 0x75, 0x2c, 0x76, 0xe7, 0xbd, 0xc2,
	0x70, 0x14, 0xdf, 0x5c, 0x5a, 0xcf, 0x14, 0x23, 0xe8, 0x05, 0x23, 0x38, 0x47, 0xb0, 0xbe, 0xb0,
	0x1b, 0xbd, 0xa5, 0xd6, 0x27, 0xbb, 0xf4, 0x32, 0xa5, 0x4e, 0xfd, 0xa2, 0x41, 0x5b, 0x11, 0xdc,
	0x78, 0xbd, 0x7a, 0x3f, 0x19, 0x71, 0x79, 0x71, 0x4a, 0xda, 0xeb, 0x66, 0xa9, 0x9e, 0x1c, 0x80,
	0x73, 0xac, 0xf3, 0x35, 0xb4, 0x64, 0xd1, 0x7f, 0x32, 0x08, 0xe4, 0xdd, 0xb8, 0x56, 0xda, 0x8d,
	0x75, 0xa9, 0x1b, 0xff, 0xac, 0x81, 0x89, 0xc9, 0x24, 0x98, 0x93, 0xdb, 0xaa, 0x80, 0x5b, 0x60,
	0x52, 0xe2, 0xcd, 0x68, 0xc4, 0xfb, 0x99, 0x2e, 0xec, 0x98, 0x33, 0x4a, 0xc3, 0x79, 0x0f, 0x20,
	0x55, 0x71, 0xb9, 0x38, 0xde, 0xde, 0x85, 0xb6, 0xf2, 0x6d, 0x81, 0xd6, 0xa0, 0x29, 0x8d, 0x5f,
	0x9d, 0x15, 0xd4, 0x81, 0x56, 0x7f, 0x36, 0x66, 0x7e, 0x32, 0xb3, 0x77, 0xb4, 0xed, 0xfb, 0x60,
	0xa4, 0xe5, 0x14, 0x19, 0x50, 0xe3, 0xdd, 0xbd, 0xb3, 0x82, 0x9a, 0xd0, 0x48, 0x1a, 0x79, 0x47,
	0xe3, 0x6c, 0x9e, 0x7b, 0x9d, 0xca, 0xee, 0xef, 0x35, 0x58, 0xeb, 0xbb, 0xb1, 0x9b, 0x07, 0x84,
	0xce, 0x7d, 0x8f, 0xa0, 0x7d, 0x30, 0xd2, 0xef, 0x5a, 0x64, 0x29, 0x41, 0x20, 0x7d, 0x8d, 0xdb,
	0x9b, 0x57, 0x48, 0xa2, 0xd0, 0x59, 0x41, 0x03, 0x58, 0x55, 0xbf, 0xb9, 0x90, 0x9a, 0x62, 0x0b,
	0x9f, 0xbe, 0xf6, 0xeb, 0xd7, 0xca, 0xc5, 0xa1, 0x5f, 0xc8, 0x73, 0x57, 0x32, 0xd2, 0xa2, 0x37,
	0x94, 0x7d, 0x65, 0xdf, 0x05, 0xb6, 0xf3, 0x77, 0x90, 0x54, 0x65, 0xb5, 0x1f, 0x17, 0x54, 0x5e,
	0x18, 0xf9, 0x0a, 0x2a, 0x2f, 0x36, 0x73, 0x67, 0x05, 0x1d, 0x82, 0x99, 0xf5, 0x24, 0xa4, 0x5a,
	0x4c, 0xee, 0xdc, 0xb6, 0x7d, 0x95, 0x48, 0x9c, 0xd2, 0xcf, 0x73, 0x8c, 0xb3, 0xd1, 0x56, 0x69,
	0x66, 0x26, 0x85, 0xdd, 0xbe, 0x7b, 0x8d, 0x54, 0x1c, 0xf7, 0x21, 0xd4, 0xe3, 0x70, 0x44, 0x1b,
	0x05, 0x68, 0x92, 0x46, 0xf6, 0x6b, 0xa5, 0x7c, 0xbe, 0xf9, 0xac, 0x2e, 0x7e, 0xd4, 0x3c, 0xf8,
	0x2b, 0x00, 0x00, 0xff, 0xff, 0x16, 0x60, 0x4d, 0x9d, 0xba, 0x11, 0x00, 0x00,
}
