// Code generated by protoc-gen-go. DO NOT EDIT.
// source: metadata.proto

/*
Package metadata_pb is a generated protocol buffer package.

It is generated from these files:
	metadata.proto

It has these top-level messages:
	GetPublicKeyReq
	GetPublicKeyResp
	MkFolderReq
	FilePath
	MkFolderResp
	CheckFileExistReq
	CheckFileExistResp
	ReplicaProvider
	UploadFilePrepareReq
	SplitPartition
	PieceHashAndSize
	UploadFilePrepareResp
	ErasureCodePartition
	BlockProviderAuth
	PieceHashAuth
	UploadFileDoneReq
	StorePartition
	StoreBlock
	UploadFileDoneResp
	ListFilesReq
	ListFilesResp
	FileOrFolder
	RetrieveFileReq
	RetrieveFileResp
	RetrievePartition
	RetrieveBlock
	RetrieveNode
	RemoveReq
	RemoveResp
	MoveReq
	MoveResp
*/
package metadata_pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FileStoreType int32

const (
	FileStoreType_ErasureCode  FileStoreType = 0
	FileStoreType_MultiReplica FileStoreType = 1
)

var FileStoreType_name = map[int32]string{
	0: "ErasureCode",
	1: "MultiReplica",
}
var FileStoreType_value = map[string]int32{
	"ErasureCode":  0,
	"MultiReplica": 1,
}

func (x FileStoreType) String() string {
	return proto.EnumName(FileStoreType_name, int32(x))
}
func (FileStoreType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type SortType int32

const (
	SortType_Name    SortType = 0
	SortType_ModTime SortType = 1
	SortType_Size    SortType = 2
)

var SortType_name = map[int32]string{
	0: "Name",
	1: "ModTime",
	2: "Size",
}
var SortType_value = map[string]int32{
	"Name":    0,
	"ModTime": 1,
	"Size":    2,
}

func (x SortType) String() string {
	return proto.EnumName(SortType_name, int32(x))
}
func (SortType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type GetPublicKeyReq struct {
	Version uint32 `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
}

func (m *GetPublicKeyReq) Reset()                    { *m = GetPublicKeyReq{} }
func (m *GetPublicKeyReq) String() string            { return proto.CompactTextString(m) }
func (*GetPublicKeyReq) ProtoMessage()               {}
func (*GetPublicKeyReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GetPublicKeyReq) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

type GetPublicKeyResp struct {
	PublicKey     []byte `protobuf:"bytes,1,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	PublicKeyHash []byte `protobuf:"bytes,2,opt,name=publicKeyHash,proto3" json:"publicKeyHash,omitempty"`
}

func (m *GetPublicKeyResp) Reset()                    { *m = GetPublicKeyResp{} }
func (m *GetPublicKeyResp) String() string            { return proto.CompactTextString(m) }
func (*GetPublicKeyResp) ProtoMessage()               {}
func (*GetPublicKeyResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetPublicKeyResp) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *GetPublicKeyResp) GetPublicKeyHash() []byte {
	if m != nil {
		return m.PublicKeyHash
	}
	return nil
}

type MkFolderReq struct {
	Version     uint32    `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	NodeId      []byte    `protobuf:"bytes,2,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	Timestamp   uint64    `protobuf:"varint,3,opt,name=timestamp" json:"timestamp,omitempty"`
	Parent      *FilePath `protobuf:"bytes,4,opt,name=parent" json:"parent,omitempty"`
	Folder      []string  `protobuf:"bytes,5,rep,name=folder" json:"folder,omitempty"`
	Interactive bool      `protobuf:"varint,6,opt,name=interactive" json:"interactive,omitempty"`
	Sign        []byte    `protobuf:"bytes,7,opt,name=sign,proto3" json:"sign,omitempty"`
}

func (m *MkFolderReq) Reset()                    { *m = MkFolderReq{} }
func (m *MkFolderReq) String() string            { return proto.CompactTextString(m) }
func (*MkFolderReq) ProtoMessage()               {}
func (*MkFolderReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *MkFolderReq) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *MkFolderReq) GetNodeId() []byte {
	if m != nil {
		return m.NodeId
	}
	return nil
}

func (m *MkFolderReq) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *MkFolderReq) GetParent() *FilePath {
	if m != nil {
		return m.Parent
	}
	return nil
}

func (m *MkFolderReq) GetFolder() []string {
	if m != nil {
		return m.Folder
	}
	return nil
}

func (m *MkFolderReq) GetInteractive() bool {
	if m != nil {
		return m.Interactive
	}
	return false
}

func (m *MkFolderReq) GetSign() []byte {
	if m != nil {
		return m.Sign
	}
	return nil
}

type FilePath struct {
	// Types that are valid to be assigned to OneOfPath:
	//	*FilePath_Path
	//	*FilePath_Id
	OneOfPath isFilePath_OneOfPath `protobuf_oneof:"oneOfPath"`
	SpaceNo   uint32               `protobuf:"varint,3,opt,name=spaceNo" json:"spaceNo,omitempty"`
}

func (m *FilePath) Reset()                    { *m = FilePath{} }
func (m *FilePath) String() string            { return proto.CompactTextString(m) }
func (*FilePath) ProtoMessage()               {}
func (*FilePath) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type isFilePath_OneOfPath interface {
	isFilePath_OneOfPath()
}

type FilePath_Path struct {
	Path string `protobuf:"bytes,1,opt,name=path,oneof"`
}
type FilePath_Id struct {
	Id []byte `protobuf:"bytes,2,opt,name=id,proto3,oneof"`
}

func (*FilePath_Path) isFilePath_OneOfPath() {}
func (*FilePath_Id) isFilePath_OneOfPath()   {}

func (m *FilePath) GetOneOfPath() isFilePath_OneOfPath {
	if m != nil {
		return m.OneOfPath
	}
	return nil
}

func (m *FilePath) GetPath() string {
	if x, ok := m.GetOneOfPath().(*FilePath_Path); ok {
		return x.Path
	}
	return ""
}

func (m *FilePath) GetId() []byte {
	if x, ok := m.GetOneOfPath().(*FilePath_Id); ok {
		return x.Id
	}
	return nil
}

func (m *FilePath) GetSpaceNo() uint32 {
	if m != nil {
		return m.SpaceNo
	}
	return 0
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*FilePath) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _FilePath_OneofMarshaler, _FilePath_OneofUnmarshaler, _FilePath_OneofSizer, []interface{}{
		(*FilePath_Path)(nil),
		(*FilePath_Id)(nil),
	}
}

func _FilePath_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*FilePath)
	// oneOfPath
	switch x := m.OneOfPath.(type) {
	case *FilePath_Path:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Path)
	case *FilePath_Id:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		b.EncodeRawBytes(x.Id)
	case nil:
	default:
		return fmt.Errorf("FilePath.OneOfPath has unexpected type %T", x)
	}
	return nil
}

func _FilePath_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*FilePath)
	switch tag {
	case 1: // oneOfPath.path
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.OneOfPath = &FilePath_Path{x}
		return true, err
	case 2: // oneOfPath.id
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeRawBytes(true)
		m.OneOfPath = &FilePath_Id{x}
		return true, err
	default:
		return false, nil
	}
}

func _FilePath_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*FilePath)
	// oneOfPath
	switch x := m.OneOfPath.(type) {
	case *FilePath_Path:
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.Path)))
		n += len(x.Path)
	case *FilePath_Id:
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.Id)))
		n += len(x.Id)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type MkFolderResp struct {
	Code   uint32 `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	ErrMsg string `protobuf:"bytes,2,opt,name=errMsg" json:"errMsg,omitempty"`
}

func (m *MkFolderResp) Reset()                    { *m = MkFolderResp{} }
func (m *MkFolderResp) String() string            { return proto.CompactTextString(m) }
func (*MkFolderResp) ProtoMessage()               {}
func (*MkFolderResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *MkFolderResp) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *MkFolderResp) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

type CheckFileExistReq struct {
	Version       uint32    `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	NodeId        []byte    `protobuf:"bytes,2,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	Timestamp     uint64    `protobuf:"varint,3,opt,name=timestamp" json:"timestamp,omitempty"`
	Parent        *FilePath `protobuf:"bytes,4,opt,name=parent" json:"parent,omitempty"`
	FileHash      []byte    `protobuf:"bytes,5,opt,name=fileHash,proto3" json:"fileHash,omitempty"`
	FileSize      uint64    `protobuf:"varint,6,opt,name=fileSize" json:"fileSize,omitempty"`
	FileType      string    `protobuf:"bytes,7,opt,name=fileType" json:"fileType,omitempty"`
	EncryptKey    []byte    `protobuf:"bytes,8,opt,name=encryptKey,proto3" json:"encryptKey,omitempty"`
	PublicKeyHash []byte    `protobuf:"bytes,9,opt,name=publicKeyHash,proto3" json:"publicKeyHash,omitempty"`
	FileName      string    `protobuf:"bytes,10,opt,name=fileName" json:"fileName,omitempty"`
	FileModTime   uint64    `protobuf:"varint,11,opt,name=fileModTime" json:"fileModTime,omitempty"`
	FileData      []byte    `protobuf:"bytes,12,opt,name=fileData,proto3" json:"fileData,omitempty"`
	Interactive   bool      `protobuf:"varint,13,opt,name=interactive" json:"interactive,omitempty"`
	NewVersion    bool      `protobuf:"varint,14,opt,name=newVersion" json:"newVersion,omitempty"`
	Sign          []byte    `protobuf:"bytes,15,opt,name=sign,proto3" json:"sign,omitempty"`
}

func (m *CheckFileExistReq) Reset()                    { *m = CheckFileExistReq{} }
func (m *CheckFileExistReq) String() string            { return proto.CompactTextString(m) }
func (*CheckFileExistReq) ProtoMessage()               {}
func (*CheckFileExistReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *CheckFileExistReq) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *CheckFileExistReq) GetNodeId() []byte {
	if m != nil {
		return m.NodeId
	}
	return nil
}

func (m *CheckFileExistReq) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *CheckFileExistReq) GetParent() *FilePath {
	if m != nil {
		return m.Parent
	}
	return nil
}

func (m *CheckFileExistReq) GetFileHash() []byte {
	if m != nil {
		return m.FileHash
	}
	return nil
}

func (m *CheckFileExistReq) GetFileSize() uint64 {
	if m != nil {
		return m.FileSize
	}
	return 0
}

func (m *CheckFileExistReq) GetFileType() string {
	if m != nil {
		return m.FileType
	}
	return ""
}

func (m *CheckFileExistReq) GetEncryptKey() []byte {
	if m != nil {
		return m.EncryptKey
	}
	return nil
}

func (m *CheckFileExistReq) GetPublicKeyHash() []byte {
	if m != nil {
		return m.PublicKeyHash
	}
	return nil
}

func (m *CheckFileExistReq) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *CheckFileExistReq) GetFileModTime() uint64 {
	if m != nil {
		return m.FileModTime
	}
	return 0
}

func (m *CheckFileExistReq) GetFileData() []byte {
	if m != nil {
		return m.FileData
	}
	return nil
}

func (m *CheckFileExistReq) GetInteractive() bool {
	if m != nil {
		return m.Interactive
	}
	return false
}

func (m *CheckFileExistReq) GetNewVersion() bool {
	if m != nil {
		return m.NewVersion
	}
	return false
}

func (m *CheckFileExistReq) GetSign() []byte {
	if m != nil {
		return m.Sign
	}
	return nil
}

type CheckFileExistResp struct {
	Code             uint32             `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	ErrMsg           string             `protobuf:"bytes,2,opt,name=errMsg" json:"errMsg,omitempty"`
	StoreType        FileStoreType      `protobuf:"varint,3,opt,name=storeType,enum=metadata.pb.FileStoreType" json:"storeType,omitempty"`
	DataPieceCount   uint32             `protobuf:"varint,4,opt,name=dataPieceCount" json:"dataPieceCount,omitempty"`
	VerifyPieceCount uint32             `protobuf:"varint,5,opt,name=verifyPieceCount" json:"verifyPieceCount,omitempty"`
	ReplicaCount     uint32             `protobuf:"varint,6,opt,name=replicaCount" json:"replicaCount,omitempty"`
	Provider         []*ReplicaProvider `protobuf:"bytes,7,rep,name=provider" json:"provider,omitempty"`
}

func (m *CheckFileExistResp) Reset()                    { *m = CheckFileExistResp{} }
func (m *CheckFileExistResp) String() string            { return proto.CompactTextString(m) }
func (*CheckFileExistResp) ProtoMessage()               {}
func (*CheckFileExistResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *CheckFileExistResp) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *CheckFileExistResp) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *CheckFileExistResp) GetStoreType() FileStoreType {
	if m != nil {
		return m.StoreType
	}
	return FileStoreType_ErasureCode
}

func (m *CheckFileExistResp) GetDataPieceCount() uint32 {
	if m != nil {
		return m.DataPieceCount
	}
	return 0
}

func (m *CheckFileExistResp) GetVerifyPieceCount() uint32 {
	if m != nil {
		return m.VerifyPieceCount
	}
	return 0
}

func (m *CheckFileExistResp) GetReplicaCount() uint32 {
	if m != nil {
		return m.ReplicaCount
	}
	return 0
}

func (m *CheckFileExistResp) GetProvider() []*ReplicaProvider {
	if m != nil {
		return m.Provider
	}
	return nil
}

type ReplicaProvider struct {
	NodeId    []byte `protobuf:"bytes,1,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	Server    string `protobuf:"bytes,2,opt,name=server" json:"server,omitempty"`
	Port      uint32 `protobuf:"varint,3,opt,name=port" json:"port,omitempty"`
	Timestamp uint64 `protobuf:"varint,4,opt,name=timestamp" json:"timestamp,omitempty"`
	Ticket    string `protobuf:"bytes,5,opt,name=ticket" json:"ticket,omitempty"`
	Auth      []byte `protobuf:"bytes,6,opt,name=auth,proto3" json:"auth,omitempty"`
}

func (m *ReplicaProvider) Reset()                    { *m = ReplicaProvider{} }
func (m *ReplicaProvider) String() string            { return proto.CompactTextString(m) }
func (*ReplicaProvider) ProtoMessage()               {}
func (*ReplicaProvider) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *ReplicaProvider) GetNodeId() []byte {
	if m != nil {
		return m.NodeId
	}
	return nil
}

func (m *ReplicaProvider) GetServer() string {
	if m != nil {
		return m.Server
	}
	return ""
}

func (m *ReplicaProvider) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *ReplicaProvider) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *ReplicaProvider) GetTicket() string {
	if m != nil {
		return m.Ticket
	}
	return ""
}

func (m *ReplicaProvider) GetAuth() []byte {
	if m != nil {
		return m.Auth
	}
	return nil
}

type UploadFilePrepareReq struct {
	Version   uint32            `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	NodeId    []byte            `protobuf:"bytes,2,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	Timestamp uint64            `protobuf:"varint,3,opt,name=timestamp" json:"timestamp,omitempty"`
	FileHash  []byte            `protobuf:"bytes,4,opt,name=fileHash,proto3" json:"fileHash,omitempty"`
	FileSize  uint64            `protobuf:"varint,5,opt,name=fileSize" json:"fileSize,omitempty"`
	Partition []*SplitPartition `protobuf:"bytes,6,rep,name=partition" json:"partition,omitempty"`
	Sign      []byte            `protobuf:"bytes,7,opt,name=sign,proto3" json:"sign,omitempty"`
}

func (m *UploadFilePrepareReq) Reset()                    { *m = UploadFilePrepareReq{} }
func (m *UploadFilePrepareReq) String() string            { return proto.CompactTextString(m) }
func (*UploadFilePrepareReq) ProtoMessage()               {}
func (*UploadFilePrepareReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *UploadFilePrepareReq) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *UploadFilePrepareReq) GetNodeId() []byte {
	if m != nil {
		return m.NodeId
	}
	return nil
}

func (m *UploadFilePrepareReq) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *UploadFilePrepareReq) GetFileHash() []byte {
	if m != nil {
		return m.FileHash
	}
	return nil
}

func (m *UploadFilePrepareReq) GetFileSize() uint64 {
	if m != nil {
		return m.FileSize
	}
	return 0
}

func (m *UploadFilePrepareReq) GetPartition() []*SplitPartition {
	if m != nil {
		return m.Partition
	}
	return nil
}

func (m *UploadFilePrepareReq) GetSign() []byte {
	if m != nil {
		return m.Sign
	}
	return nil
}

type SplitPartition struct {
	Piece []*PieceHashAndSize `protobuf:"bytes,1,rep,name=piece" json:"piece,omitempty"`
}

func (m *SplitPartition) Reset()                    { *m = SplitPartition{} }
func (m *SplitPartition) String() string            { return proto.CompactTextString(m) }
func (*SplitPartition) ProtoMessage()               {}
func (*SplitPartition) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *SplitPartition) GetPiece() []*PieceHashAndSize {
	if m != nil {
		return m.Piece
	}
	return nil
}

type PieceHashAndSize struct {
	Hash []byte `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Size uint32 `protobuf:"varint,2,opt,name=size" json:"size,omitempty"`
}

func (m *PieceHashAndSize) Reset()                    { *m = PieceHashAndSize{} }
func (m *PieceHashAndSize) String() string            { return proto.CompactTextString(m) }
func (*PieceHashAndSize) ProtoMessage()               {}
func (*PieceHashAndSize) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *PieceHashAndSize) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *PieceHashAndSize) GetSize() uint32 {
	if m != nil {
		return m.Size
	}
	return 0
}

type UploadFilePrepareResp struct {
	Partition []*ErasureCodePartition `protobuf:"bytes,1,rep,name=partition" json:"partition,omitempty"`
}

func (m *UploadFilePrepareResp) Reset()                    { *m = UploadFilePrepareResp{} }
func (m *UploadFilePrepareResp) String() string            { return proto.CompactTextString(m) }
func (*UploadFilePrepareResp) ProtoMessage()               {}
func (*UploadFilePrepareResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *UploadFilePrepareResp) GetPartition() []*ErasureCodePartition {
	if m != nil {
		return m.Partition
	}
	return nil
}

type ErasureCodePartition struct {
	ProviderAuth []*BlockProviderAuth `protobuf:"bytes,1,rep,name=providerAuth" json:"providerAuth,omitempty"`
	Timestamp    uint64               `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
}

func (m *ErasureCodePartition) Reset()                    { *m = ErasureCodePartition{} }
func (m *ErasureCodePartition) String() string            { return proto.CompactTextString(m) }
func (*ErasureCodePartition) ProtoMessage()               {}
func (*ErasureCodePartition) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *ErasureCodePartition) GetProviderAuth() []*BlockProviderAuth {
	if m != nil {
		return m.ProviderAuth
	}
	return nil
}

func (m *ErasureCodePartition) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type BlockProviderAuth struct {
	NodeId   []byte           `protobuf:"bytes,1,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	Server   string           `protobuf:"bytes,2,opt,name=server" json:"server,omitempty"`
	Port     uint32           `protobuf:"varint,3,opt,name=port" json:"port,omitempty"`
	Spare    bool             `protobuf:"varint,4,opt,name=spare" json:"spare,omitempty"`
	HashAuth []*PieceHashAuth `protobuf:"bytes,5,rep,name=hashAuth" json:"hashAuth,omitempty"`
}

func (m *BlockProviderAuth) Reset()                    { *m = BlockProviderAuth{} }
func (m *BlockProviderAuth) String() string            { return proto.CompactTextString(m) }
func (*BlockProviderAuth) ProtoMessage()               {}
func (*BlockProviderAuth) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *BlockProviderAuth) GetNodeId() []byte {
	if m != nil {
		return m.NodeId
	}
	return nil
}

func (m *BlockProviderAuth) GetServer() string {
	if m != nil {
		return m.Server
	}
	return ""
}

func (m *BlockProviderAuth) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *BlockProviderAuth) GetSpare() bool {
	if m != nil {
		return m.Spare
	}
	return false
}

func (m *BlockProviderAuth) GetHashAuth() []*PieceHashAuth {
	if m != nil {
		return m.HashAuth
	}
	return nil
}

type PieceHashAuth struct {
	Hash   []byte `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Size   uint32 `protobuf:"varint,2,opt,name=size" json:"size,omitempty"`
	Ticket string `protobuf:"bytes,3,opt,name=ticket" json:"ticket,omitempty"`
	Auth   []byte `protobuf:"bytes,4,opt,name=auth,proto3" json:"auth,omitempty"`
}

func (m *PieceHashAuth) Reset()                    { *m = PieceHashAuth{} }
func (m *PieceHashAuth) String() string            { return proto.CompactTextString(m) }
func (*PieceHashAuth) ProtoMessage()               {}
func (*PieceHashAuth) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *PieceHashAuth) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *PieceHashAuth) GetSize() uint32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *PieceHashAuth) GetTicket() string {
	if m != nil {
		return m.Ticket
	}
	return ""
}

func (m *PieceHashAuth) GetAuth() []byte {
	if m != nil {
		return m.Auth
	}
	return nil
}

type UploadFileDoneReq struct {
	Version       uint32            `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	NodeId        []byte            `protobuf:"bytes,2,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	Timestamp     uint64            `protobuf:"varint,3,opt,name=timestamp" json:"timestamp,omitempty"`
	Parent        *FilePath         `protobuf:"bytes,4,opt,name=parent" json:"parent,omitempty"`
	FileHash      []byte            `protobuf:"bytes,5,opt,name=fileHash,proto3" json:"fileHash,omitempty"`
	FileSize      uint64            `protobuf:"varint,6,opt,name=fileSize" json:"fileSize,omitempty"`
	EncryptKey    []byte            `protobuf:"bytes,7,opt,name=encryptKey,proto3" json:"encryptKey,omitempty"`
	PublicKeyHash []byte            `protobuf:"bytes,8,opt,name=publicKeyHash,proto3" json:"publicKeyHash,omitempty"`
	FileName      string            `protobuf:"bytes,9,opt,name=fileName" json:"fileName,omitempty"`
	FileModTime   uint64            `protobuf:"varint,10,opt,name=fileModTime" json:"fileModTime,omitempty"`
	Partition     []*StorePartition `protobuf:"bytes,11,rep,name=partition" json:"partition,omitempty"`
	Interactive   bool              `protobuf:"varint,12,opt,name=interactive" json:"interactive,omitempty"`
	NewVersion    bool              `protobuf:"varint,13,opt,name=newVersion" json:"newVersion,omitempty"`
	Sign          []byte            `protobuf:"bytes,14,opt,name=sign,proto3" json:"sign,omitempty"`
}

func (m *UploadFileDoneReq) Reset()                    { *m = UploadFileDoneReq{} }
func (m *UploadFileDoneReq) String() string            { return proto.CompactTextString(m) }
func (*UploadFileDoneReq) ProtoMessage()               {}
func (*UploadFileDoneReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *UploadFileDoneReq) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *UploadFileDoneReq) GetNodeId() []byte {
	if m != nil {
		return m.NodeId
	}
	return nil
}

func (m *UploadFileDoneReq) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *UploadFileDoneReq) GetParent() *FilePath {
	if m != nil {
		return m.Parent
	}
	return nil
}

func (m *UploadFileDoneReq) GetFileHash() []byte {
	if m != nil {
		return m.FileHash
	}
	return nil
}

func (m *UploadFileDoneReq) GetFileSize() uint64 {
	if m != nil {
		return m.FileSize
	}
	return 0
}

func (m *UploadFileDoneReq) GetEncryptKey() []byte {
	if m != nil {
		return m.EncryptKey
	}
	return nil
}

func (m *UploadFileDoneReq) GetPublicKeyHash() []byte {
	if m != nil {
		return m.PublicKeyHash
	}
	return nil
}

func (m *UploadFileDoneReq) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *UploadFileDoneReq) GetFileModTime() uint64 {
	if m != nil {
		return m.FileModTime
	}
	return 0
}

func (m *UploadFileDoneReq) GetPartition() []*StorePartition {
	if m != nil {
		return m.Partition
	}
	return nil
}

func (m *UploadFileDoneReq) GetInteractive() bool {
	if m != nil {
		return m.Interactive
	}
	return false
}

func (m *UploadFileDoneReq) GetNewVersion() bool {
	if m != nil {
		return m.NewVersion
	}
	return false
}

func (m *UploadFileDoneReq) GetSign() []byte {
	if m != nil {
		return m.Sign
	}
	return nil
}

type StorePartition struct {
	Block []*StoreBlock `protobuf:"bytes,1,rep,name=block" json:"block,omitempty"`
}

func (m *StorePartition) Reset()                    { *m = StorePartition{} }
func (m *StorePartition) String() string            { return proto.CompactTextString(m) }
func (*StorePartition) ProtoMessage()               {}
func (*StorePartition) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *StorePartition) GetBlock() []*StoreBlock {
	if m != nil {
		return m.Block
	}
	return nil
}

type StoreBlock struct {
	Hash        []byte   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Size        uint64   `protobuf:"varint,2,opt,name=size" json:"size,omitempty"`
	BlockSeq    uint32   `protobuf:"varint,3,opt,name=blockSeq" json:"blockSeq,omitempty"`
	Checksum    bool     `protobuf:"varint,4,opt,name=checksum" json:"checksum,omitempty"`
	StoreNodeId [][]byte `protobuf:"bytes,5,rep,name=storeNodeId,proto3" json:"storeNodeId,omitempty"`
}

func (m *StoreBlock) Reset()                    { *m = StoreBlock{} }
func (m *StoreBlock) String() string            { return proto.CompactTextString(m) }
func (*StoreBlock) ProtoMessage()               {}
func (*StoreBlock) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *StoreBlock) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *StoreBlock) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *StoreBlock) GetBlockSeq() uint32 {
	if m != nil {
		return m.BlockSeq
	}
	return 0
}

func (m *StoreBlock) GetChecksum() bool {
	if m != nil {
		return m.Checksum
	}
	return false
}

func (m *StoreBlock) GetStoreNodeId() [][]byte {
	if m != nil {
		return m.StoreNodeId
	}
	return nil
}

type UploadFileDoneResp struct {
	Code   uint32 `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	ErrMsg string `protobuf:"bytes,2,opt,name=errMsg" json:"errMsg,omitempty"`
}

func (m *UploadFileDoneResp) Reset()                    { *m = UploadFileDoneResp{} }
func (m *UploadFileDoneResp) String() string            { return proto.CompactTextString(m) }
func (*UploadFileDoneResp) ProtoMessage()               {}
func (*UploadFileDoneResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *UploadFileDoneResp) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *UploadFileDoneResp) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

type ListFilesReq struct {
	Version   uint32    `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	NodeId    []byte    `protobuf:"bytes,2,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	Timestamp uint64    `protobuf:"varint,3,opt,name=timestamp" json:"timestamp,omitempty"`
	Parent    *FilePath `protobuf:"bytes,4,opt,name=parent" json:"parent,omitempty"`
	PageSize  uint32    `protobuf:"varint,5,opt,name=pageSize" json:"pageSize,omitempty"`
	PageNum   uint32    `protobuf:"varint,6,opt,name=pageNum" json:"pageNum,omitempty"`
	SortType  SortType  `protobuf:"varint,7,opt,name=sortType,enum=metadata.pb.SortType" json:"sortType,omitempty"`
	AscOrder  bool      `protobuf:"varint,8,opt,name=ascOrder" json:"ascOrder,omitempty"`
	Sign      []byte    `protobuf:"bytes,9,opt,name=sign,proto3" json:"sign,omitempty"`
}

func (m *ListFilesReq) Reset()                    { *m = ListFilesReq{} }
func (m *ListFilesReq) String() string            { return proto.CompactTextString(m) }
func (*ListFilesReq) ProtoMessage()               {}
func (*ListFilesReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *ListFilesReq) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *ListFilesReq) GetNodeId() []byte {
	if m != nil {
		return m.NodeId
	}
	return nil
}

func (m *ListFilesReq) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *ListFilesReq) GetParent() *FilePath {
	if m != nil {
		return m.Parent
	}
	return nil
}

func (m *ListFilesReq) GetPageSize() uint32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListFilesReq) GetPageNum() uint32 {
	if m != nil {
		return m.PageNum
	}
	return 0
}

func (m *ListFilesReq) GetSortType() SortType {
	if m != nil {
		return m.SortType
	}
	return SortType_Name
}

func (m *ListFilesReq) GetAscOrder() bool {
	if m != nil {
		return m.AscOrder
	}
	return false
}

func (m *ListFilesReq) GetSign() []byte {
	if m != nil {
		return m.Sign
	}
	return nil
}

type ListFilesResp struct {
	Code        uint32          `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	ErrMsg      string          `protobuf:"bytes,2,opt,name=errMsg" json:"errMsg,omitempty"`
	TotalRecord uint32          `protobuf:"varint,3,opt,name=totalRecord" json:"totalRecord,omitempty"`
	Fof         []*FileOrFolder `protobuf:"bytes,4,rep,name=fof" json:"fof,omitempty"`
}

func (m *ListFilesResp) Reset()                    { *m = ListFilesResp{} }
func (m *ListFilesResp) String() string            { return proto.CompactTextString(m) }
func (*ListFilesResp) ProtoMessage()               {}
func (*ListFilesResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *ListFilesResp) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ListFilesResp) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *ListFilesResp) GetTotalRecord() uint32 {
	if m != nil {
		return m.TotalRecord
	}
	return 0
}

func (m *ListFilesResp) GetFof() []*FileOrFolder {
	if m != nil {
		return m.Fof
	}
	return nil
}

type FileOrFolder struct {
	Id       []byte `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Folder   bool   `protobuf:"varint,2,opt,name=folder" json:"folder,omitempty"`
	Name     string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	ModTime  uint64 `protobuf:"varint,4,opt,name=modTime" json:"modTime,omitempty"`
	FileHash []byte `protobuf:"bytes,5,opt,name=fileHash,proto3" json:"fileHash,omitempty"`
	FileSize uint64 `protobuf:"varint,6,opt,name=fileSize" json:"fileSize,omitempty"`
	FileType string `protobuf:"bytes,7,opt,name=fileType" json:"fileType,omitempty"`
}

func (m *FileOrFolder) Reset()                    { *m = FileOrFolder{} }
func (m *FileOrFolder) String() string            { return proto.CompactTextString(m) }
func (*FileOrFolder) ProtoMessage()               {}
func (*FileOrFolder) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *FileOrFolder) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *FileOrFolder) GetFolder() bool {
	if m != nil {
		return m.Folder
	}
	return false
}

func (m *FileOrFolder) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FileOrFolder) GetModTime() uint64 {
	if m != nil {
		return m.ModTime
	}
	return 0
}

func (m *FileOrFolder) GetFileHash() []byte {
	if m != nil {
		return m.FileHash
	}
	return nil
}

func (m *FileOrFolder) GetFileSize() uint64 {
	if m != nil {
		return m.FileSize
	}
	return 0
}

func (m *FileOrFolder) GetFileType() string {
	if m != nil {
		return m.FileType
	}
	return ""
}

type RetrieveFileReq struct {
	Version   uint32 `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	NodeId    []byte `protobuf:"bytes,2,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	Timestamp uint64 `protobuf:"varint,3,opt,name=timestamp" json:"timestamp,omitempty"`
	FileHash  []byte `protobuf:"bytes,4,opt,name=fileHash,proto3" json:"fileHash,omitempty"`
	FileSize  uint64 `protobuf:"varint,5,opt,name=fileSize" json:"fileSize,omitempty"`
	Sign      []byte `protobuf:"bytes,6,opt,name=sign,proto3" json:"sign,omitempty"`
}

func (m *RetrieveFileReq) Reset()                    { *m = RetrieveFileReq{} }
func (m *RetrieveFileReq) String() string            { return proto.CompactTextString(m) }
func (*RetrieveFileReq) ProtoMessage()               {}
func (*RetrieveFileReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *RetrieveFileReq) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *RetrieveFileReq) GetNodeId() []byte {
	if m != nil {
		return m.NodeId
	}
	return nil
}

func (m *RetrieveFileReq) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *RetrieveFileReq) GetFileHash() []byte {
	if m != nil {
		return m.FileHash
	}
	return nil
}

func (m *RetrieveFileReq) GetFileSize() uint64 {
	if m != nil {
		return m.FileSize
	}
	return 0
}

func (m *RetrieveFileReq) GetSign() []byte {
	if m != nil {
		return m.Sign
	}
	return nil
}

type RetrieveFileResp struct {
	Code       uint32               `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	ErrMsg     string               `protobuf:"bytes,2,opt,name=errMsg" json:"errMsg,omitempty"`
	FileData   []byte               `protobuf:"bytes,3,opt,name=fileData,proto3" json:"fileData,omitempty"`
	FileType   string               `protobuf:"bytes,4,opt,name=fileType" json:"fileType,omitempty"`
	EncryptKey []byte               `protobuf:"bytes,5,opt,name=encryptKey,proto3" json:"encryptKey,omitempty"`
	Partition  []*RetrievePartition `protobuf:"bytes,6,rep,name=partition" json:"partition,omitempty"`
	Timestamp  uint64               `protobuf:"varint,7,opt,name=timestamp" json:"timestamp,omitempty"`
}

func (m *RetrieveFileResp) Reset()                    { *m = RetrieveFileResp{} }
func (m *RetrieveFileResp) String() string            { return proto.CompactTextString(m) }
func (*RetrieveFileResp) ProtoMessage()               {}
func (*RetrieveFileResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *RetrieveFileResp) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *RetrieveFileResp) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *RetrieveFileResp) GetFileData() []byte {
	if m != nil {
		return m.FileData
	}
	return nil
}

func (m *RetrieveFileResp) GetFileType() string {
	if m != nil {
		return m.FileType
	}
	return ""
}

func (m *RetrieveFileResp) GetEncryptKey() []byte {
	if m != nil {
		return m.EncryptKey
	}
	return nil
}

func (m *RetrieveFileResp) GetPartition() []*RetrievePartition {
	if m != nil {
		return m.Partition
	}
	return nil
}

func (m *RetrieveFileResp) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type RetrievePartition struct {
	Block []*RetrieveBlock `protobuf:"bytes,1,rep,name=block" json:"block,omitempty"`
}

func (m *RetrievePartition) Reset()                    { *m = RetrievePartition{} }
func (m *RetrievePartition) String() string            { return proto.CompactTextString(m) }
func (*RetrievePartition) ProtoMessage()               {}
func (*RetrievePartition) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func (m *RetrievePartition) GetBlock() []*RetrieveBlock {
	if m != nil {
		return m.Block
	}
	return nil
}

type RetrieveBlock struct {
	Hash      []byte          `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Size      uint64          `protobuf:"varint,2,opt,name=size" json:"size,omitempty"`
	BlockSeq  uint32          `protobuf:"varint,3,opt,name=blockSeq" json:"blockSeq,omitempty"`
	Checksum  bool            `protobuf:"varint,4,opt,name=checksum" json:"checksum,omitempty"`
	StoreNode []*RetrieveNode `protobuf:"bytes,5,rep,name=storeNode" json:"storeNode,omitempty"`
}

func (m *RetrieveBlock) Reset()                    { *m = RetrieveBlock{} }
func (m *RetrieveBlock) String() string            { return proto.CompactTextString(m) }
func (*RetrieveBlock) ProtoMessage()               {}
func (*RetrieveBlock) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

func (m *RetrieveBlock) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *RetrieveBlock) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *RetrieveBlock) GetBlockSeq() uint32 {
	if m != nil {
		return m.BlockSeq
	}
	return 0
}

func (m *RetrieveBlock) GetChecksum() bool {
	if m != nil {
		return m.Checksum
	}
	return false
}

func (m *RetrieveBlock) GetStoreNode() []*RetrieveNode {
	if m != nil {
		return m.StoreNode
	}
	return nil
}

type RetrieveNode struct {
	NodeId []byte `protobuf:"bytes,1,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	Server string `protobuf:"bytes,2,opt,name=server" json:"server,omitempty"`
	Port   uint32 `protobuf:"varint,3,opt,name=port" json:"port,omitempty"`
	Ticket string `protobuf:"bytes,4,opt,name=ticket" json:"ticket,omitempty"`
	Auth   []byte `protobuf:"bytes,5,opt,name=auth,proto3" json:"auth,omitempty"`
}

func (m *RetrieveNode) Reset()                    { *m = RetrieveNode{} }
func (m *RetrieveNode) String() string            { return proto.CompactTextString(m) }
func (*RetrieveNode) ProtoMessage()               {}
func (*RetrieveNode) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

func (m *RetrieveNode) GetNodeId() []byte {
	if m != nil {
		return m.NodeId
	}
	return nil
}

func (m *RetrieveNode) GetServer() string {
	if m != nil {
		return m.Server
	}
	return ""
}

func (m *RetrieveNode) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *RetrieveNode) GetTicket() string {
	if m != nil {
		return m.Ticket
	}
	return ""
}

func (m *RetrieveNode) GetAuth() []byte {
	if m != nil {
		return m.Auth
	}
	return nil
}

type RemoveReq struct {
	Version   uint32    `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	NodeId    []byte    `protobuf:"bytes,2,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	Timestamp uint64    `protobuf:"varint,3,opt,name=timestamp" json:"timestamp,omitempty"`
	Target    *FilePath `protobuf:"bytes,4,opt,name=target" json:"target,omitempty"`
	Recursive bool      `protobuf:"varint,5,opt,name=recursive" json:"recursive,omitempty"`
	Sign      []byte    `protobuf:"bytes,6,opt,name=sign,proto3" json:"sign,omitempty"`
}

func (m *RemoveReq) Reset()                    { *m = RemoveReq{} }
func (m *RemoveReq) String() string            { return proto.CompactTextString(m) }
func (*RemoveReq) ProtoMessage()               {}
func (*RemoveReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

func (m *RemoveReq) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *RemoveReq) GetNodeId() []byte {
	if m != nil {
		return m.NodeId
	}
	return nil
}

func (m *RemoveReq) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *RemoveReq) GetTarget() *FilePath {
	if m != nil {
		return m.Target
	}
	return nil
}

func (m *RemoveReq) GetRecursive() bool {
	if m != nil {
		return m.Recursive
	}
	return false
}

func (m *RemoveReq) GetSign() []byte {
	if m != nil {
		return m.Sign
	}
	return nil
}

type RemoveResp struct {
	Code   uint32 `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	ErrMsg string `protobuf:"bytes,2,opt,name=errMsg" json:"errMsg,omitempty"`
}

func (m *RemoveResp) Reset()                    { *m = RemoveResp{} }
func (m *RemoveResp) String() string            { return proto.CompactTextString(m) }
func (*RemoveResp) ProtoMessage()               {}
func (*RemoveResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{28} }

func (m *RemoveResp) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *RemoveResp) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

type MoveReq struct {
	Version   uint32    `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	NodeId    []byte    `protobuf:"bytes,2,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	Timestamp uint64    `protobuf:"varint,3,opt,name=timestamp" json:"timestamp,omitempty"`
	Source    *FilePath `protobuf:"bytes,4,opt,name=source" json:"source,omitempty"`
	Dest      string    `protobuf:"bytes,5,opt,name=dest" json:"dest,omitempty"`
	Sign      []byte    `protobuf:"bytes,9,opt,name=sign,proto3" json:"sign,omitempty"`
}

func (m *MoveReq) Reset()                    { *m = MoveReq{} }
func (m *MoveReq) String() string            { return proto.CompactTextString(m) }
func (*MoveReq) ProtoMessage()               {}
func (*MoveReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{29} }

func (m *MoveReq) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *MoveReq) GetNodeId() []byte {
	if m != nil {
		return m.NodeId
	}
	return nil
}

func (m *MoveReq) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *MoveReq) GetSource() *FilePath {
	if m != nil {
		return m.Source
	}
	return nil
}

func (m *MoveReq) GetDest() string {
	if m != nil {
		return m.Dest
	}
	return ""
}

func (m *MoveReq) GetSign() []byte {
	if m != nil {
		return m.Sign
	}
	return nil
}

type MoveResp struct {
	Code   uint32 `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	ErrMsg string `protobuf:"bytes,2,opt,name=errMsg" json:"errMsg,omitempty"`
}

func (m *MoveResp) Reset()                    { *m = MoveResp{} }
func (m *MoveResp) String() string            { return proto.CompactTextString(m) }
func (*MoveResp) ProtoMessage()               {}
func (*MoveResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{30} }

func (m *MoveResp) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *MoveResp) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func init() {
	proto.RegisterType((*GetPublicKeyReq)(nil), "metadata.pb.GetPublicKeyReq")
	proto.RegisterType((*GetPublicKeyResp)(nil), "metadata.pb.GetPublicKeyResp")
	proto.RegisterType((*MkFolderReq)(nil), "metadata.pb.MkFolderReq")
	proto.RegisterType((*FilePath)(nil), "metadata.pb.FilePath")
	proto.RegisterType((*MkFolderResp)(nil), "metadata.pb.MkFolderResp")
	proto.RegisterType((*CheckFileExistReq)(nil), "metadata.pb.CheckFileExistReq")
	proto.RegisterType((*CheckFileExistResp)(nil), "metadata.pb.CheckFileExistResp")
	proto.RegisterType((*ReplicaProvider)(nil), "metadata.pb.ReplicaProvider")
	proto.RegisterType((*UploadFilePrepareReq)(nil), "metadata.pb.UploadFilePrepareReq")
	proto.RegisterType((*SplitPartition)(nil), "metadata.pb.SplitPartition")
	proto.RegisterType((*PieceHashAndSize)(nil), "metadata.pb.PieceHashAndSize")
	proto.RegisterType((*UploadFilePrepareResp)(nil), "metadata.pb.UploadFilePrepareResp")
	proto.RegisterType((*ErasureCodePartition)(nil), "metadata.pb.ErasureCodePartition")
	proto.RegisterType((*BlockProviderAuth)(nil), "metadata.pb.BlockProviderAuth")
	proto.RegisterType((*PieceHashAuth)(nil), "metadata.pb.PieceHashAuth")
	proto.RegisterType((*UploadFileDoneReq)(nil), "metadata.pb.UploadFileDoneReq")
	proto.RegisterType((*StorePartition)(nil), "metadata.pb.StorePartition")
	proto.RegisterType((*StoreBlock)(nil), "metadata.pb.StoreBlock")
	proto.RegisterType((*UploadFileDoneResp)(nil), "metadata.pb.UploadFileDoneResp")
	proto.RegisterType((*ListFilesReq)(nil), "metadata.pb.ListFilesReq")
	proto.RegisterType((*ListFilesResp)(nil), "metadata.pb.ListFilesResp")
	proto.RegisterType((*FileOrFolder)(nil), "metadata.pb.FileOrFolder")
	proto.RegisterType((*RetrieveFileReq)(nil), "metadata.pb.RetrieveFileReq")
	proto.RegisterType((*RetrieveFileResp)(nil), "metadata.pb.RetrieveFileResp")
	proto.RegisterType((*RetrievePartition)(nil), "metadata.pb.RetrievePartition")
	proto.RegisterType((*RetrieveBlock)(nil), "metadata.pb.RetrieveBlock")
	proto.RegisterType((*RetrieveNode)(nil), "metadata.pb.RetrieveNode")
	proto.RegisterType((*RemoveReq)(nil), "metadata.pb.RemoveReq")
	proto.RegisterType((*RemoveResp)(nil), "metadata.pb.RemoveResp")
	proto.RegisterType((*MoveReq)(nil), "metadata.pb.MoveReq")
	proto.RegisterType((*MoveResp)(nil), "metadata.pb.MoveResp")
	proto.RegisterEnum("metadata.pb.FileStoreType", FileStoreType_name, FileStoreType_value)
	proto.RegisterEnum("metadata.pb.SortType", SortType_name, SortType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for MatadataService service

type MatadataServiceClient interface {
	GetPublicKey(ctx context.Context, in *GetPublicKeyReq, opts ...grpc.CallOption) (*GetPublicKeyResp, error)
	MkFolder(ctx context.Context, in *MkFolderReq, opts ...grpc.CallOption) (*MkFolderResp, error)
	CheckFileExist(ctx context.Context, in *CheckFileExistReq, opts ...grpc.CallOption) (*CheckFileExistResp, error)
	UploadFilePrepare(ctx context.Context, in *UploadFilePrepareReq, opts ...grpc.CallOption) (*UploadFilePrepareResp, error)
	UploadFileDone(ctx context.Context, in *UploadFileDoneReq, opts ...grpc.CallOption) (*UploadFileDoneResp, error)
	ListFiles(ctx context.Context, in *ListFilesReq, opts ...grpc.CallOption) (*ListFilesResp, error)
	RetrieveFile(ctx context.Context, in *RetrieveFileReq, opts ...grpc.CallOption) (*RetrieveFileResp, error)
	Remove(ctx context.Context, in *RemoveReq, opts ...grpc.CallOption) (*RemoveResp, error)
	Move(ctx context.Context, in *MoveReq, opts ...grpc.CallOption) (*MoveResp, error)
}

type matadataServiceClient struct {
	cc *grpc.ClientConn
}

func NewMatadataServiceClient(cc *grpc.ClientConn) MatadataServiceClient {
	return &matadataServiceClient{cc}
}

func (c *matadataServiceClient) GetPublicKey(ctx context.Context, in *GetPublicKeyReq, opts ...grpc.CallOption) (*GetPublicKeyResp, error) {
	out := new(GetPublicKeyResp)
	err := grpc.Invoke(ctx, "/metadata.pb.MatadataService/GetPublicKey", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matadataServiceClient) MkFolder(ctx context.Context, in *MkFolderReq, opts ...grpc.CallOption) (*MkFolderResp, error) {
	out := new(MkFolderResp)
	err := grpc.Invoke(ctx, "/metadata.pb.MatadataService/MkFolder", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matadataServiceClient) CheckFileExist(ctx context.Context, in *CheckFileExistReq, opts ...grpc.CallOption) (*CheckFileExistResp, error) {
	out := new(CheckFileExistResp)
	err := grpc.Invoke(ctx, "/metadata.pb.MatadataService/CheckFileExist", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matadataServiceClient) UploadFilePrepare(ctx context.Context, in *UploadFilePrepareReq, opts ...grpc.CallOption) (*UploadFilePrepareResp, error) {
	out := new(UploadFilePrepareResp)
	err := grpc.Invoke(ctx, "/metadata.pb.MatadataService/UploadFilePrepare", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matadataServiceClient) UploadFileDone(ctx context.Context, in *UploadFileDoneReq, opts ...grpc.CallOption) (*UploadFileDoneResp, error) {
	out := new(UploadFileDoneResp)
	err := grpc.Invoke(ctx, "/metadata.pb.MatadataService/UploadFileDone", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matadataServiceClient) ListFiles(ctx context.Context, in *ListFilesReq, opts ...grpc.CallOption) (*ListFilesResp, error) {
	out := new(ListFilesResp)
	err := grpc.Invoke(ctx, "/metadata.pb.MatadataService/ListFiles", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matadataServiceClient) RetrieveFile(ctx context.Context, in *RetrieveFileReq, opts ...grpc.CallOption) (*RetrieveFileResp, error) {
	out := new(RetrieveFileResp)
	err := grpc.Invoke(ctx, "/metadata.pb.MatadataService/RetrieveFile", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matadataServiceClient) Remove(ctx context.Context, in *RemoveReq, opts ...grpc.CallOption) (*RemoveResp, error) {
	out := new(RemoveResp)
	err := grpc.Invoke(ctx, "/metadata.pb.MatadataService/Remove", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matadataServiceClient) Move(ctx context.Context, in *MoveReq, opts ...grpc.CallOption) (*MoveResp, error) {
	out := new(MoveResp)
	err := grpc.Invoke(ctx, "/metadata.pb.MatadataService/Move", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for MatadataService service

type MatadataServiceServer interface {
	GetPublicKey(context.Context, *GetPublicKeyReq) (*GetPublicKeyResp, error)
	MkFolder(context.Context, *MkFolderReq) (*MkFolderResp, error)
	CheckFileExist(context.Context, *CheckFileExistReq) (*CheckFileExistResp, error)
	UploadFilePrepare(context.Context, *UploadFilePrepareReq) (*UploadFilePrepareResp, error)
	UploadFileDone(context.Context, *UploadFileDoneReq) (*UploadFileDoneResp, error)
	ListFiles(context.Context, *ListFilesReq) (*ListFilesResp, error)
	RetrieveFile(context.Context, *RetrieveFileReq) (*RetrieveFileResp, error)
	Remove(context.Context, *RemoveReq) (*RemoveResp, error)
	Move(context.Context, *MoveReq) (*MoveResp, error)
}

func RegisterMatadataServiceServer(s *grpc.Server, srv MatadataServiceServer) {
	s.RegisterService(&_MatadataService_serviceDesc, srv)
}

func _MatadataService_GetPublicKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPublicKeyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatadataServiceServer).GetPublicKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metadata.pb.MatadataService/GetPublicKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatadataServiceServer).GetPublicKey(ctx, req.(*GetPublicKeyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatadataService_MkFolder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MkFolderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatadataServiceServer).MkFolder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metadata.pb.MatadataService/MkFolder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatadataServiceServer).MkFolder(ctx, req.(*MkFolderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatadataService_CheckFileExist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckFileExistReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatadataServiceServer).CheckFileExist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metadata.pb.MatadataService/CheckFileExist",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatadataServiceServer).CheckFileExist(ctx, req.(*CheckFileExistReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatadataService_UploadFilePrepare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadFilePrepareReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatadataServiceServer).UploadFilePrepare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metadata.pb.MatadataService/UploadFilePrepare",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatadataServiceServer).UploadFilePrepare(ctx, req.(*UploadFilePrepareReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatadataService_UploadFileDone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadFileDoneReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatadataServiceServer).UploadFileDone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metadata.pb.MatadataService/UploadFileDone",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatadataServiceServer).UploadFileDone(ctx, req.(*UploadFileDoneReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatadataService_ListFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFilesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatadataServiceServer).ListFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metadata.pb.MatadataService/ListFiles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatadataServiceServer).ListFiles(ctx, req.(*ListFilesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatadataService_RetrieveFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveFileReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatadataServiceServer).RetrieveFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metadata.pb.MatadataService/RetrieveFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatadataServiceServer).RetrieveFile(ctx, req.(*RetrieveFileReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatadataService_Remove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatadataServiceServer).Remove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metadata.pb.MatadataService/Remove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatadataServiceServer).Remove(ctx, req.(*RemoveReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatadataService_Move_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatadataServiceServer).Move(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metadata.pb.MatadataService/Move",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatadataServiceServer).Move(ctx, req.(*MoveReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _MatadataService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "metadata.pb.MatadataService",
	HandlerType: (*MatadataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPublicKey",
			Handler:    _MatadataService_GetPublicKey_Handler,
		},
		{
			MethodName: "MkFolder",
			Handler:    _MatadataService_MkFolder_Handler,
		},
		{
			MethodName: "CheckFileExist",
			Handler:    _MatadataService_CheckFileExist_Handler,
		},
		{
			MethodName: "UploadFilePrepare",
			Handler:    _MatadataService_UploadFilePrepare_Handler,
		},
		{
			MethodName: "UploadFileDone",
			Handler:    _MatadataService_UploadFileDone_Handler,
		},
		{
			MethodName: "ListFiles",
			Handler:    _MatadataService_ListFiles_Handler,
		},
		{
			MethodName: "RetrieveFile",
			Handler:    _MatadataService_RetrieveFile_Handler,
		},
		{
			MethodName: "Remove",
			Handler:    _MatadataService_Remove_Handler,
		},
		{
			MethodName: "Move",
			Handler:    _MatadataService_Move_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "metadata.proto",
}

func init() { proto.RegisterFile("metadata.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1569 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x58, 0x4f, 0x6f, 0x1b, 0x45,
	0x14, 0xcf, 0xda, 0x6b, 0x67, 0xfd, 0xfc, 0x27, 0xce, 0x28, 0x4d, 0x5d, 0xd3, 0x06, 0xb3, 0x42,
	0x28, 0x6a, 0xd5, 0x0a, 0x52, 0x51, 0x4a, 0x41, 0x2a, 0xfd, 0x93, 0x52, 0x04, 0x4e, 0xa3, 0x49,
	0xa9, 0x40, 0xe2, 0xb2, 0x59, 0x4f, 0x92, 0x55, 0x6c, 0xef, 0x76, 0x76, 0x6d, 0x9a, 0x1e, 0xf8,
	0x00, 0x1c, 0xf8, 0x0a, 0x9c, 0x40, 0x1c, 0x40, 0xe2, 0xc0, 0x81, 0x03, 0x9f, 0x04, 0x21, 0xf1,
	0x09, 0xb8, 0xf0, 0x09, 0xd0, 0x9b, 0x9d, 0xf5, 0xce, 0xec, 0x6e, 0x62, 0x82, 0x1a, 0xa9, 0xdc,
	0xe6, 0xbd, 0xf9, 0xed, 0xcc, 0xfb, 0xff, 0xde, 0x2c, 0xb4, 0x46, 0x2c, 0x72, 0x06, 0x4e, 0xe4,
	0x5c, 0x0b, 0xb8, 0x1f, 0xf9, 0xa4, 0x9e, 0xd2, 0xbb, 0xf6, 0x15, 0x58, 0xfa, 0x90, 0x45, 0xdb,
	0x93, 0xdd, 0xa1, 0xe7, 0x7e, 0xcc, 0x8e, 0x28, 0x7b, 0x4a, 0x3a, 0xb0, 0x38, 0x65, 0x3c, 0xf4,
	0xfc, 0x71, 0xc7, 0xe8, 0x19, 0xeb, 0x4d, 0x9a, 0x90, 0xf6, 0x13, 0x68, 0xeb, 0xe0, 0x30, 0x20,
	0x17, 0xa1, 0x16, 0x24, 0x0c, 0x81, 0x6f, 0xd0, 0x94, 0x41, 0x5e, 0x87, 0xe6, 0x8c, 0x78, 0xe8,
	0x84, 0x07, 0x9d, 0x92, 0x40, 0xe8, 0x4c, 0xfb, 0x77, 0x03, 0xea, 0xfd, 0xc3, 0x07, 0xfe, 0x70,
	0xc0, 0xf8, 0x89, 0x12, 0x90, 0x55, 0xa8, 0x8e, 0xfd, 0x01, 0xfb, 0x68, 0x20, 0x0f, 0x92, 0x14,
	0x4a, 0x11, 0x79, 0x23, 0x16, 0x46, 0xce, 0x28, 0xe8, 0x94, 0x7b, 0xc6, 0xba, 0x49, 0x53, 0x06,
	0xb9, 0x0a, 0xd5, 0xc0, 0xe1, 0x6c, 0x1c, 0x75, 0xcc, 0x9e, 0xb1, 0x5e, 0xdf, 0x38, 0x77, 0x4d,
	0x31, 0xc1, 0xb5, 0x07, 0xde, 0x90, 0x6d, 0x3b, 0xd1, 0x01, 0x95, 0x20, 0xbc, 0x64, 0x4f, 0xc8,
	0xd2, 0xa9, 0xf4, 0xca, 0xeb, 0x35, 0x2a, 0x29, 0xd2, 0x83, 0xba, 0x37, 0x8e, 0x18, 0x77, 0xdc,
	0xc8, 0x9b, 0xb2, 0x4e, 0xb5, 0x67, 0xac, 0x5b, 0x54, 0x65, 0x11, 0x02, 0x66, 0xe8, 0xed, 0x8f,
	0x3b, 0x8b, 0x42, 0x38, 0xb1, 0xb6, 0x3f, 0x07, 0x2b, 0xb9, 0x81, 0xac, 0x80, 0x19, 0x38, 0xd1,
	0x81, 0xd0, 0xaa, 0xf6, 0x70, 0x81, 0x0a, 0x8a, 0xb4, 0xa1, 0xe4, 0x49, 0x85, 0x1e, 0x2e, 0xd0,
	0x92, 0x37, 0x40, 0x03, 0x84, 0x81, 0xe3, 0xb2, 0x2d, 0x5f, 0x28, 0xd3, 0xa4, 0x09, 0x79, 0xb7,
	0x0e, 0x35, 0x7f, 0xcc, 0x1e, 0xed, 0xe1, 0x71, 0xf6, 0x2d, 0x68, 0xa4, 0x66, 0x0b, 0x03, 0xbc,
	0xde, 0xf5, 0x07, 0x4c, 0x1a, 0x4d, 0xac, 0x51, 0x19, 0xc6, 0x79, 0x3f, 0xdc, 0x17, 0x17, 0xd4,
	0xa8, 0xa4, 0xec, 0x3f, 0xca, 0xb0, 0x7c, 0xef, 0x80, 0xb9, 0x87, 0x28, 0xdc, 0xe6, 0x33, 0x2f,
	0x8c, 0x5e, 0x02, 0xcb, 0x77, 0xc1, 0xda, 0xf3, 0x86, 0x4c, 0x44, 0x4a, 0x45, 0x5c, 0x33, 0xa3,
	0x93, 0xbd, 0x1d, 0xef, 0x79, 0x6c, 0x7a, 0x93, 0xce, 0xe8, 0x64, 0xef, 0xf1, 0x51, 0xc0, 0x84,
	0xed, 0x6b, 0x74, 0x46, 0x93, 0x35, 0x00, 0x36, 0x76, 0xf9, 0x51, 0x10, 0x61, 0x84, 0x5a, 0xe2,
	0x54, 0x85, 0x93, 0x0f, 0xd1, 0x5a, 0x41, 0x88, 0x26, 0x37, 0x6c, 0x39, 0x23, 0xd6, 0x81, 0xf4,
	0x06, 0xa4, 0x31, 0x2e, 0x70, 0xdd, 0xf7, 0x07, 0x8f, 0xbd, 0x11, 0xeb, 0xd4, 0x85, 0x70, 0x2a,
	0x2b, 0xf9, 0xfa, 0xbe, 0x13, 0x39, 0x9d, 0x46, 0xaa, 0x17, 0xd2, 0xd9, 0xa8, 0x6a, 0xe6, 0xa3,
	0x6a, 0x0d, 0x60, 0xcc, 0xbe, 0x7c, 0x22, 0xfd, 0xd2, 0x12, 0x00, 0x85, 0x33, 0x8b, 0xba, 0x25,
	0x25, 0xea, 0x7e, 0x2c, 0x01, 0xc9, 0xba, 0xf7, 0x74, 0x11, 0x42, 0x6e, 0x42, 0x2d, 0x8c, 0x7c,
	0x1e, 0x5b, 0x15, 0x3d, 0xdb, 0xda, 0xe8, 0xe6, 0xdc, 0xb7, 0x93, 0x20, 0x68, 0x0a, 0x26, 0x6f,
	0x40, 0x0b, 0x31, 0xdb, 0x1e, 0x73, 0xd9, 0x3d, 0x7f, 0x22, 0xbd, 0xdf, 0xa4, 0x19, 0x2e, 0xb9,
	0x0c, 0xed, 0x29, 0xe3, 0xde, 0xde, 0x91, 0x82, 0xac, 0x08, 0x64, 0x8e, 0x4f, 0x6c, 0x68, 0x70,
	0x16, 0x0c, 0x3d, 0xd7, 0x89, 0x71, 0x55, 0x81, 0xd3, 0x78, 0xe4, 0x26, 0x58, 0x01, 0xf7, 0xa7,
	0x1e, 0xa6, 0xee, 0x62, 0xaf, 0xbc, 0x5e, 0xdf, 0xb8, 0xa8, 0x09, 0x4c, 0x63, 0xf0, 0xb6, 0xc4,
	0xd0, 0x19, 0xda, 0xfe, 0xd6, 0x80, 0xa5, 0xcc, 0xae, 0x12, 0xf1, 0x86, 0x16, 0xf1, 0xab, 0x50,
	0x0d, 0x19, 0x9f, 0x32, 0x9e, 0xd8, 0x2b, 0xa6, 0xd0, 0xb6, 0x81, 0xcf, 0x23, 0x99, 0xb1, 0x62,
	0xad, 0x67, 0x87, 0x99, 0xcd, 0x8e, 0x55, 0xa8, 0x46, 0x9e, 0x7b, 0xc8, 0x62, 0xad, 0x6b, 0x54,
	0x52, 0x78, 0x92, 0x33, 0x89, 0x0e, 0x84, 0x8e, 0x0d, 0x2a, 0xd6, 0xf6, 0x5f, 0x06, 0xac, 0x7c,
	0x1a, 0x0c, 0x7d, 0x67, 0x20, 0xb2, 0x86, 0x33, 0x4c, 0x99, 0xb3, 0x48, 0x59, 0x35, 0x07, 0xcd,
	0x13, 0x72, 0xb0, 0x92, 0xc9, 0xc1, 0x77, 0xa1, 0x16, 0x38, 0x3c, 0xf2, 0x22, 0x94, 0xa4, 0x2a,
	0xac, 0xff, 0x8a, 0x66, 0xfd, 0x9d, 0x60, 0xe8, 0x45, 0xdb, 0x09, 0x84, 0xa6, 0xe8, 0xc2, 0xb2,
	0xb9, 0x09, 0x2d, 0xfd, 0x03, 0x72, 0x1d, 0x2a, 0x01, 0xc6, 0x43, 0xc7, 0x10, 0x87, 0x5f, 0xd2,
	0x0e, 0x17, 0x91, 0x82, 0x32, 0xde, 0x19, 0x0f, 0x50, 0x1c, 0x1a, 0x63, 0xed, 0x5b, 0xd0, 0xce,
	0x6e, 0xe1, 0x75, 0x07, 0xa8, 0x5d, 0xec, 0x56, 0xb1, 0x8e, 0x45, 0x78, 0xce, 0x84, 0xa5, 0x9a,
	0x54, 0xac, 0xed, 0xcf, 0xe0, 0x5c, 0x81, 0xc5, 0xc3, 0x80, 0xdc, 0x56, 0x55, 0x8d, 0xa5, 0x79,
	0x4d, 0x93, 0x66, 0x93, 0x3b, 0xe1, 0x84, 0xb3, 0x7b, 0xfe, 0x80, 0x15, 0x29, 0x6c, 0x3f, 0x83,
	0x95, 0x22, 0x08, 0xb9, 0x0b, 0x8d, 0x24, 0x24, 0xef, 0x4c, 0x44, 0x9f, 0xc0, 0xb3, 0xd7, 0xb4,
	0xb3, 0xef, 0x0e, 0x7d, 0xf7, 0x70, 0x5b, 0x41, 0x51, 0xed, 0x1b, 0xdd, 0xbb, 0xa5, 0x8c, 0x77,
	0xed, 0xef, 0x0c, 0x58, 0xce, 0x9d, 0xf0, 0x42, 0x42, 0x7d, 0x05, 0x2a, 0x21, 0x5a, 0x48, 0x04,
	0x8d, 0x45, 0x63, 0x82, 0xdc, 0x00, 0x0b, 0xed, 0x2b, 0xb4, 0xa9, 0x08, 0x6d, 0xba, 0xc7, 0xf8,
	0x0d, 0x35, 0x99, 0x61, 0x6d, 0x17, 0x9a, 0xda, 0xd6, 0xbf, 0x75, 0x9a, 0x92, 0x53, 0xe5, 0xc2,
	0x9c, 0x32, 0x95, 0x9c, 0xfa, 0xb3, 0x0c, 0xcb, 0xa9, 0x87, 0xef, 0xfb, 0x63, 0xf6, 0x3f, 0xee,
	0x81, 0x7a, 0x9f, 0x5b, 0x9c, 0xdf, 0xe7, 0xac, 0x79, 0x7d, 0xae, 0x76, 0x72, 0x9f, 0x83, 0x7c,
	0x9f, 0xd3, 0x6a, 0x40, 0xbd, 0xa8, 0x06, 0x60, 0x8f, 0x28, 0xac, 0x01, 0x99, 0x36, 0xd8, 0x98,
	0xd7, 0x06, 0x9b, 0xc7, 0xb6, 0xc1, 0x96, 0x52, 0x45, 0x6e, 0x43, 0x4b, 0xbf, 0x92, 0x5c, 0x85,
	0xca, 0x2e, 0xc6, 0xbf, 0xcc, 0xad, 0xf3, 0x79, 0xf1, 0x44, 0x7a, 0xd0, 0x18, 0x65, 0x7f, 0x63,
	0x00, 0xa4, 0xdc, 0xb9, 0x51, 0x68, 0xca, 0x28, 0xec, 0x82, 0x25, 0xbe, 0xdf, 0x61, 0x4f, 0x65,
	0x92, 0xcc, 0x68, 0xdc, 0x73, 0xb1, 0x33, 0x87, 0x93, 0x91, 0xcc, 0x95, 0x19, 0x8d, 0x56, 0x10,
	0x6d, 0x74, 0x2b, 0x0e, 0x33, 0xcc, 0x98, 0x06, 0x55, 0x59, 0xf6, 0x07, 0x40, 0xb2, 0x21, 0x7b,
	0xca, 0xc9, 0xef, 0xfb, 0x12, 0x34, 0x3e, 0xf1, 0xc2, 0x08, 0x0f, 0x08, 0x5f, 0x8e, 0x80, 0x0f,
	0x9c, 0xfd, 0xb4, 0xa9, 0x34, 0xe9, 0x8c, 0x46, 0xd1, 0x70, 0xbd, 0x35, 0x19, 0xc9, 0x86, 0x9f,
	0x90, 0xe4, 0x2d, 0xb0, 0x42, 0x9f, 0x47, 0xb3, 0x91, 0xaf, 0x95, 0xb9, 0x66, 0x47, 0x6e, 0xd2,
	0x19, 0x0c, 0x2f, 0x72, 0x42, 0xf7, 0x11, 0xc7, 0xf1, 0xc0, 0x8a, 0x0d, 0x9f, 0xd0, 0xb3, 0xe0,
	0xa9, 0x29, 0xc1, 0xf3, 0xb5, 0x01, 0x4d, 0xc5, 0x50, 0xa7, 0x1c, 0x9f, 0x7a, 0x50, 0x8f, 0xfc,
	0xc8, 0x19, 0x52, 0xe6, 0xfa, 0x7c, 0x20, 0xa3, 0x40, 0x65, 0x91, 0x2b, 0x50, 0xde, 0xf3, 0xf7,
	0x3a, 0xa6, 0x08, 0xc4, 0x0b, 0x39, 0x23, 0x3d, 0xe2, 0x72, 0xb4, 0x47, 0x94, 0xfd, 0xab, 0x01,
	0x0d, 0x95, 0x4b, 0x5a, 0xe2, 0xd5, 0x10, 0x07, 0x22, 0xbe, 0x19, 0xd2, 0x57, 0x4b, 0x49, 0xe8,
	0x96, 0xbc, 0x5a, 0x08, 0x98, 0x63, 0xcc, 0xe6, 0xb8, 0x1c, 0x8a, 0x35, 0x9a, 0x75, 0x24, 0xb3,
	0x38, 0x1e, 0x4a, 0x12, 0xf2, 0x2c, 0x26, 0x70, 0xfb, 0x27, 0x31, 0x5c, 0x45, 0xdc, 0x63, 0x53,
	0x86, 0x2a, 0xbc, 0x4c, 0x53, 0x4b, 0xe2, 0xf7, 0xaa, 0xe2, 0xf7, 0xbf, 0x0d, 0x68, 0xeb, 0xf2,
	0x9e, 0xd2, 0xf5, 0xea, 0xb8, 0x5f, 0xce, 0x8c, 0xfb, 0xaa, 0xa1, 0xcc, 0x13, 0x9f, 0x2a, 0x95,
	0x5c, 0x09, 0x7f, 0x3f, 0x3f, 0x62, 0xad, 0x65, 0x06, 0xdc, 0x58, 0xea, 0xc2, 0x0a, 0xab, 0x19,
	0x70, 0x31, 0x3b, 0x18, 0x6c, 0xc2, 0x72, 0xee, 0x6b, 0xf2, 0xa6, 0x5e, 0x2c, 0xbb, 0x85, 0x97,
	0x69, 0xf5, 0xf2, 0x07, 0x03, 0x9a, 0xda, 0xc6, 0x99, 0x97, 0xcc, 0x77, 0xe4, 0x33, 0x05, 0xeb,
	0xa3, 0x1c, 0x31, 0x2e, 0x14, 0xca, 0x89, 0x00, 0x9a, 0x62, 0xed, 0xaf, 0xa0, 0xa1, 0x6e, 0xbd,
	0x90, 0x21, 0x28, 0x9d, 0x3e, 0xcc, 0xc2, 0xe9, 0xa3, 0xa2, 0x4c, 0x1f, 0xbf, 0x19, 0x50, 0xa3,
	0x6c, 0xe4, 0x4f, 0xcf, 0x6a, 0xea, 0x88, 0x1c, 0xbe, 0xcf, 0xe6, 0x15, 0xe1, 0x18, 0x84, 0x87,
	0x71, 0xe6, 0x4e, 0x78, 0x88, 0xcd, 0xb7, 0x22, 0x4c, 0x9c, 0x32, 0x0a, 0xb3, 0xe4, 0x26, 0x40,
	0x22, 0xfd, 0x29, 0x1b, 0xd0, 0xcf, 0x06, 0x2c, 0xf6, 0xcf, 0x4e, 0xed, 0xd0, 0x9f, 0x70, 0x97,
	0xcd, 0x51, 0x3b, 0x06, 0xa1, 0xd8, 0x03, 0x16, 0x26, 0xef, 0x2f, 0xb1, 0x2e, 0x6c, 0x05, 0x37,
	0xc0, 0xea, 0xff, 0x07, 0x55, 0x2f, 0x6f, 0x40, 0x53, 0x7b, 0x25, 0x93, 0x25, 0xa8, 0x2b, 0x93,
	0x7f, 0x7b, 0x81, 0xb4, 0xa1, 0xd1, 0x9f, 0x0c, 0x23, 0x4f, 0xbe, 0x3e, 0xdb, 0xc6, 0xe5, 0x2b,
	0x60, 0x25, 0xcd, 0x8b, 0x58, 0x60, 0xe2, 0xe8, 0xd5, 0x5e, 0x20, 0x75, 0xb4, 0x99, 0xa8, 0xd1,
	0x6d, 0x03, 0xd9, 0x58, 0xbd, 0xda, 0xa5, 0x8d, 0x5f, 0x2a, 0xb0, 0xd4, 0x77, 0x62, 0x0d, 0x77,
	0x18, 0x9f, 0x7a, 0x2e, 0x23, 0x7d, 0x68, 0xa8, 0xbf, 0xe9, 0x88, 0xfe, 0x08, 0xce, 0xfc, 0xee,
	0xeb, 0x5e, 0x3a, 0x61, 0x37, 0x0c, 0xec, 0x05, 0x72, 0x07, 0xac, 0xe4, 0x2f, 0x13, 0xe9, 0x68,
	0x60, 0xe5, 0x9f, 0x5d, 0xf7, 0xc2, 0x31, 0x3b, 0xe2, 0x88, 0x1d, 0x68, 0xe9, 0x3f, 0x23, 0x88,
	0x5e, 0xb7, 0x72, 0x3f, 0xa2, 0xba, 0xaf, 0x9e, 0xb8, 0x2f, 0x0e, 0xfd, 0x42, 0x1d, 0xde, 0xe5,
	0xf3, 0x8c, 0xe8, 0xef, 0xb0, 0xa2, 0x07, 0x73, 0xd7, 0x9e, 0x07, 0x49, 0x44, 0xd6, 0xe7, 0xac,
	0x8c, 0xc8, 0xb9, 0x77, 0x43, 0x46, 0xe4, 0xfc, 0x90, 0x66, 0x2f, 0x90, 0xfb, 0x50, 0x9b, 0x0d,
	0x14, 0x44, 0xb7, 0x98, 0x3a, 0x91, 0x75, 0xbb, 0xc7, 0x6d, 0x89, 0x53, 0xfa, 0x69, 0xe1, 0x42,
	0x36, 0xb9, 0x58, 0x58, 0xee, 0x64, 0xa7, 0xcd, 0xf8, 0x37, 0xdb, 0xd7, 0xec, 0x05, 0xf2, 0x1e,
	0x54, 0xe3, 0x44, 0x26, 0xab, 0x19, 0xa8, 0xac, 0x4d, 0xdd, 0xf3, 0x85, 0x7c, 0xf1, 0xf1, 0xdb,
	0x60, 0x62, 0x62, 0x90, 0x15, 0xdd, 0xfd, 0xf2, 0xc3, 0x73, 0x05, 0x5c, 0xfc, 0x6c, 0xb7, 0x2a,
	0x7e, 0x45, 0x5f, 0xff, 0x27, 0x00, 0x00, 0xff, 0xff, 0xea, 0xe5, 0x8a, 0x64, 0x9c, 0x16, 0x00,
	0x00,
}
